### ISSUE TITLE
[v1.0.0-beta.2] cacheKey doesn't take uglifyOptions into account

### ISSUE THREAD

**Issue by mikesherov** [webpack-contrib/uglifyjs-webpack-plugin#100]
The cache key for cached version of the output should also include the options passed to uglify, otherwise, the same input with different options will yeild incorrect output.

**Comment by hulkish** [comment]
@mikesherov What solution do u recommend?

**Comment by mikesherov** [comment]
No, I recommend stringifying the uglifyOptions as part of the cacheKey generation at the same spot uglify version number is appended.
