### ISSUE TITLE
Shouldn't there be a way to pass in a specified Uglify version?

### ISSUE THREAD

**Issue by andyhall** [webpack-contrib/uglifyjs-webpack-plugin#102]
I've had an unpleasant issue where the current version of Uglify#harmony (3.0.27) minimizes my code fine, but the version inside this plugin (2.8.29) barfs. Paradoxically the only way I can figure out to fix this is to "downgrade" to the `uglifyjs-webpack-plugin2` plugin (since it gets uglify via peer dependency).

Am I missing some obvious undocumented way to handle this? If not, would it not make sense to accept an optional passed-in library that overrides the embedded uglify dependency, like:

```js
var newestUglify = require('uglify-js')
var plugins = [
	new UglifyPlugin({
		uglify: newestUglify,
	})
]
```
or some such?

Thanks!

**Comment by nifgraup** [comment]
use the latest uglifyjs-webpack-plugin beta, it depeds on uglify-es 3

**Comment by michael-ciniawsky** [comment]
`npm i -D uglifyjs-webpack-plugin@beta` (`uglify-es`)

**Comment by andyhall** [comment]
Thanks! Maybe worth mentioning in the readme or similar.
