### ISSUE TITLE
Fails on `let`?

### ISSUE THREAD

**Issue by trusktr** [webpack-contrib/uglifyjs-webpack-plugin#105]
I tried this, with

```
    "uglifyjs-webpack-plugin": "^0.4.6",
    "uglify-js": "mishoo/UglifyJS2#harmony-v2.8.22",
```

in my dependencies, but I still get this problem:

https://github.com/webpack/webpack/issues/5449

**Comment by trusktr** [comment]
I just tried with 

```
    "uglifyjs-webpack-plugin": "^0.4.6",
    "uglify-js": "mishoo/UglifyJS2#harmony",
```

in my dependencies but still no luck.

**Comment by trusktr** [comment]
Ah, well, for now I'm using babili-webpack-plugin which is working for ES6+.

**Comment by michael-ciniawsky** [comment]
v0.4.6 (`uglify-js` v2.0.0) doesn't sufficiently support ES2015. You can try out `uglifyjs-webpack-plugin@beta` `npm i -D uglifyjs-webpack-plugin@beta` which uses `uglify-es` and supports parallelization

> ⚠️  Note that the `options` interface between `v0.4.6` => `v1.0.0-beta` changed
