### ISSUE TITLE
uglifyjs-webpack-plugin cannot recognize  es6  array spread operator

### ISSUE THREAD

**Issue by imjustfly** [webpack-contrib/uglifyjs-webpack-plugin#109]
Using  the spread operator `...` will lead to an error as below:

```
ERROR in static/js/app.38dbf899165e7f1c306f.js from UglifyJs
Unexpected token: punc (.) [./main.js:23,0][static/js/app.38dbf899165e7f1c306f.js:649,4]
```

the code is like this

```
new TabRouter([
    ...demoRoutes
])
```

and my config in webpack:

```
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      },
      sourceMap: true,
      uglifyOptions: {
        ecma: 8
      }
    }),
```

**Comment by evilebottnawi** [comment]
@imjustfly can your provide minimum reproducible test repo?

**Comment by kzc** [comment]
>     new webpack.optimize.UglifyJsPlugin({

This indicates that `uglify-js@2` is being used which can only process ES5.

`uglify-es` can handle array spreads...

```
$ bin/uglifyjs -V
uglify-es 3.0.27

$ echo 'new TabRouter([ ...demoRoutes ])' | bin/uglifyjs -mc
new TabRouter([...demoRoutes]);
```
See: https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/104#issuecomment-321376934

**Comment by michael-ciniawsky** [comment]
Please use `npm i -D ugilfyjs-webpack-plugin@beta` instead or transpile to ES5 via `babel-loader`

**Comment by fritx** [comment]
When using uglifyjs-webpack-plugin@1.0.0-beta.2,

I had to disable the existing `compress` option:

```js
plugins: [
  new UglifyJSPlugin({
      // compress: {
      //   warnings: false
      // },
      sourceMap: true
    }),
]
```

Otherwise I will get a validation Error without any descripton:

```plain
> node build/build.js

/Users/user/Project/node_modules/schema-utils/dist/validateOptions.js:40
    throw new _ValidationError2.default(ajv.errors, name);
    ^

false
```

**Comment by evilebottnawi** [comment]
@fritx can you create minimum reproducible test repo? And create new issue around your problem?

**Comment by kzc** [comment]
@fritx The options in `uglifyjs-webpack-plugin@1.0.0-beta` have changed and are not backwards compatible with `0.4.6`.

See [uglifyOptions](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/v1.0.0-beta.2/README.md#uglifyoptions)

**Comment by fritx** [comment]
@evilebottnawi @kzc oh, didn't noticed that.
