### ISSUE TITLE
[v1.0.0-beta.2] sourcemap not work in parallel

### ISSUE THREAD

**Issue by jinker** [webpack-contrib/uglifyjs-webpack-plugin#111]
first set cache true, parallel false
then parallel true, the sourcemap not work

**Comment by evilebottnawi** [comment]
@jinker thanks for issue, `uglifyjs-webpack-plugin` don't contain `cache` now, it is implement only in https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/108. We have only `parallel` option. Can your provide minimum test repo, thanks!

**Comment by crazyxhz** [comment]
I'm also have this issue. 
```
devtools:'#source-map',
plugins: [
... 
new UglifyJSPlugin({
      parallel: true,
      sourceMap: true
    }),
...]
```
when set parallel to true, source map is not generated.
I'm using v1.0.0 beta2

**Comment by evilebottnawi** [comment]
@crazyxhz should be fixed after approved https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/108, also i add tests, thanks!

**Comment by crazyxhz** [comment]
@evilebottnawi  sorry, it's a typo, I'm using devtool correcly in my webpack config

**Comment by evilebottnawi** [comment]
@crazyxhz after review https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/108 i can add tests for this and if don't works as expected i will fix this, thanks!

**Comment by evilebottnawi** [comment]
@jinker @crazyxhz problem still exists?

**Comment by michael-ciniawsky** [comment]
#173
