### ISSUE TITLE
Plugin breaks to minify es2015 and newer

### ISSUE THREAD

**Issue by code-chris** [webpack-contrib/uglifyjs-webpack-plugin#112]
Hi,
today I changed my TypeScript "target" setting from "es5" to "es2015". This caused an compile error in one of my typescript files:
```
ERROR in main.js?bust=oqYFU from UglifyJs
Unexpected token: name (App) [./app/App.ts:19,13][main.js?bust=oqYFU:78963,8]
```
The line and column refers to the class name. This error happens too with more modern target settings.

My setup:
- TypeScript 2.4.2
- Webpack 3.5.4
- uglifyjs-webpack-plugin 1.0.0-beta.2
- uglify-js 3.0.10
- OS Windows 10
- Node 8.1.2

Maybe this relates to #49, but I'm not sure.

Does anybody know why this happens? If you need more information, please tell me.
Thanks!

**Comment by kzc** [comment]
https://stackoverflow.com/a/45088328

**Comment by evilebottnawi** [comment]
@code-chris link above help to solve problem, if not please provide a minimum reproducible test repo, thanks!

**Comment by code-chris** [comment]
Thanks for your quick reply, but the issue still occurs: https://github.com/code-chris/uglifyjs-repro

**Comment by kzc** [comment]
`uglifyjs-webpack-plugin@0.4.6` and `uglify-js@2.x` can only minify ES5:

https://github.com/code-chris/uglifyjs-repro/blob/8bd2d31083fcdd34fcb64acf5e124238225c061f/package.json#L10

```
    "uglifyjs-webpack-plugin": {
      "version": "0.4.6",
      "resolved": "https://registry.npmjs.org/uglifyjs-webpack-plugin/-/uglifyjs-webpack-plugin-0.4.6.tgz",
      "integrity": "sha1-uVH0q7a9YX5m9j64kUmOORdj4wk=",
      "dev": true,
      "requires": {
        "source-map": "0.5.7",
        "uglify-js": "2.8.29",
        "webpack-sources": "1.0.1"
      }
    },
```

If you've configured it successfully you would see `uglify-es` in [`package-lock.json`](https://github.com/code-chris/uglifyjs-repro/blob/8bd2d31083fcdd34fcb64acf5e124238225c061f/package-lock.json).

**Comment by code-chris** [comment]
@kzc sorry, my fault. Yes, this fixed the original issue. Now I hit the same bug as described in #31.

**Comment by kzc** [comment]
The stackoverflow instructions do work. All I can suggest is to delete `node_modules` and do a fresh `npm install` and verify the module versions in `package-lock.json`.

People experiencing issues configuring webpack should wait for the `uglifyjs-webpack-plugin @1.0.0` release.

**Comment by code-chris** [comment]
clean install brings the initial error again, but ok. Is there a final release date planned (or a rough range) ?

**Comment by evilebottnawi** [comment]
@code-chris First we should review https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/108, some time later we will do final release, thanks!

**Comment by michael-ciniawsky** [comment]
`npm i -D  uglifyjs-webpack-plugin@beta` (`uglify-es`) => Minify ES2015+

**Comment by kzc** [comment]
@code-chris The reason for your [test repo](https://github.com/code-chris/uglifyjs-repro)'s failure are [these two lines](https://github.com/code-chris/uglifyjs-repro/blob/4d19b8376b710e4923c1aa6d648c792187bd76c2/package.json#L15-L16):
```js
    "prod": "webpack -p",
    "dev": "webpack -d"
```
You need to change them to:
```
    "prod": "webpack --define process.env.NODE_ENV=production",
    "dev": "webpack --define process.env.NODE_ENV=development"
```

`webpack@3.5.5`'s `-p` and `-d` flags make use of `uglifyjs-webpack-plugin@0.4.6` which uses the ES5-only `uglify-js@2.8.29`. This is not obvious at all and should probably be mentioned in the README.

ref: https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/104#issuecomment-321529673

**Comment by code-chris** [comment]
@kzc yes, this actually fixed the bug in my test repo... thanks!
Unfortunately in my big project (with a much more complex webpack config) the plugin does not minify anything, without an error. Hopefully I can find the issue there...

**Comment by kzc** [comment]
The problem is that webpack includes an earlier incompatible version of this plugin by name causing all the versioning confusion. Changing the plugin options only add to the confusion. The `uglify-es` version of this plugin really ought to have a different name since most users run into these same problems. I just noticed that stackoverflow is a fountain of incorrect advice on this subject - the wisdom of crowds. Better to wait for a new webpack release that makes use of the new `uglify-es` version of this plugin.
