### ISSUE TITLE
npm ERR! uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`

### ISSUE THREAD

**Issue by wfgmiami** [webpack-contrib/uglifyjs-webpack-plugin#113]
I am getting the following error when trying to install webpack on AWS EC2:

![image](https://user-images.githubusercontent.com/16696928/29629916-80091826-8808-11e7-8598-876cf88348ac.png)

**Comment by evilebottnawi** [comment]
@wfgmiami Seems your have invalid permission in your, look on your first line in screenshot. Remove `node_modules` and try to install again.

**Comment by wfgmiami** [comment]
@evilebottnawi I do not know why i get that permission denied message. I am able to install other packages like express for example. I removed node_modules, ran again but i got the same error.

**Comment by evilebottnawi** [comment]
@wfgmiami I see your work using `root`, it is not recommended (this can cause problems). But your can try to create minimum reproducible test repo, maybe it is allow to find your problem.

**Comment by wfgmiami** [comment]
@evilebottnawi Thanks for your help. I did sudo apt-get install nodejs-legacy and after than I was able to npm install webpack.

**Comment by ganeshcoolstar** [comment]
please help me .how to resolve this issue

**Comment by ganeshcoolstar** [comment]
i cant get your answer @wfgmiami ,@evilebottnawi

**Comment by evilebottnawi** [comment]
Please don't use unmaintained `uglify-webpack-plugin@0.4.6`

**Comment by ramiasg** [comment]
i have same issue
