### ISSUE TITLE
Unable to install on ARM Linux

### ISSUE THREAD

**Issue by kentenzer** [webpack-contrib/uglifyjs-webpack-plugin#115]
[npm-debug.txt](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/files/1253836/npm-debug.txt)
Hi, 

I am trying to install webpack on my Raspberry Pi, I run the following command: 
```npm install --save-dev --no-optional webpack```
and I am getting this output:
```
> uglifyjs-webpack-plugin@0.4.6 postinstall /home/pi/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

sh: 1: node: not found
npm WARN pi@1.0.0 No description
npm WARN pi@1.0.0 No repository field.
npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save-dev" "--no-optional" "webpack"
npm ERR! node v4.8.2
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script 'node lib/post_install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uglifyjs-webpack-plugin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/post_install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uglifyjs-webpack-plugin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uglifyjs-webpack-plugin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log
```
Any idea?

I attach the npm-debug output. 

Thanks, 
Ken

**Comment by michael-ciniawsky** [comment]
It's a know issue in `uglifyjs-webpack-plugin =< v0.4.6` use the current `beta` instead please `npm i -D uglifyjs-webpack-plugin@beta`, which doesn't include this file anymore

**Comment by kentenzer** [comment]
Hi Michael, 

Thanks for your quick response, using beta version, I get:
`npm WARN uglifyjs-webpack-plugin@1.0.0-beta.2 requires a peer of webpack@^2.0.0 || ^3.0.0 but none was installed.
npm WARN Neon@0.0.4 No repository field.`

However, I stil get the issue with webpack: `sudo npm install -g webpack` fails for me. 

Thanks, 
Ken

**Comment by michael-ciniawsky** [comment]
Neon is your package? Or a webpack wrapper/seed?  This also happens when installing webpack without `-g` ? This could likely be a dependency mismatch then, since webpack still ships with `0.4.6` atm and loads this version first

**Comment by kentenzer** [comment]
Hi Michael, 

Indeed, I am trying to install a [Neon](https://github.com/CityOfZion/neon-wallet) is my package.
I get the same error when running: `sudo npm install -g webpack `.

Any clue?

Thanks, 
Ken

**Comment by michael-ciniawsky** [comment]
**without** the `-g` flag :), just `npm i -D webpack uglifyjs-webpack-plugin@beta`

**Comment by kentenzer** [comment]
Thanks but same problem :(

npm ERR! uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
npm ERR! spawn ENOENT

**Comment by michael-ciniawsky** [comment]
> uglifyjs-webpack-plugin@**0.4.6** :stuck_out_tongue:

**webpack.config.js**
```js
const UglifyJSPlugin = require('uglifyjs-webpack-plugin')

{
  plugins: [ new UglifyJSPlugin() ]
}
```

**Comment by kentenzer** [comment]
This worked, thanks!

**Comment by mikeaustin** [comment]
@kentenzer what worked? I’m having this problem on an Ubuntu Amazon EC2 instance.

**Comment by kentenzer** [comment]
If you edit the webpack.config.js, then npm works.
