### ISSUE TITLE
Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script 'node lib/post_install.js'.

### ISSUE THREAD

**Issue by markfaine** [webpack-contrib/uglifyjs-webpack-plugin#117]
npm -v
4.2.0
node -v 
v7.10.1

$ sudo npm install -g  '@'angular/cli

```
/usr/bin/ng -> /usr/lib/node_modules/@angular/cli/bin/ng

 node-sass@4.5.3 install /usr/lib/node_modules/@angular/cli/node_modules/node-sass
 node scripts/install.js

module.js:472
    throw err;
    ^

Error: Cannot find module '/usr/lib/node_modules/@angular/cli/node_modules/node-sass/scripts/install.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3

uglifyjs-webpack-plugin@0.4.6 postinstall /usr/lib/node_modules/@angular/cli/node_modules/uglifyjs-webpack-plugin
node lib/post_install.js

module.js:472
    throw err;
    ^

Error: Cannot find module '/usr/lib/node_modules/@angular/cli/node_modules/uglifyjs-webpack-plugin/lib/post_install.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
/usr/lib
└── (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/@angular/cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.5.3 (node_modules/@angular/cli/node_modules/node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.5.3 install: `node scripts/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Linux 4.10.0-33-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "@angular/cli"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script 'node lib/post_install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uglifyjs-webpack-plugin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/post_install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uglifyjs-webpack-plugin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uglifyjs-webpack-plugin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mark/.npm/_logs/2017-08-31T01_59_46_840Z-debug.log

[2017-08-31T01_59_46_840Z-debug.txt](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/files/1265564/2017-08-31T01_59_46_840Z-debug.txt)


```

**Comment by evilebottnawi** [comment]
@markfaine seems not related to `uglifyjs-webpack-plugin`, because your also have error with `node-sass`:
```Error: Cannot find module '/usr/lib/node_modules/@angular/cli/node_modules/node-sass/scripts/install.js'```
Try to:
1. `rm -r node_modules`
2. `npm cache clean`
3. `npm i`

**Comment by michael-ciniawsky** [comment]
The `postinstall` script is buggy on some platforms and was removed in `v1.0.0-beta`

`npm i -D uglifyjs-webpack-plugin@beta`

**webpack.config.js**
```js
const UglifyJSPlugin = require('uglifyjs-webpack-plugin')

{
  plugins: [ new UglifyJSPlugin() ]
}
```

For the `@angular/cli` related part, please file an issue there aswell

**Comment by markfaine** [comment]
Thanks!  I was able to get it to finally install.

**Comment by logabhi** [comment]
How did you make it work with @angular/cli?

**Comment by markfaine** [comment]
I think  my problem was permissions.  I set myself as the owner of  ~/.npm and ~/.config recursively.  I then executed the command without sudo.  I'm still not sure if that was it but it did seem to install correctly after that.
________________________________________

**Comment by msegmx** [comment]
I got this error when I used the node version of the Ubuntu Xenial repo (I'm on the lates Linux Mint (18.2 Sonya), fresh install).

So I uninstalled everything (npm, node, etc), deleted ~/.node_modules and downloaded the node package from https://nodejs.org/en/download/, unzipped it and added an entry into ./.bashrc that points to that folder : 

PATH="/opt/node/bin:$PATH"

afterwards the simple setup at https://cli.angular.io/ worked.

HTH someone.

**Comment by azollai** [comment]
Hello,
I had the same issue. I had to update to the latest node.js and npm.
1. I downloaded the latest Node.js from the official page and installed(https://nodejs.org/en/download/). 
2. Take care because in Windows Command Prompt I couldn't update npm.It looked like if it was updated but it was not! In C:\Users\[Username]\AppData\Roaming I deleted the content of npm and npm-cache folders. After that I opened Git Bash and installed the latest npm =>npm install npm@5.4.2 -g .

After that deleted node_modules folder form my project and run "npm i". It was  running fine :)

**Comment by logabhi** [comment]
I finally switched to yarn to make it work. :/

**Comment by dingy007** [comment]
Encountered the same issue as of Nov-2017, with nodejs version : 4.7.2 and npm version 3.5.2, which were installed on Ubuntu 17.04 using `sudo apt get install nodejs`.

How i fixed:
- Removed existing nodejs:
`sudo apt-get purge --auto-remove nodejs`
- Followed the instructions at [godaddy help docs](https://sg.godaddy.com/help/install-nodejs-ubuntu-17395), but installed the LTS version 8, take note that as the instructions says, it already contains npm also.
- Fixed npm permission issues, so as to not use 'sudo' for angular-cli installation (for me Option-2 worked, as the npm directory is in '/usr/' and not '/usr/local/' so Option 2 was the way to go.
- Installed angular cli without sudo
`npm install -g @angular/cli`

**Comment by bichomen** [comment]
I have the same problem:

`npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-09T10_35_46_942Z-debug.log
`
Uname: 4.4.0-83-generic #106~14.04.1+7.0trisquel1
node v9.11.1
npm 5.6.0
npm i -D uglifyjs-webpack-plugin@beta installed

**Comment by isahuntercsg** [comment]
Linux Sucks Balls

**Comment by ganeshcoolstar** [comment]
i am getting same issue. how to resolve error.
 uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`

**Comment by evilebottnawi** [comment]
Please don't use unmaintained `uglify-webpack-plugin@0.4.6`

**Comment by jebuscraisp** [comment]
testrpc(eth) seems to require it, can we use an earlier version.?
