### ISSUE TITLE
how could i know the time cost by this plugin?

### ISSUE THREAD

**Issue by zzzgit** [webpack-contrib/uglifyjs-webpack-plugin#119]
hello, when webpack complete its work, we can see the time cost in the console.

![image](https://user-images.githubusercontent.com/1060733/30010875-ad939710-9165-11e7-8c51-7e6609bdd668.png)

but how could i know the time cost by uglityjs?

**Comment by evilebottnawi** [comment]
@zzzgit `webpack` don't have build-in ability to get this time (only `--profile`), but your can use this information to obtain this information:
1. https://nodejs.org/api/debugger.html 
2. https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27

**Comment by zzzgit** [comment]
is it possible to write a plugin to detect the time cost of uglifyjs-webpack-plugin?
if it is, i would like to try

**Comment by evilebottnawi** [comment]
@zzzgit Sorry, but we can not accept this PR. We avoid using logging and debugging inside Plugin code, we use this practice in all `webpack-contrib` repos. Thanks!
