### ISSUE TITLE
not able to install angular CLI on windows 7

### ISSUE THREAD

**Issue by supriya-gaurav** [webpack-contrib/uglifyjs-webpack-plugin#124]
[npm-debug.zip](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/files/1305617/npm-debug.zip)
node version -: v6.11.3
npm version -: v3.10.10
Operating system : Windows 7
Logfile is attached here for reference.

**Comment by evilebottnawi** [comment]
@supriya-gaurav please provide more information (`webpack` config and example), better minimum reproducer test repo, thank you.
Look at you debug log:
1. You don't have right premission
2. npm contain bugs. try to install to latest npm and try again

**Comment by michael-ciniawsky** [comment]
Reopen in `angular/angular-cli` please
