### ISSUE TITLE
[v1.0.0-beta.2] Removing dead code doesn't work & parsing fail on import

### ISSUE THREAD

**Issue by Kurtas** [webpack-contrib/uglifyjs-webpack-plugin#125]
Hi, 

 I have following configuration of webpack plugins
```javascript
  plugins: [
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify(process.env.NODE_ENV),
      },
    }),
    new UglifyJSPlugin({
      exclude: /node_modules/,
      parallel: true,
      uglifyOptions: {
        ie8: false,
        ecma: 8,
        warnings: false,
        mangle: true,
        compress: {
          ecma: 8,
          dead_code: true,
        }
      }
    }),...
]
```
I run build with following command
`cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color --progress --hide-modules`

1. First problem is that Uglify will fail on `import` in following code
```javascript
    if (module.hot) {
      module.hot.accept('./reducers', () => {
        import('./reducers').then(reducerModule => {
          const createReducers = reducerModule.default;
          const nextReducers = createReducers(store.asyncReducers);
          store.replaceReducer(nextReducers);
        });
      });
    }
```
```javascript
ERROR in app.7ec7b505e69d5acb6a31.js from UglifyJs
Unexpected token: punc (() [app.7ec7b505e69d5acb6a31.js:16938,14]
```
2. Dead code removal doesn't work
So I decided use removing `dead_code` and I wrap the code by this way
```javascript
  if (process.env.NODE_ENV === 'development') {
    if (module.hot) {
      module.hot.accept('./reducers', () => {
        import('./reducers').then(reducerModule => {
          const createReducers = reducerModule.default;
          const nextReducers = createReducers(store.asyncReducers);

          store.replaceReducer(nextReducers);
        });
      });
    }
  }
```
but ther error is still there, so removing of dead code probably doesn't work also.

**Comment by kzc** [comment]
`uglify-es` supports the ES2017/ES8 standard.

[Dynamic `import`](https://github.com/tc39/proposal-dynamic-import) is a stage 3 proposal.

I was under the impression that Webpack itself is supposed to [handle dynamic `import`](https://webpack.js.org/guides/code-splitting/#dynamic-imports) and transpile it to another form.

**Comment by kzc** [comment]
`uglify-es@3.1.3` now supports dynamic import.

**Comment by michael-ciniawsky** [comment]
@Kurtas Could you run `npm update`  and test with `uglify-es >= 3.1.3` and test if this fixes the issue ?

**Comment by Kurtas** [comment]
@michael-ciniawsky @kzc I tried a new version and the build passed
Thanks

**Comment by scabbiaza** [comment]
Hello! I have the same issue with tree shaking.

I see you suggested to update `uglify-es >= 3.1.3`, however in your `package.json` version is
`"uglify-es": "^3.0.24"`

https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/package.json#L37
https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/package-lock.json#L8072

------

**Example of the not working tree shaking**
```js
"webpack": "^3.7.1"
"uglifyjs-webpack-plugin": "^1.0.0-beta.3",
```

`a.js`
```js
export function initA() {
  console.log("aaa")
}

export function initB() {
  console.log("bbb")
}
```

`main.js`
```js
import {initA} from "./a"

initA()
```

Result bundle created from `main.js` contains `initB` code, but it shouldn't, right?
(i did unuglify)

```js
! function(n) {
    function t(o) {
        if (e[o]) return e[o].exports;
        var r = e[o] = {
            i: o,
            l: !1,
            exports: {}
        };
        return n[o].call(r.exports, r, r.exports, t), r.l = !0, r.exports
    }
    var e = {};
    t.m = n, t.c = e, t.d = function(n, e, o) {
        t.o(n, e) || Object.defineProperty(n, e, {
            configurable: !1,
            enumerable: !0,
            get: o
        })
    }, t.n = function(n) {
        var e = n && n.__esModule ? function() {
            return n.default
        } : function() {
            return n
        };
        return t.d(e, "a", e), e
    }, t.o = function(n, t) {
        return Object.prototype.hasOwnProperty.call(n, t)
    }, t.p = "/", t(t.s = 0)
}([function(n, t, e) {
    var o, r;
    o = [e(1)], void 0 !== (r = function(n) {
        "use strict";
        (0, n.initA)()
    }.apply(t, o)) && (n.exports = r)
}, function(n, t, e) {
    var o, r;
    o = [t], void 0 !== (r = function(n) {
        "use strict";
        Object.defineProperty(n, "__esModule", {
            value: !0
        }), n.initA = function() {
            console.log("aaa")
        }, n.initB = function() {
            console.log("bbbb") // <<<<<<<<<<<<<<<<<<<<<<
        }
    }.apply(t, o)) && (n.exports = r)
}]);
```

**Comment by StuRuby** [comment]
Hello ,I have the same issue with tree shaking .
I have two js file .
`print.js`
`export function printMe() {
    alert('I get called from print.js!');
}

export function printYou() {
    alert(`you !`);
}`

`index.js`

`
import { printMe }  from './print';

function component() {
    var element = document.createElement('div');
    var btn = document.createElement('button');
    element.innerHTML = 'Hello Webpack'
    btn.innerHTML = 'Click me and check the console';
    btn.onclick = printMe;
    element.appendChild(btn);
    return element;
}

document.body.appendChild(component());
`

`webpack.config.js`

`
new UglifyWebpackPlugin({
            uglifyOptions: {
                compress: {
                    ecma: 8,
                    dead_code: true
                }
            }
        })
`

when I run `webpack` command. It seems does not tree shaking . 
`
!function(r){var t={};function n(e){if(t[e])return t[e].exports;var o=t[e]={i:e,l:!1,exports:{}};return r[e].call(o.exports,o,o.exports,n),o.l=!0,o.exports}n.m=r,n.c=t,n.d=function(r,t,e){n.o(r,t)||Object.defineProperty(r,t,{configurable:!1,enumerable:!0,get:e})},n.r=function(r){Object.defineProperty(r,"__esModule",{value:!0})},n.n=function(r){var t=r&&r.__esModule?function(){return r.default}:function(){return r};return n.d(t,"a",t),t},n.o=function(r,t){return Object.prototype.hasOwnProperty.call(r,t)},n.p="/",n(n.s="./src/print.js")}({"./src/print.js":function(r,t,n){"use strict";function e(){alert("I get called from print.js!")}function o(){alert("you !")}n.r(t),n.d(t,"printMe",function(){return e}),n.d(t,"printYou",function(){return o})}});
`

**Comment by evilebottnawi** [comment]
Please read this issue https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/247
