### ISSUE TITLE
From a fresh install, uglifyjs-webpack-plugin@0.4.6 postinstall error prevents from installing webpack

### ISSUE THREAD

**Issue by ea167** [webpack-contrib/uglifyjs-webpack-plugin#127]
Hello,

From a fresh install, with npm cache cleaned, etc.
When I try to install webpack (v3.6.0) I get the error: 

> uglifyjs-webpack-plugin@0.4.6 postinstall /root/EVGIT/audio-bo-client/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

module.js:491
    throw err;
    ^

Error: Cannot find module '/root/EVGIT/audio-bo-client/node_modules/webpack/node_modules/uglifyjs-webpack-plugin/lib/post_install.js'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script.

npm 5.3.0 on centos7

Thank you for your help.

**Comment by michael-ciniawsky** [comment]
Yep, it's know issue please consider using the current `beta` instead `npm i -D uglifyjs-webpack-plugin@beta`
