### ISSUE TITLE
In webpack documentation there is `compress` in` uglifyOptions`, but that does not work properly

### ISSUE THREAD

**Issue by km-tr** [webpack-contrib/uglifyjs-webpack-plugin#128]
1. webpack@3.6.0
2. https://github.com/km-tr/webpack-uglifyOptions-error
3. 
    - Mac OS 10.12.6
    - node v6.10.2

`webpack.optimize.UglifyJsPlugin` did not work properly as it was documented
I have an example in the above repository.

[webpack doc](https://webpack.js.org/plugins/uglifyjs-webpack-plugin/#uglifyoptions)

**Comment by kzc** [comment]
You missed this line from 
https://webpack.js.org/plugins/uglifyjs-webpack-plugin/#options ...

> ⚠️ The following options are for the latest beta version. If you would like to see the options for the latest built-in version of the plugin in webpack, see the [v0.4.6 docs](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/tree/v0.4.6).

**Comment by michael-ciniawsky** [comment]
```
npm i -D uglifyjs-webpack-plugin@beta
```

**webpack.config.js**
```js
const UglifyJSPlugin = require('uglifyjs-webpack-plugin')

const config = {
  ...
  plugins: [
    new UglifyJSPlugin(...options)
  ]
}
```
