### ISSUE TITLE
Error in common.js from UglifyJs Unexpected token: name (urlParts) [common.js8648.4]

### ISSUE THREAD

**Issue by MEDIOCAL** [webpack-contrib/uglifyjs-webpack-plugin#132]
var path = require('path');
var webpack = require('webpack');
var ExtractTextPlugin = require("extract-text-webpack-plugin");
var HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
    entry: {
        home: [
            'babel-polyfill',
            './src/home/main.js'
        ],
        common: ['react','babel-polyfill']
    },
    output: {
        path: path.join(__dirname, 'build'),
        filename: '[name].js',
        chunkFilename: '[id].build.js?[chunkhash]',
        publicPath: '/build',
    },
    module: {
        rules: [
            {
                test: /\.(less|css)$/,
                use: ['style-loader', 'css-loader','less-loader'],
            },
            {         
              test:/\.(js|jsx)?$/,
              loader:'babel-loader',
              exclude:/node_modules/,
              options:{presets:['env','react','stage-0','stage-1']}
            },
            {
                test: /\.(png|jpg|gif)?$/,
                use: ['url-loader?limit=8192&name=[name]_[sha512:hash:base64:7].[ext]'],
            },
            {
                test: /\.(eot|woff|ttf|svg)$/,
                use: ['file-loader?limit=81920&name=[name]_[sha512:hash:base64:7].[ext]']
            }
        ]
    },
    resolve: {
        extensions: ['.js', '.jsx', '.styl', '.html', '.json'],
        modules: ['node_modules']
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin(),
        new ExtractTextPlugin('[name].[contenthash:20].css'),
        new webpack.optimize.UglifyJsPlugin({
            compress: {warnings: false}
        }),
        new webpack.optimize.CommonsChunkPlugin({name:'common', filename:'common.js'}),
        new HtmlWebpackPlugin({
              title: "SNT",
              template: path.join(path.resolve(__dirname),'/build/myApp.html'),  
              inject:'body',
              hash:true,   
              minify:{   
                removeComments:false,   
                collapseWhitespace:false    
              }
        })
    ],
    devServer: {
        historyApiFallback: true,
        hot: true,
        inline: true,
        progress: true,
    }
};

**Comment by rfranco** [comment]
+1

**Comment by evilebottnawi** [comment]
@MEDIOCAL @rfranco which version you use and can you describe repo with minimum reproducible? It is hard to repeat problem  from source code from github post, thank you!

**Comment by dothanhlam** [comment]
I have the same problem - mine is webpack 1.14.0
Uglify plugin throws the error from redux-saga library
import middleware from './internal/middleware' <-- throwing the error here

**Comment by RoboBurned** [comment]
@MEDIOCAL as a workaround until this is fixed you can try to remove the line
`exclude:/node_modules/,`
from` babel-loader` configuration.
This should allow babel to transpile all code to es5 which Uglify plugin can understand.

**Comment by Candy374** [comment]
+ 1
I'm using webpack 3.6.0


@RoboBurned  if remove `exclude:/node_modules/,`,  then it will have other error, like file too big..

**Comment by Ballpin** [comment]
I added the following code..
```
// webpack.config.js
 plugins: [
    new UglifyJSPlugin({
      test: /\.js($&#124;\?)/i,
      exclude: /(node_modules|bower_components)/
    }),
....
```

I don't really see any reason for uglify to run through the node_modules folder.

**Comment by frixid** [comment]
+1

**Comment by evilebottnawi** [comment]
Somebody can create minimum reproducible test repo?

**Comment by frixid** [comment]
Downgrading to webpack-dev-server 2.7.1 works

**Comment by Ballpin** [comment]
For my part i realized that i dont want uglifyjs to minify my js while im developing. So i simply removed it from webpack.config.js.

And moved it to to my webpack.config.prod.js.
`plugins: [new UglifyJSPlugin(), new ExtractTextPlugin('style.css')]`

So now when i run build command it works as it is suppose to 😄

**Comment by RoboBurned** [comment]
Tried to create minimal reproducer. [webpack-uglifyjs-error.zip](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/files/1362567/webpack-uglifyjs-error.zip)

**Comment by evilebottnawi** [comment]
@RoboBurned remove `'webpack-dev-server/client?http://localhost:8080'` and `'webpack/hot/only-dev-server'` when you build for production env

**Comment by evilebottnawi** [comment]
@RoboBurned because https://github.com/webpack/webpack-dev-server/blob/master/client/index.js use es6, but uglify@0.4.6 don't support es6

**Comment by michael-ciniawsky** [comment]
Please ensure to transpile ypur code down to ES5 when using `>= v0.4.6` or try the current `beta` 

`npm i -D uglifyjs-webpack-plugin`

**webpack.config.js**
```js
const UglifyJSPlugin = require('uglifyjs-webpack-plugin')

const config = {
  ...
  plugins: [
    new UglifyJSPlugin({ uglifyOptions: {...options } })
  ]
}
```

which supports ES2015+ (`uglify-es`)

**Comment by surfjedi** [comment]
+1

**Comment by kevinmims** [comment]
I think the problem is using `new webpack.optimize.UglifyJsPlugin...` with webpack v3+.  You need to import the uglifyjs-webpack-plugin and change your plugin to `new UglifyJSPlugin...` as michael-ciniawsky mentioned above.

Here is a reference https://webpack.js.org/plugins/uglifyjs-webpack-plugin/

**Comment by TotallyInformation** [comment]
Even with `uglifyjs-webpack-plugin@1.0.0-beta.3`, I'm still getting lots of errors:

- It couldn't cope with a default value on a function parameter
- It failed on a let statement
- It failed on a '`' string

Thankfully, I didn't have much ES6 code so I've stripped it for now. A bit crazy that we are still forced to use nothing beyond ES5.

**Comment by evilebottnawi** [comment]
@TotallyInformation please provide minimum reproducible test repo, thanks!

**Comment by acierto** [comment]
Faced the same issue today with the latest version of webpack 3.7.1.

Upgrade to 1.0.0-beta.3 and using below snapshot helped to resolve the issue

```
const UglifyJSPlugin = require('uglifyjs-webpack-plugin')

const config = {
  ...
  plugins: [
    new UglifyJSPlugin({ uglifyOptions: { ...options } })
  ]
}
```

**Comment by firebird631** [comment]
Same issue with webpack 3.8.1, and using the webpack.optimize.UglifyJsPlugin or 'uglifyjs-webpack-plugin' 1.0.0 and uglify-js is correctly pointing to uglify-es. So I installed https://www.npmjs.com/package/uglifyjs-webpack-plugin3 and it works fine.

**Comment by codler** [comment]
Will this be updated in webpack?

**Comment by lffg** [comment]
Same.

**Comment by crowmagnumb** [comment]
Looks like they are saying that uglify 1.0.0 will be included in webpack 4. Until then as @firebird631 indicated, installing that version manually does the trick.

npm -i -D uglifyjs-webpack-plugin

Then in webpack.config...

```
const UglifyJsPlugin = require("uglifyjs-webpack-plugin");
            // new webpack.optimize.UglifyJsPlugin({ // Can switch back to this with webpack 4
            new UglifyJsPlugin({
                sourceMap: true
            })

**Comment by chenyiqi** [comment]
I met the same problem
![image](https://user-images.githubusercontent.com/3357208/39698053-c39f60ee-5225-11e8-9fcf-9b624419e8bb.png)

**Comment by evilebottnawi** [comment]
Please don't write your problem in old issue. Please create new issue with minimum reproducible test repo. Thanks
