### ISSUE TITLE
mangle and minify not working 

### ISSUE THREAD

**Issue by RahavLussato** [webpack-contrib/uglifyjs-webpack-plugin#133]
i don't understand what i'm doing wrong but it seems like mangle and minify is not working at all with the latest beta.

[here](https://github.com/RahavLussato/webpack-config-env-issue) you can find a repository that easily reproduce it.
just run `npm install` and then `npm run build`, after the build will finish check the `bundle.js` file under dist/bundledCode and you'll see that the code is not minified and not mangled.

### original code:
```
const notMangledName = 3;
const notMangledName2 = 3;


const notMangleName3 = 10;



const notMangleName4 = 10;
const notMangleName5 = 10;
const notMangleName6 = 10;
const notMangleName7 = 10;
```

### after uglifiy:
```
webpackJsonp([0],[
/* 0 */
/***/ (function(module, exports, __webpack_require__) {

module.exports = __webpack_require__(1);


/***/ }),
/* 1 */
/***/ (function(module, exports) {

var notMangledName = 3;
var notMangledName2 = 3;


var notMangleName3 = 10;



var notMangleName4 = 10;
var notMangleName5 = 10;
var notMangleName6 = 10;
var notMangleName7 = 10;

/***/ })
],[0]);
//# sourceMappingURL=bundle.js.map?c0d9ad7c70ebe088ac45
```

expected behavior should be compressed to one line, variables names should be mangled ...

**Comment by kzc** [comment]
The uglify plugin is not being run at all. What you're looking at is webpack output + source map. Try writing the simplest possible minimal `webpack.config.js` with no uglify options and without the `webpack-config` module.

**Comment by RahavLussato** [comment]
@kzc it is running because if i'll switch it to `` [here](https://github.com/RahavLussato/webpack-config-env-issue/blob/master/staging.config.js#L13) you'll see completely different output.

**Comment by RahavLussato** [comment]
to make sure i added `console.log('test')` on `function UglifyJsPlugin()` and it is running.

**Comment by kzc** [comment]
`webpack-config` may be making incorrect assumptions. The following works fine:

```
$ cat main.js 
var some_constant = 123;
class Foo {
    run() {
        console.log("hello " + some_constant);
    }
}
new Foo().run();
```
```
$ cat webpack.config.js 
var Uglify = require("uglifyjs-webpack-plugin");
module.exports = {
    entry: {
        main: "./main.js",
    },
    output: {
        filename: "out.min.js",
    },
    devtool: 'source-map',
    plugins: [
        new Uglify({
            sourceMap: true,
            uglifyOptions: {
                output: {
                    beautify: true,
                },
            },
        }),
    ],
};
```
```
$ webpack --config webpack.config.js 
Hash: 3d12e256217203e17a88
Version: webpack 3.6.0
Time: 155ms
         Asset       Size  Chunks             Chunk Names
    out.min.js  955 bytes       0  [emitted]  main
out.min.js.map     3.4 kB       0  [emitted]  main
   [0] ./main.js 121 bytes {0} [built]
```
```
$ cat out.min.js && echo
!function(n) {
    function r(t) {
        if (e[t]) return e[t].exports;
        var o = e[t] = {
            i: t,
            l: !1,
            exports: {}
        };
        return n[t].call(o.exports, o, o.exports, r), o.l = !0, o.exports;
    }
    var e = {};
    r.m = n, r.c = e, r.d = function(n, e, t) {
        r.o(n, e) || Object.defineProperty(n, e, {
            configurable: !1,
            enumerable: !0,
            get: t
        });
    }, r.n = function(n) {
        var e = n && n.__esModule ? function() {
            return n.default;
        } : function() {
            return n;
        };
        return r.d(e, "a", e), e;
    }, r.o = function(n, r) {
        return Object.prototype.hasOwnProperty.call(n, r);
    }, r.p = "", r(r.s = 0);
}([ function(n, r) {
    var e = 123;
    class t {
        run() {
            console.log("hello " + e);
        }
    }
    new t().run();
} ]);
//# sourceMappingURL=out.min.js.map
```

**Comment by evilebottnawi** [comment]
@RahavLussato which version do you use?

**Comment by RahavLussato** [comment]
@evilebottnawi you can see it on the package config:
```

  "name": "webpack-config-bug",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "rm -rf ./dist/ && NODE_ENV=staging webpack --display-error-details --config webpack.config.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "uglify-es": "^3.0.27",
    "uglify-js": "3",
    "uglifyjs-webpack-plugin": "1.0.0-beta.2",
    "webpack": "^3.5.1",
    "webpack-config": "^7.0.0"
  }
}
```

**Comment by evilebottnawi** [comment]
@RahavLussato can you try to use `0.4.6` version?

**Comment by evilebottnawi** [comment]
@RahavLussato Also you don't need `uglify-es` and `uglify-js` packages

**Comment by RahavLussato** [comment]
@evilebottnawi i need to use the beta version and also `uglify-es` because i want to do it on es6 code, the repo that i published is just to reproduce the issue but on my real env i have a code thats should use the beta version, if not i'm getting this error `UglifyJs Unexpected token: operator (>)`.
i managed to do a workaround to that and revert it back to use `webpack.optimize.UglifyJsPlugin` by forking the problematic 3rd parties that used es6 and managed them to work with es5, so now its working for me. (e.g. for problamatic 3rd party is [parseQuery](https://github.com/webpack/loader-utils/blob/master/lib/parseQuery.js#L24))

**Comment by RahavLussato** [comment]
and thanks @kzc its looks like you are right
