### ISSUE TITLE
Custom sourceMappingURL question

### ISSUE THREAD

**Issue by caguthrie** [webpack-contrib/uglifyjs-webpack-plugin#136]
In UglifyJS, you are able to use the follow option to get a custom ```sourceMappingURL``` in the bottom of your uglified js:

```javascript
    sourceMap: {
        filename: "out.js",
        url: "out.js.map"
    }
```

Therefore, I thought it was natural to do this:
```javascript
        new webpack.optimize.UglifyJsPlugin({
          sourceMap: true,
          uglifyOptions: {
            sourceMap: {
              filename: "out.js",
              url: "../custom/url"
            }
          }
        })
```

However, doing that ```sourceMappingURL``` doesn't show up at all in the output.  What is the correct way to get a custom ```sourceMappingURL``` in your uglified js file?

**Comment by kzc** [comment]
> new webpack.optimize.UglifyJsPlugin({

That line will pull in [`uglifyjs-webpack-plugin@0.4.6`](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/v0.4.6/README.md) which is incompatible with `v1.0.0-beta` `uglifyOptions`:

https://github.com/webpack-contrib/uglifyjs-webpack-plugin/tree/v1.0.0-beta.3#options

For an example of using the latest beta version of this plugin see:

https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/133#issuecomment-332769465

**Comment by caguthrie** [comment]
Thanks

**Comment by kzc** [comment]
@sokra  Any idea when `uglifyjs-webpack-plugin@1.x` will be released?
