### ISSUE TITLE
[v1.0.0-beta.3] Broken `parallel` option

### ISSUE THREAD

**Issue by sapegin** [webpack-contrib/uglifyjs-webpack-plugin#139]
`{ parallel: true }` work fine but `{ parallel: { cache: true } }` throws an error:

```
Error: Validation Error

UglifyJs Plugin Invalid Options

options.parallel should be boolean
options.parallel should be integer
options.parallel should match exactly one schema in oneOf
]
  err: 
   [ { keyword: 'type',
       dataPath: '.parallel',
       schemaPath: '#/properties/parallel/oneOf/0/type',
       params: [Object],
       message: 'should be boolean' },
     { keyword: 'type',
       dataPath: '.parallel',
       schemaPath: '#/properties/parallel/oneOf/1/type',
       params: [Object],
       message: 'should be integer' },
     { keyword: 'oneOf',
       dataPath: '.parallel',
       schemaPath: '#/properties/parallel/oneOf',
       params: {},
       message: 'should match exactly one schema in oneOf' } ] }
```

I also don’t see any change log entries or even commit for this version.

**Comment by evilebottnawi** [comment]
@sapegin `parallel` and `cache` are now difference option, maybe something wrong with schema, in near future i try to investigate, thank you

**Comment by sapegin** [comment]
According to the readme, it’s not. It shows both examples as correct: { parallel: { cache: true } } and { parallel: true }.

**Comment by sapegin** [comment]
I see, it’s in some random branch. How should I guess that?

**Comment by evilebottnawi** [comment]
latest beta and branch https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/108

**Comment by sapegin** [comment]
Yes, that’s what I’m saying.

**Comment by michael-ciniawsky** [comment]
The `options` interface changed between `beta.2` => `beta.3`  

`{ parallel: { cache: 'path/to/cache', workers: 2 } }` 
=> `{ cache: 'path/to/cache' , parallel: workers }` 

to decouple the `cache` from `parallelization`

Agreed it should be better visible, but that's up to the release team. Feel free to reopen if still regressions :)
