### ISSUE TITLE
[Feature] `--mangle-props` debug

### ISSUE THREAD

**Issue by khmyznikov** [webpack-contrib/uglifyjs-webpack-plugin#143]
I have trying to setup mangle in large project, something have broken after mangle and i can't find what exactly without debug info.

**Comment by michael-ciniawsky** [comment]
Does `new UglifyJS({ uglifyOptions: { warnings: true } })` yield anything here? Otherwise if `uglify` itself doesn't throw or produces any warnings I'm afraid it's out of scope for this plugin to provide such functionality. Open an issue at `uglify` instead then

**Comment by michael-ciniawsky** [comment]
Does 

```js
new UglifyJSPlugin({
 uglifyOptions: {
   mangle: {
     properties: { debug: true }
   } 
 } 
})
```

work ?

**Comment by khmyznikov** [comment]
@michael-ciniawsky Yes, looks like working, but the app doesn't work at all with this option - "webpackJsonp is not defined" error and stuck. But with mange: true it works, but partially, another errors.

**Comment by khmyznikov** [comment]
I'm Trying to use "reserved" for webpackJsonp, but it doesn't help. Falling on the next step where loading exports.

**Comment by evilebottnawi** [comment]
@khmyznikov seems you don't have manifest file (initial chunk) where define `webpackJsonp` function, maybe forgot something include

**Comment by michael-ciniawsky** [comment]
**webpack.config.js**
```js
const config = {
  entry: {
     app: 'path/to/app.js',
     ...entries,
     vendor: [ 'react', 'react-dom', ...packages ]
  },
  plugins: [
     webpack.optimize.CommonChunksPlugin({
         // Set an undefined name for the webpack runtime (wepackJsonP)
         // e.g 'runtime' to split it from your app.bundle.js
         // ⚠️  Ensure the runtime name isn't as entry in config.entry 
         name: [ 'app', ...entries,  'vendor', 'runtime' ],
         minChunks: Infinity
     }),
     new UglifyJSPlugin({ ...options })
  ]
}
```

**Comment by khmyznikov** [comment]
@evilebottnawi @michael-ciniawsky _webpackJsonp_ error solved by manifest, but next step - no. 

`modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);`
> Cannot read property 'call' of undefined

_moduleId_ have for example value _+8jR_, but into _modules_ it is _$+8jR$_
