### ISSUE TITLE
Is webpack.optimize.UglifyJsPlugin() UglifyJsPlugin() ?

### ISSUE THREAD

**Issue by kmvan** [webpack-contrib/uglifyjs-webpack-plugin#144]
I am try in my config:
```javascript
// webpack: v3.8.1
// uglifyjs-webpack-plugin: v1.0.0 b3

// Below doesn't work, plugin doesn't compress any code
const UglifyJsPlugin = require('uglifyjs-webpack-plugin')
new UglifyJsPlugin({
    uglifyOptions: {
        compress: {
            properties: true,
```
```javascript
// But below works:
new webpack.optimize.UglifyJsPlugin({
    compress: {
        properties: true,
```

I can't believe my eyes, what's wrong with me?

**Comment by michael-ciniawsky** [comment]
Does only the `compress` option not work atm ?

**Comment by michael-ciniawsky** [comment]
`webpack.optimize.UglifyJsPlugin`  === `uglifyjs-webpack-plugin@0.4.6`  (UglifyJS v2.0.0 (ES5))
`uglifyjs-webpack-plugin@beta` (UglifyJS v3.0.0 (ES2015+))

**Comment by kzc** [comment]
For `webpack@3` the command `webpack -p` uses `uglifyjs-webpack-plugin@0.4.6` unconditionally:

https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/112#issuecomment-329069520

This particular problem trips up everyone will only be solved once `uglifyjs-webpack-plugin@1.x` is released and a future `webpack` release uses it. But then `uglifyjs-webpack-plugin ` users will have the opposite problem - `0.4.6` options will not work with `1.x`.

> uglifyjs-webpack-plugin@beta (UglifyJS v3.0.0 (ES2015+))

`uglify-js@2` and `uglify-js@3` are ES5 only.

`uglifyjs-webpack-plugin@beta` uses `uglify-es` which is ES6+.
