### ISSUE TITLE
[v0.4.6]  `options.compress` isn't assign (`webpack.optimize.UglifyJSPlugin`)

### ISSUE THREAD

**Issue by KievDevel** [webpack-contrib/uglifyjs-webpack-plugin#146]
Hi, I'm using webpack 3.8.1, and after running webpack -p I have an issue when compress options doesn't work. (uglifyjs-webpack-plugin 0.4.6)
I see that compressor called multiple times and the last one he called without options (options === undefined). 
If in dist/index.js:100 I fix check with if (options.compress !== false && options.compress !== undefined) { - the last call will be with parameters so I get the expected result.

But I don't know why it called multiple times and if in webpack config will be new UglifyJSPlugin() will be empty it won't be filled with defaults.

Looks like it is a known issue, so please ask how can I help. If I can help to close this issue it would be great.

**Comment by michael-ciniawsky** [comment]
If ypu have something in mind please open a PR for discussion, otherwise would upgrading to v1.0.0 be sufficient for you ?

`npm i -D uglifyjs-webpack-plugin`

**webpack.config.js**
```js
const UglifyJSPlugin = require('uglifyjs-webpack-plugin')

module.exports = {
  plugins: [
     new UglifyJSPlugin({ ...pluginOptions, ...uglifyOptions })
  ]
}
```

> ⚠️   Note that this isn't equal to webpack.optimize.UglifyJSPlugin() atm and the `options` interface changed between v0.4.6...1.0.0, see the README`

**Comment by michael-ciniawsky** [comment]
Can you post your `webapck.config.js` please ?

**Comment by KievDevel** [comment]
I'm using now:

`module.exports = [
    plugins: [
        new UglifyJSPlugin({
                compress: { unused:false }
            })
    ]
]`

That conf now should be used for default conf (if u'll use my PR proposal and that's isn't good)
`module.exports = [
    plugins: [
        new UglifyJSPlugin({
                compress: { }
            })
    ]
]`

Full [webpack.config.js](https://pastebin.com/cpPUkWaw) here
