### ISSUE TITLE
 Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script 'node lib/post_install.js'.

### ISSUE THREAD

**Issue by Callie-C-Wang** [webpack-contrib/uglifyjs-webpack-plugin#156]
Hi,
 I am trying to install @angular/cli in my machine.
However, error shows like below.
My node version is v6.11.5
my npm version is v3.10.10

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! file C:\windows\system32\cmd.exe;
npm ERR! path C:\windows\system32\cmd.exe;
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\windows\system32\cmd.exe;

npm ERR! uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
npm ERR! spawn C:\windows\system32\cmd.exe; ENOENT
npm ERR!
npm ERR! Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script 'node lib/post_install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uglifyjs-webpack-plugin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/post_install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uglifyjs-webpack-plugin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uglifyjs-webpack-plugin
npm ERR! There is likely additional logging output above.

**Comment by evilebottnawi** [comment]
@Callie-C-Wang can you provide minimum reproducible test repo?

**Comment by Callie-C-Wang** [comment]
Hi @evilebottnawi 
This issue happened when I try to install angular command lines using the following command:
npm install -g @angular/cli
I ran this command in administration permission.
I also confirmed there's no proxy in my current machine.
And I also tried to uninstall, re-start the machine and install updated version of node and npm
With the node version = v8.9.0 and the npm version = 5.5.1, the same issue still occured

Here are the info in the debug logs (when I using administration permission to install angular command lines)
4488 silly lifecycle uglifyjs-webpack-plugin@0.4.6~postinstall: Args: [ '/d /s /c', 'node lib/post_install.js' ]
24489 info lifecycle uglifyjs-webpack-plugin@0.4.6~postinstall: Failed to exec postinstall script
24490 silly lifecycle uglifyjs-webpack-plugin@0.4.6~postinstall: Returned: code: -4058  signal: null
24491 info lifecycle uglifyjs-webpack-plugin@0.4.6~postinstall: Failed to exec postinstall script
24492 verbose unlock done using C:\Users\cwang\AppData\Roaming\npm-cache\_locks\staging-6d5753cb61739e63.lock for C:\Users\cwang\AppData\Roaming\npm\node_modules\.staging
24493 warn Error: EPERM: operation not permitted, scandir 'C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules'
24493 warn  { Error: EPERM: operation not permitted, scandir 'C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules'
24493 warn   stack: 'Error: EPERM: operation not permitted, scandir \'C:\\Users\\cwang\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\'',
24493 warn   errno: -4048,
24493 warn   code: 'EPERM',
24493 warn   syscall: 'scandir',
24493 warn   path: 'C:\\Users\\cwang\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules' }
24494 verbose Please try running this command again as root/Administrator.
24495 verbose stack Error: uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
24495 verbose stack spawn C:\windows\system32\cmd.exe; ENOENT
24495 verbose stack     at _errnoException (util.js:1024:11)
24495 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
24495 verbose stack     at onErrorNT (internal/child_process.js:372:16)
24495 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
24495 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
24496 verbose pkgid uglifyjs-webpack-plugin@0.4.6
24497 verbose cwd C:\windows\system32
24498 verbose Windows_NT 6.1.7601
24499 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
24500 verbose node v8.9.0
24501 verbose npm  v5.5.1

Let me know if you need more information and thank you for your help!

**Comment by evilebottnawi** [comment]
@Callie-C-Wang seems you don't have enough permissions, because you got `EPERM` error code

**Comment by evilebottnawi** [comment]
@Callie-C-Wang maybe https://github.com/npm/npm/issues/17747 ?

**Comment by Callie-C-Wang** [comment]
Thank you, @evilebottnawi 
I will close this ticket and leave message to issue npm/npm#17747
