### ISSUE TITLE
Improve schema errors feedback

### ISSUE THREAD

**Issue by pladaria** [webpack-contrib/uglifyjs-webpack-plugin#157]
After updating to latest version, my webpack build broke and it was pretty hard to find the cause. 

This is the only feedback I got:
```
/source/web/node_modules/schema-utils/dist/validateOptions.js:40
    throw new _ValidationError2.default(ajv.errors, name);
    ^
```

After disabling all plugins and rules, and enabling them again one by one, I found that the problem was that uglify-webpack-plugin now requires to wrap `output` with `uglifyOptions`.

It would be nice to have some better feedback for those errors.

**Comment by michael-ciniawsky** [comment]
Will be fixed by [schema-utils (#15)](https://github.com/webpack-contrib/schema-utils/pull/15) soon
