### ISSUE TITLE
Minification with sourcemaps enabled is slow

### ISSUE THREAD

**Issue by alan-agius4** [webpack-contrib/uglifyjs-webpack-plugin#161]
I have a huge application, with several thousands of files and lines of code.

When I enable source maps using the below, the compilation takes around 40 times longer, and In my case that means approximately 40 minutes.

```js
new UglifyJSPlugin({
     parallel: true,
     sourceMap: true,
});
```

I did some digging and it seems that the methods that take a lot of time are `sourceAndMap();
` and `map()` coming from [webpack-sources](https://github.com/webpack/webpack-sources)

https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/src/index.js#L124
and 
https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/src/index.js#L128

A work around to make the minification with sourcemaps fast would be to call these 2 methods with `{ columns: false }`.

Downside is that the devtool option must not be `cheap-module-source-map` but AFAIK this plugin only supports sourcemaps that are for `production`

Question: would it be possible to include an addition options in the Plugin to disable columnMapping? I'd happily do a PR if you'd like.

**Comment by michael-ciniawsky** [comment]
In general this is to be expected to some point, source map generation is expensive. Are the maps still correct  without column mapping ? Why do you need the source maps for production ? The use case for `options.sourceMap` is more suited in case you want to bundle a library and provide with source maps to users. Otherwise it is in general a good idea to disable minification during development

**Comment by alan-agius4** [comment]
I am not interested in column mapping but line mapping is enough for me
which seems to be working ok

I want sournaps for production to map error logging using sentry logger
with the actual source.

**Comment by michael-ciniawsky** [comment]
Closing in favor of [webpack-sources (#29)](https://github.com/webpack/webpack-sources/issues/29) 😛 , we shouldn't try to alter this within `uglifyjs-webpack-plugin` until absolutely necessary imho
