### ISSUE TITLE
[^1.0.1] How to use a custom sourceMappingURL 

### ISSUE THREAD

**Issue by bretthadley** [webpack-contrib/uglifyjs-webpack-plugin#165]
Versions -
`"uglifyjs-webpack-plugin": "^1.0.1"`
`"webpack": "^3.8.1"`

Usage
```
new UglifyJsPlugin({
    sourceMap: true,
    extractComments: true,
    parallel: true,
    uglifyOptions: {
        sourceMap: {
            url: "/themes/compare-modular/app.js.map"
        }
    }
 })
```

Output
`//# sourceMappingURL=app.js.map`

Expected
`//# sourceMappingURL=/themes/compare-modular/app.js.map`

I'm sure I'm doing something wrong can someone point it out please?

Many thanks!

**Comment by evilebottnawi** [comment]
@bretthadley can you describe use case?

**Comment by bretthadley** [comment]
@evilebottnawi Specifically I need it for the errorception service where they look for the sourceMappingURL  to give better error stacktraces. My app.js is served from '/themes/compare-modular/app.js' but the sourceMappingURL says '/app.js.map' which isnt right. 

p.s. my publicPath in webpack is also '/themes/compare-modular/'

This is something that is supported by UglifyJS 2.x and 3.x (according to their docs)

**Comment by michael-ciniawsky** [comment]
[SourceMapDevToolPlugin](https://webpack.js.org/plugins/source-map-dev-tool-plugin/#src/components/Sidebar/Sidebar.jsx) ?

**Comment by bretthadley** [comment]
@michael-ciniawsky Sure I could use that but because this is a feature supported by uglifyjs I just assumed I was configuring it wrong but if it doesn't work correctly then thats fine.

Thanks.

**Comment by evilebottnawi** [comment]
@bretthadley can we close issue?

**Comment by mike3run** [comment]
As seen in the uglify docs:

https://github.com/mishoo/UglifyJS2/tree/harmony#source-map-options

The options are never just `url` but rather `url` and one of the following:

- filename
- root
- content

**Comment by mikeLspohn** [comment]
The documentation in the README.md links the options to the uglify options, which contain these `sourceMap` object config values. Should that be removed, or does this work in this plugin now?
