### ISSUE TITLE
cache seems does not work when I fetch code from github and compile it

### ISSUE THREAD

**Issue by Ben07** [webpack-contrib/uglifyjs-webpack-plugin#170]
webpack:3.8.1
uglifyjs-webpack-plugin:1.0.1

Part of the configuration is as follows
```
new UglifyJSPlugin({
  uglifyOptions: {
    compress: {
      warnings: false,
      drop_console: true,
    },
    ecma: 5,
  },
  parallel: true,
  cache: path.resolve(__dirname, '../uglify_cache')
}),
```
The first time I compiled the code, `45668ms additional asset processing`,it compile slowly because there is no cache files.when I  compile again,`7ms additional chunk assets processing`.it compiled fastly because cache.That's good!
The problem is when I fetch code from gitlab, there is little change in the code, but it become slowly when compiled.
git has ignore uglify_cache directory,so cache is existed.
Thanks in advcance! my english is poor

**Comment by michael-ciniawsky** [comment]
> The problem is when I fetch code from gitlab, there is little change in the code, but it become slowly when compiled.

If these changes the`assets` processed by uglify the cache will be busted

**Comment by Ben07** [comment]
@michael-ciniawsky Thank you for your reply. In my understanding, if there is little change in code, cache will be busted little.But now the situation is like no cache, I am very confused.

**Comment by michael-ciniawsky** [comment]
All `.js` output files (`assets`) you get in your output/build directory are processed  by `uglifyjs-webpack-plugin` individually, so a small change to one of the modules included in one of these assets will likely bust the cache for at least this asset then :)

**Comment by Ben07** [comment]
Probably for this reason. I will check it in next compile time
