### ISSUE TITLE
Syntax error when minifying array destructuring

### ISSUE THREAD

**Issue by eldh** [webpack-contrib/uglifyjs-webpack-plugin#172]
In this function 
```js
const getInitials = (fullName, size) => {
    const names = fullName
      .split(' ')
    if (names.length === 1) {
      return [...names[0]][0]
    }
    const initials = names.map(name => [...name][0])
    return size === 'small' ? initials[0] : initials[0] + initials[initials.length - 1]
  }
  ```
... the array destructuring compiles to `return...r[0];const e=r.map(t=>...t);`, which is afaict a syntax error. I tried disabling a bunch of compress options but always got the same result.

I guess this doesn't happen often because in most setups array destructuring is transpiled by babel before it hits uglify. 

Minimal repro in this repo: https://github.com/eldh/webpack-bug

**Comment by evilebottnawi** [comment]
@eldh seems it is not related to `uglifyjs-webpack-plugin`, problems in `babel` or `uglify-es`, need investigate

**Comment by eldh** [comment]
Ah yes, sorry. I'll close this and open an issue in uglify-es.

**Comment by eldh** [comment]
https://github.com/mishoo/UglifyJS2/issues/2498 if anyone comes this way
