### ISSUE TITLE
Compilation error when compress conditionals is true

### ISSUE THREAD

**Issue by danbopes** [webpack-contrib/uglifyjs-webpack-plugin#179]
See repo: https://github.com/danbopes/webpack-uglify-react-form-issue

Trying to diagnose an error. When compress conditionals is false, webpack compiles and runs correctly. When compress conditionals is true or mangle is false, webpack compiles but shows the following error:
![](https://camo.githubusercontent.com/c433070af2bf9613b37f549777094ecc30f0cee2/68747470733a2f2f692e696d6775722e636f6d2f5450723147444c2e706e67)

The cause of the error appears to be this line in the minified dist of react-form:

        e.exports = require("babel-runtime/helpers/extends")

Additional information located in the react-form issue [here](https://github.com/react-tools/react-form/issues/185), but I believe this issue is internal to uglifyjs, and nothing in react-form.

**Comment by kzc** [comment]
> Reproduce via repository here: https://github.com/danbopes/webpack-uglify-react-form-issue
>
> Compile with:
> $ yarn
> $ webpack -p

`uglifyjs-webpack-plugin@1.x` is not compatible with the `-p` flag of `webpack@3.x`.

The `-p` flag of `webpack@3.x` will use `uglifyjs-webpack-plugin@0.4.6` unconditionally.

For `webpack@3.10.0` on UNIX use this instead:
```
webpack --config webpack.config.js --define process.env.NODE_ENV='"production"'
```
On Windows the quoting may be different. I don't know.

**Comment by michael-ciniawsky** [comment]
@danbopes See @kzc comment @kzc Thx :) Feel free to reopen if still regressions

**Comment by kzc** [comment]
I confirmed the repro worked with the command above. It would have been helpful if the code actually displayed something. :-)

```patch
diff --git a/src/index.jsx b/src/index.jsx
index 5fe1742..ebcdea6 100644
--- a/src/index.jsx
+++ b/src/index.jsx
@@ -4,9 +4,10 @@ import { Form, Text } from 'react-form';
 
 const app = () => (
     <div>
+      Hello dude.
     </div>
 );
 
 const root = document.getElementById('root');
 
```

**Comment by danbopes** [comment]
I thought it had <div>It works!</div>. Anyways, thanks for the assistance.
Would be helpful if the documentation reflected the '-p' flag.
