### ISSUE TITLE
Removing comments does not work when setting devtool to eval

### ISSUE THREAD

**Issue by re-fort** [webpack-contrib/uglifyjs-webpack-plugin#180]
Hi, thanks for the great lib!

Currently, I'm trying code splitting.
Since babel removes webpack magic comments like `webpackChunkName`, I want to use this library to remove comments instead of it.
But when I set devtool to eval, it seems removing comments does not work.
Is it expected behavior?

my config:
```js
new uglifyJsWebpackPlugin({
      uglifyOptions: {
        output: {
          comments: false
        },
        compress: {
          warnings: false,
        },
      },
    }),
```

|devtool|remove comments?|
|------------- |-------------|
|eval|NO|
|cheap-eval-source-map|NO|
|source-map|YES|

- lib: 1.1.2
- node: 8.5.0
- OS: mac OS Sierra
- webpack config: [here](https://github.com/re-fort/vue-webpack-boilerplate/blob/code-spliting/webpack.config.js)

**Comment by michael-ciniawsky** [comment]
> ⚠️ cheap-source-map options don't work with this plugin

**Comment by re-fort** [comment]
OK, thanks

**Comment by lizongze** [comment]
> [README#sourceMap](https://github.com/webpack-contrib/uglifyjs-webpack-plugin#sourcemap)
> 
> > ⚠️ cheap-source-map options don't work with this plugin

eval is also cheap-source-map
