### ISSUE TITLE
Uglifyjs ascii_only option

### ISSUE THREAD

**Issue by cbranca** [webpack-contrib/uglifyjs-webpack-plugin#184]
Hello, I'm using webpack 3.5.4 with AngularJS 1.6.5.
I need to minify the application using the "ascii_only: true" option, but this option doesn't work.
I need the ascii_only option because when I use an angularjs currency filter, after the minification it prints "Â$ 345,000" instead of "$ 345,000".

this is the code that I use to minify the application:
```
    new webpack.optimize.UglifyJsPlugin({
      compress: { warnings: false, drop_console: true },
      comments: false,
      mangle: true,
      sourceMap: false,
      uglifyOptions: {
        output: {
          ascii_only: true
        }
      }
    }),
```

Is this option supported or it is a bug?

**Comment by evilebottnawi** [comment]
@cbranca `webpack.optimize.UglifyJsPlugin` contain `0.4.6` version (see https://github.com/webpack-contrib/uglifyjs-webpack-plugin/tree/v0.4.6), but you use arguments for latest version.
Solution:
1. Rewrite arguments for https://github.com/webpack-contrib/uglifyjs-webpack-plugin/tree/v0.4.6#usage
2. Add in `package.json` latest `uglifyjs-webpack-plugin` version and use new format arguments.

Thank for issue!

**Comment by cbranca** [comment]
Thank you!

**Comment by blurymind** [comment]
lol, webpack is still using "uglify-js": "~2.7.3"


Would a PR be welcome?
