### ISSUE TITLE
Minimal compress options to suppress React production build warning

### ISSUE THREAD

**Issue by clairepham91** [webpack-contrib/uglifyjs-webpack-plugin#186]
Hi, I don't wish to use the default compress options to [minimize build time](https://github.com/mishoo/UglifyJS2#uglify-fast-minify-mode). However I encounter this error by React.
`Uncaught Error: React is running in production mode, but dead code elimination has not been applied. Read how to correctly configure React for production: https://fb.me/react-perf-use-the-production-build`

I tried using the following compress options but the error persists
`compress: {
                        booleans: false,
                        cascade: false,
                        'collapse_vars': false,
                        comparisons: false,
                        conditionals: false,
                        'dead_code': true,
                        evaluate: false,
                        'hoist_funs': false,
                        'hoist_props': false,
                        'if_return': false,
                        inline: false,
                        'join_vars': false,
                        'keep_fargs': false,
                        'keep_infinity': false,
                        'loops': false,
                        'negate_iife': false,
                        properties: false,
                        'reduce_funcs': false,
                        'reduce_vars': false,
                        sequences: false,
                        'side_effects': false,
                        switches: false,
                        typeofs: false,
                        unused: true
                    }`

Do you have any ideas to fix this? Thanks

I am using version 1.1.0.

**Comment by evilebottnawi** [comment]
@clairepham91 thank for issue, can you create minimum reproducible test repo?

**Comment by kzc** [comment]
This is a question for the react project.

It's not possible to minimize build time if you're using the production version of react as it apparently requires uglify `compress` to be enabled:

> Uncaught Error: React is running in production mode, but dead code elimination has not been applied. Read how to correctly configure React for production: https://fb.me/react-perf-use-the-production-build

See: https://reactjs.org/docs/optimizing-performance.html#webpack

You can minimize build time with a development version of react.

Look at the Webpack documentation to see how multiple build configurations are supported.
