### ISSUE TITLE
uglifyjs-webpack-plugin can't compress code

### ISSUE THREAD

**Issue by huboshu0819** [webpack-contrib/uglifyjs-webpack-plugin#192]
webpack version 3.8.1
uglifyjs-webpack-plugin version 0.4.6

plugins config:
```
 new UglifyJSPlugin({
        compress: true,
        warnings: false
    })
```
![5050bc34-773e-91e6-0046-27fa110e613d](https://user-images.githubusercontent.com/10299842/33987784-17c001dc-e0fd-11e7-99d2-e29dc7281842.jpg)
![753a24a1-befc-5ca9-954f-9181d5891f73](https://user-images.githubusercontent.com/10299842/33987787-18b16914-e0fd-11e7-956e-b1c61bcede4e.jpg)
After the output of "d", it does not execute

**Comment by evilebottnawi** [comment]
@huboshu0819 can you create minimum reproducible test repo?

**Comment by huboshu0819** [comment]
I'd resloved this problem by update uglifyjs-webpack-plugin to 1.1.3, thanks
