### ISSUE TITLE
Provide list of not-yet-supported ES6 features 

### ISSUE THREAD

**Issue by Kitanotori** [webpack-contrib/uglifyjs-webpack-plugin#2]
The harmony branch of UglifyJS (https://github.com/mishoo/UglifyJS2#harmony) does not yet fully support ES6. Provide information on what features are not yet supported and how to avoid issues during minification.

Follow https://github.com/mishoo/UglifyJS2/issues/1433 for reference.

**Comment by jpollard-cs** [comment]
I know one of them is assignment-destructuring statements, but there's already a PR here: https://github.com/mishoo/UglifyJS2/issues/1402#issuecomment-266182075

**Comment by jskrzypek** [comment]
Should also follow https://github.com/mishoo/UglifyJS2/issues/448, no?

**Comment by michael-ciniawsky** [comment]
We will update the plugin to a newer version of `uglify` soon, so docs for this won't be needed anymore :) thx
