### ISSUE TITLE
UglifyJsPlugin fails if the entry file is outside the package directory

### ISSUE THREAD

**Issue by nuthinking** [webpack-contrib/uglifyjs-webpack-plugin#203]
I am trying to build an npm module from code used in an app to limit the number of projects and not having to distribute the source map. For this reason the building assets for the module (webpack config, package.json and .babelrc) are outside the project `src` folder and in the module webpack config I specify as entry `../src/folder/index.js`. When building I get:

```
    ERROR in index.js from UglifyJs
    Unexpected token name «extends», expected punc «)» [index.js:87,63]
```

If I copy the folder containing the entry inside the folder with all the building assets, and change the entry to `./folder/index.js`, all works.

Maybe this is related to the fact that facebook/create-react-app doesn't build symlinked folders. Thanks!

**Comment by evilebottnawi** [comment]
@nuthinking seems you have old version uglify webpack plugin, can you create minimum reproducible test repo?
