### ISSUE TITLE
Doesn't playing well with ModuleConcatenationPlugin

### ISSUE THREAD

**Issue by dangh** [webpack-contrib/uglifyjs-webpack-plugin#209]
Hi,

I'm not sure if this is the right place to report this issue.

I'm facing a runtime exception in my uglified output: `Uncaught SyntaxError: Missing initializer in const declaration`.

It only happens when I enable both UglifyjsWebpackPlugin and ModuleConcatenationPlugin. Disable one and the issue gone.

Below is the code and the shortened output where the exception belongs to.
```js
import {flush} from './flush'

export class MyClass {
  * test (channel) {
    const pendingActions = yield flush(channel)
    console.log(pendingActions)
  }
}
```
```js
const t=yield n=e,checkForbiddenStates(),(0,_utils.check)(n,_utils.is.func,"channel.flush' callback must be a function"),void(closed&&buffer.isEmpty()?n(END):n(buffer.flush()));
```

I create a reproduce repo here: https://github.com/dangh/reproduce-uglifyjs-webpack-plugin

My environment:
```
uglifyjs-webpack-plugin: 1.1.6
webpack: 3.10.0
babel: 7.0.0-beta.38
nodejs: 9.4.0
chrome: 65.0.3322.3 dev
os: macOS 10.13.3 beta
```

**Comment by kzc** [comment]
https://github.com/mishoo/UglifyJS2/issues/2832

**Comment by evilebottnawi** [comment]
Fixed in https://github.com/mishoo/UglifyJS2. Thanks everyone!
