### ISSUE TITLE
Expose chunk to `options.<test|include|exclude>`

### ISSUE THREAD

**Issue by japgolly** [webpack-contrib/uglifyjs-webpack-plugin#21]
The `test`, `include` and `exclude` options only inspect the output filename, which has no value when the names are like `[hash].[ext]`. It would be very helpful to expose the associated chunk info as well.

**Comment by hulkish** [comment]
@japgolly How about this for usage:
````js
new UglifyJsPlugin ({ 
  // same as current behavior, would convert old syntax to this for legacy support.
  assets: {
    test: /foo.js/,
    include: /bar.js/,
    exclude: require.resolve('../some/path'),
  },
  modules: {
    include: require.resolve('../src/dont-uglify-me-specifically')
  },
});
```

I believe this offers basically the finest grain of control.

**Comment by FranckFreiburger** [comment]
I have created a loader for [javascript-obfuscator](https://github.com/javascript-obfuscator/javascript-obfuscator), and I would like to avoid uglifyjs-webpack-plugin to process resources that pass to that loader (because obfuscated code must not be uglified). 

I would like to use something like:
```
  modules(module) (
    if ( module.loaders.find(loader => .... 'javascript-obfuscator-loader' ....) !== null ) {
      return false
    }
    return true;
  ),
```

**Comment by Friksel** [comment]
+1 
A way to exclude libs from uglifying/mangling would be very welcome!

**Comment by evilebottnawi** [comment]
Will be shipped in near future
