### ISSUE TITLE
Works but console shows warning

### ISSUE THREAD

**Issue by 462960** [webpack-contrib/uglifyjs-webpack-plugin#210]
"uglifyjs-webpack-plugin": "^1.1.6",
    "webpack": "^3.10.0"

Console shows in red: ERROR in bundle.js from UglifyJs name expected [ bundle.js : 1.808025]

![error](https://user-images.githubusercontent.com/10447862/35157113-ad82080a-fd3b-11e7-911f-9abd3e02b98f.png)

**Comment by evilebottnawi** [comment]
@462960 can you show wepback config? Maybe you use build-in `uglify` plugin in webpack (he is old version and don't support ecma2015 features,  you need babel-loader)

**Comment by 462960** [comment]
@evilebottnawi  Thanks for support. I was using `uglify-js-plugin` for a long time. Today, without any reason it started throwing error which prevents webpack from doing job. That's why I switched to `uglifyjs-webpack-plugin`. Job done but the error occurs. Node 8.1.2
![webpack](https://user-images.githubusercontent.com/10447862/35167614-db975ce0-fd5e-11e7-912b-e73ea9d8c416.png)

**Comment by evilebottnawi** [comment]
@462960 hm you reinstall `node_modules`? maybe `npm` cache (`npm cache clear --from &&& npm i`)?

**Comment by 462960** [comment]
@evilebottnawi  Thanks! Do you think I should completely reinstall all packages? I haven't been using `npm cache clear --from` command. So, I have to read about it in the first place.
By the way, when `uglify-js-plugin` abruptly refused to work, console had a blue message, telling somewhat about `UglifyJs`, if it matters...

**Comment by michael-ciniawsky** [comment]
Please try `(sudo) npm cache clear --force && rm -rf node_modules package-lock.json` and report back if the issue still persists

**Comment by 462960** [comment]
Thanks @michael-ciniawsky   As far as I understand, I should do eather single 
shot `npm cache clear --force && rm -rf node_modules package-lock.json` or 
one `npm cache clear --force` then the next one `rm -rf node_modules package-lock.json`.
Both ways turned to be non-appliable. 
![cashe](https://user-images.githubusercontent.com/10447862/35210172-c2a39968-ff59-11e7-8763-b17d187e5b45.png)

**Comment by PlayMa256** [comment]
You misspelled cache... it should work.

**Comment by 462960** [comment]
OK, many thanks @PlayMa256 I've already done it. So, the issue solved..

**Comment by evilebottnawi** [comment]
Solved. See comments above. Thanks everyone!
