### ISSUE TITLE
Using a deprecated version of Uglify-es

### ISSUE THREAD

**Issue by vdechef** [webpack-contrib/uglifyjs-webpack-plugin#211]
Using version 1.1.6 of uglifyjs-webpack-plugin, I get an error when running prod bundle : ReferenceError on a thirdparty lib (sax-js).
After some investigation, the culprit is uglify-es 3.3.4 (see this issue https://github.com/mishoo/UglifyJS2/issues/2783). The fix has just been released by uglify-es team.

Forcing uglifyjs-webpack-plugin to use uglify-es 3.3.8 solved my issue locally, so I think it would be great to update it in the npm package.

**Comment by michael-ciniawsky** [comment]
`uglifyjs-webpack-plugin` already installs the latest `uglify-es` version available *at the time* one installs the plugin 

**package.json**
```
"uglify-es": "^3.3.4",
```

>  ℹ️ `^` pulls the latest semver minor/patch version of `ugilfy-es`

It's up to the consumer to update their lockfile(s) via `npm update && yarn upgrade`

Feel free to send a PR to set the minimum to `^3.3.8` if you like
