### ISSUE TITLE
Reserved not working.

### ISSUE THREAD

**Issue by totaki** [webpack-contrib/uglifyjs-webpack-plugin#212]
I try use in last react application using last create-react-app bitcoinjs-lib. And got error in production, on https://github.com/bitcoinjs/bitcoinjs-lib write
```
uglifyjs ... --mangle reserved=['BigInteger','ECPair','Point']
```
i make eject and set in webpack production config, but it's not help
```
 mangle: {
        safari10: true,
        reserved: ["BigInteger","ECPair","Point"]
      }
```

**Comment by evilebottnawi** [comment]
@totaki what version of `uglifyjs-webpack-plugin` you are use?

**Comment by totaki** [comment]
```
uglifyjs-webpack-plugin@^0.4.6:
  version "0.4.6"
  resolved "https://registry.yarnpkg.com/uglifyjs-webpack-plugin/-/uglifyjs-webpack-plugin-0.4.6.tgz#b951f4abb6bd617e66f63eb891498e391763e309"
  dependencies:
    source-map "^0.5.6"
    uglify-js "^2.8.29"
    webpack-sources "^1.0.1
```

**Comment by evilebottnawi** [comment]
@totaki `uglifyjs-webpack-plugin@^0.4.6` use `uglify-js@2` and seems don't have this option look https://github.com/mishoo/UglifyJS2/tree/v2.x#mangle

**Comment by totaki** [comment]
I need use ```except```?

**Comment by evilebottnawi** [comment]
@totaki yes

**Comment by totaki** [comment]
It s not help, only disabled uglify, but +60 Kb :(

**Comment by evilebottnawi** [comment]
@totaki 60kb what?

**Comment by totaki** [comment]
builded js was 550 Kb after disabled 610Kb

**Comment by evilebottnawi** [comment]
@totaki can you try latest version?

**Comment by evilebottnawi** [comment]
@kzc friendly ping, `reserved` don't work in `uglify0js@2` or something invalid?
@totaki can you create minimum reproducible test repo?

**Comment by totaki** [comment]
https://github.com/vasinkd/cryptowallet/tree/develop

**Comment by totaki** [comment]
This is work repo

**Comment by evilebottnawi** [comment]
@totaki thanks!

**Comment by kzc** [comment]
It's all documented.

https://github.com/mishoo/UglifyJS2/blob/harmony/README.md

See also the `keep_*` options.

**Comment by evilebottnawi** [comment]
@kzc thanks!
@totaki please use option above. Feel free to reopen issue if problem still exists
