### ISSUE TITLE
Tree shaking without minification / mangle

### ISSUE THREAD

**Issue by paztis** [webpack-contrib/uglifyjs-webpack-plugin#213]
Is there a way to use the plugin to only do tree shaking /dead code removal, without minification ?

I'd like to have a prod version minified and another non minified (but with the tree shaking for the weight)  in my deliveries to lemy deliveries.

**Comment by michael-ciniawsky** [comment]
https://github.com/mishoo/UglifyJS2/tree/harmony#minify-options and the all the `options` of `options` etc. You will likely need to grind through them and see if you can customize your setup to only included what you want :) There is no switch or the like implemented for this plugin atm sry

**Comment by dietergeerts** [comment]
I tried several options, and I couldn't get it to work to just remove dead code. @michael-ciniawsky , an example of a configuration that ONLY removes dead code would be very helpful.
