### ISSUE TITLE
@latest has no files

### ISSUE THREAD

**Issue by timneutkens** [webpack-contrib/uglifyjs-webpack-plugin#217]
Installing the latest version breaks because there is no `dist` directory.

```
$ ls node_modules/uglifyjs-webpack-plugin
CHANGELOG.md  LICENSE  README.md  node_modules/  package.json
```

**Comment by timneutkens** [comment]
Looks like it was published by @michael-ciniawsky 30 minutes ago.

**Comment by michael-ciniawsky** [comment]
Yeah there is something wrong, another release is also affected. Investigating why...

**Comment by Bradleycorn** [comment]
Yep. My Angular CLI project just started failing builds due to this too.

**Comment by timjklein36** [comment]
Same here. For the time being, downgrading to 1.1.6 for the local project worked for me.
`npm i --save-dev uglifyjs-webpack-plugin@1.1.6`

**Comment by michael-ciniawsky** [comment]
[`v1.1.8`](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/releases/tag/v1.1.8) 🎉 
Sry guys it was my mistake during release 😅

**Comment by timneutkens** [comment]
Thank you @michael-ciniawsky 🙏

**Comment by demiro** [comment]
you guys, you broke the whole internet...... well, for us, no harm done.... just few people mobilised over night coz the things were failing building :)
