### ISSUE TITLE
cheap-source-map doesn't work

### ISSUE THREAD

**Issue by Vanuan** [webpack-contrib/uglifyjs-webpack-plugin#22]
It looks to be incompatible with sourceMap. I use the following versions:

```
    "uglifyjs-webpack-plugin": "^0.3.1",
    "webpack": "2.3.2",
    "uglify-js": "^2.8.18",
```

Config:

```
        devtool: 'cheap-source-map',
...
                new UglifyJSPlugin({
                        sourceMap: true
                })

```

**Comment by bebraw** [comment]
https://github.com/webpack/webpack/issues/2766 seems to be related to this.

**Comment by halfninja** [comment]
For me, `source-map` works but `cheap-source-map` causes the source map to be generated with a single source file, the built asset itself.

**Comment by Vanuan** [comment]
Well, `source-map` results in wrong breakpoints

**Comment by Vanuan** [comment]
Looks like it still uses `webpack-sources@0.1.x` while `0.2.x` is released.

**Comment by bebraw** [comment]
@Vanuan Update to `0.2.x`. Thanks for the heads up.

**Comment by Vanuan** [comment]
Now `source-map` works but only if I don't use CommonsChunkPlugin

**Comment by bebraw** [comment]
@Vanuan Can you confirm the issue against webpack core `UglifyJsPlugin`? Technically it's the same implementation, though, so I expect the result is the same as well.

Could you set up a tiny standalone repository to study?

**Comment by Vanuan** [comment]
I've experimented with debugging a bit more. And I wouldn't say it doesn't work at all, it's just weird. I have to do more clicks (to step into) due to imported functions not being transparent and the stacktrace doesn't preserve function names.

![screenshot from 2017-04-01 02 40 39](https://cloud.githubusercontent.com/assets/361985/24572807/d9ad8e02-1684-11e7-9cd2-453860a58d39.png)

Another problem I've notices is that it's broken when I use `ExtractTextPlugin` to `require` css files along with `css-loader`.

Here's a demo project:

https://github.com/Vanuan/webpack-demo-app

**Comment by Vanuan** [comment]
Also, adding breakpoints to `import` statement doesn't work (it does without uglify)

**Comment by Vanuan** [comment]
So I've tried different options with lines only and it doesn't work at all.

The only option that work is source-map but is uses partially transformed code.
Eval - no luck.
No sources - stacktrace still uses generated function names when throwing errors in the body of module, but that's probably always been so.

**Comment by Vanuan** [comment]
Another strange thing: uglify seems to bubble function declarations which breaks debugging:

```
function render() {
  console.log('Strange');
  console.log('Gotcha'); // <-- put breakpoint here
  ReactDOM.render(<App />, document.getElementById('app'));

  function thisIsStrange() { 
    console.log('rewriting is wrong');
  }
  thisIsStrange();
}

render();
```

**Comment by Vanuan** [comment]
The last one looks related to this: https://github.com/mishoo/UglifyJS2/issues/493

**Comment by Vanuan** [comment]
Destructuring is troublesome:

```
  function destructuringNotWorking(obj) {
    const { prop1, prop2 } = this.obj; // <-- can't set breakpoint here
    console.log(prop1);
  }
  destructuringNotWorking.apply({obj: { prop1: 1, prop2: 2} });
```

Generated code:
```

  function destructuringNotWorking(obj) {
    var _obj = this.obj,
        prop1 = _obj.prop1,
        prop2 = _obj.prop2; // <-- can't set breakpoint here

    console.log(prop1);
  }
  destructuringNotWorking.apply({ obj: { prop1: 1, prop2: 2 } });
```

But it's that way without uglify.

**Comment by Vanuan** [comment]
So I think the only real issue with this plugin is that `cheap` isn't working. Other issues are either reproducible without the plugin or a result of `uglifyjs` itself.

**Comment by bebraw** [comment]
Thanks for the research! I have a feeling `cheap` might be a core level issue as there are a few related to that.

This restriction could be documented in the readme so people know to avoid cheap alternatives with Uglify.

**Comment by Vanuan** [comment]
Ok, so if it's expected, I'm closing.
