### ISSUE TITLE
How to disable in development?

### ISSUE THREAD

**Issue by Pashaster12** [webpack-contrib/uglifyjs-webpack-plugin#221]
I want to disable uglifyjs-webpack-plugin in develompent because webpack's watching with minification is too slow. But I need it in production.

How can I do it?

Ideally it would be something like this:

`disable: process.env.NODE_ENV === "production"`

**Comment by evilebottnawi** [comment]
@Pashaster12 All `disable` option deprecated and will be removed. Webpack in 4 version have 0CJS and enable uglify in production mode by default. In webpack 3, 2, 1 please use something like this:
```js
const webpackConfig = {
  // ...
  plugins: []
};

if (!isDevelopmentEnv) {
  const UglifyJSPlugin = require("uglifyjs-webpack-plugin");

  webpackConfig.plugins.push(new UglifyJSPlugin());
}

module.exports = webpackConfig;
```
