### ISSUE TITLE
Cache: why not enabling it by default?

### ISSUE THREAD

**Issue by jpetitcolas** [webpack-contrib/uglifyjs-webpack-plugin#224]
I'm wondering why `cache` is set to `false` by default. Trying it on our own project gave us a performance boost of approximatively 34%.

And, corollary question: is there any drawbacks for enabling cache? If so, perhaps should we add some lines about it in the README?

Thanks for your great plugin! :)

**Comment by evilebottnawi** [comment]
@jpetitcolas by default `cache` is disable for all tools/plugins/system and etc, it is best practice. PR welcome for docs this, also webpack@4 use cache and parallels by default.

**Comment by marcofugaro** [comment]
Yeah it says [here](https://github.com/webpack/webpack/releases/tag/v4.0.0-beta.0) that 

> UglifyJs now caches and parallizes by default

I guess they still have to update the code.

**Comment by evilebottnawi** [comment]
@marcofugaro it is do webpack, not plugin

**Comment by michael-ciniawsky** [comment]
`webpack >= v4.0.0` by default enables caching && parallelisation, while the plugin in whatever setup it might be used doesn't to avoid eventual integration problems and that's intended as @evilebottnawi already stated. Please just set the appropriate options yourself if needed

**Comment by marcofugaro** [comment]
so, just to be clear, when I do this in webpack4:

```js
optimization: {
  minimizer: [
    new webpack.optimize.UglifyJsPlugin({
      parallel: true,
      cache: true,
    }),
  ],
},
```
is it completely unnecessary?
