### ISSUE TITLE
Uglify causes error in the angular 2 application only in IE, works fine in Chrome and FireFox

### ISSUE THREAD

**Issue by narendra-agashe** [webpack-contrib/uglifyjs-webpack-plugin#23]
Uglify Package version 0.4.0
Node version 7.4.0
Angular Version 2.4.9
Typescript 2.0.0

IE version IE 11

I am running into a weird issue, I am not sure if it is an issue with my implementation or something else.

I am using this webpack plugin with grunt and when I uglify and try to access the code in IE it throws an error that a promise was not found and points to an html page referenced in the angular component. where as same code works perfectly fine in chrome and firefox.

if I don't uglify then code works fine all browsers.

I am confused as to what is going wrong with using uglify and IE. 
I don't use any options on the uglify its just plain uglify.

Please verify and let me know if i am missing something in my configuration or its something else.

Thanks,
Naren

**Comment by bebraw** [comment]
Hi,

Are you shimming `Promise` somehow? I don't know IE that well but it's possible it might need a shim in order to work.

**Comment by narendra-agashe** [comment]
Thanks for your quick reply @bebraw

My Typings.json looks as below
{
  "name": "ng2-webpack-test",
  "dependencies": {
    "es6-promise": "registry:npm/es6-promise#3.0.0+20160211003958"
  },
  "globalDependencies": {
    "es6-shim": "registry:dt/es6-shim#0.31.2+20160602141504",
    "jasmine": "registry:dt/jasmine#2.2.0+20160621224255",
    "node": "registry:env/node#6.0.0+20160622202520"
  }
} 

Am I missing any shim here?

--Naren

**Comment by bebraw** [comment]
I don't understand Angular setups well enough to say anything sure based on that. You could try a different method like [promise-polyfill](https://github.com/taylorhakes/promise-polyfill#simple-use).

Maybe the best thing to do would be to set up a minimal example to run and study.

**Comment by narendra-agashe** [comment]
@bebraw Right.. I will try to make an example.. 
I am still confused because if i don't uglify then the code works just fine on all browsers.

**Comment by michael-ciniawsky** [comment]
@narendra-agashe Any updates on this ?

**Comment by d3viant0ne** [comment]
@michael-ciniawsky - This is very likely an Angular / Uglify problem. The framework, depending on what browsers you are targeting requires quite a bit of shimming. 

In either case, it's not a problem that can be solved in this plugin. @narendra-agashe If you look in the `polyfills.ts` that @angular/cli spits out, you should have a pretty complete list of what needs to be in your bundle for the IE version mentioned above.
