### ISSUE TITLE
Webpack v3.11 + uglifyjs-webpack-plugin + Cannot find module 'source-map'

### ISSUE THREAD

**Issue by Legends** [webpack-contrib/uglifyjs-webpack-plugin#231]
- C:\WINDOWS\system32>node -v v9.5.0
- C:\WINDOWS\system32>npm -v 5.6.0
- C:\WINDOWS\system32>tsc -v Version 2.7.1
- Win 10 x64

I am not sure, if I can update the version, because latest webpack uses uglifyjs-webpack-plugin@**0.4.6**

`tsc`

 
![image](https://user-images.githubusercontent.com/966368/36145643-4671b6f8-10b2-11e8-800a-e741922543a7.png)

--> node_modules/@types/ugligy-js/index.d.ts
![image](https://user-images.githubusercontent.com/966368/36142790-65c7acfa-10a9-11e8-823d-140d4608ced0.png)

![image](https://user-images.githubusercontent.com/966368/36141917-cf3eebf6-10a6-11e8-97e9-1e7820b608ac.png)

**As you can see, there is another node_modules folder inside of uglify-js, which contains the source-map.js file in the dist folder.**

![image](https://user-images.githubusercontent.com/966368/36141843-8f165ad2-10a6-11e8-9718-1b87cee7f72d.png)

**Comment by evilebottnawi** [comment]
@Legends you should add `uglifyjs-webpack-plugin` in package.json and add plugin manually in webpack config, only in webpack@4 you will have `uglifyjs-webpack-plugin` latest version. Also try to remove npm cache `npm cache clear --force` and reinstall deps.

**Comment by Legends** [comment]
**Steps I have done:**

1. Added the plugin with no args to the webpack.config.js (see config below)
2. Deleted node_modules folder.
3. npm cache clear --force
4. npm install
5. tsc  --> same error

```
const {
    join
} = require('path')

const HTMLWebpackPlugin = require('html-webpack-plugin');
const UglifyWebpackPlugin = require('uglifyjs-webpack-plugin')

module.exports = {

    // Pick any source-map that does not require eval.
    // `inline-source-map` gives the best quality for development.
    devtool: 'inline-source-map',

    entry: join(__dirname, 'src/index'),

    plugins: [
        new HTMLWebpackPlugin({
            title: 'Code Splitting'
        }),
        new UglifyWebpackPlugin()  // added by me
    ],

    output: {
        path: join(__dirname, 'dist'),
        filename: 'bundle.js',
        chunkFilename: '[name].bundle.js',
        // Bundle absolute resource paths in the source-map,
        // so VSCode can match the source file.
        devtoolModuleFilenameTemplate: '[absolute-resource-path]'
    },

    resolve: {
        extensions: ['.ts']
    },

    module: {
        loaders: [{
            test: /\.ts$/,
            loaders: ['ts-loader']
        }]
    }
}
```

**Comment by evilebottnawi** [comment]
@Legends can you show npm command that you use to build webpack (or script)?

**Comment by Legends** [comment]
What do you mean with "npm command that you use to build webpack"?
Executing `webpack` on the command line works fine.
But `tsc` fails.
Please clarify what you mean.

**Comment by evilebottnawi** [comment]
@Legends i don't familiar with type script, but seems you use invalid `@types` for uglify-js. Looks here https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/uglify-js/index.d.ts#L1, we don't use `uglify-js`, we use `uglify-es` (harmony branch https://github.com/mishoo/UglifyJS2/tree/harmony). Maybe problem in this?

**Comment by Legends** [comment]
You know what? I will delete everything and create all packages from scratch again, because it worked before.... 

I think the new way is to install packages from

>  npm @types\yourPackage

**Comment by evilebottnawi** [comment]
@Legends Feel free to feedback

**Comment by Legends** [comment]
Is there a way to debug such things, setting a breakpoint?

**Comment by evilebottnawi** [comment]
@Legends Better as this question in `@types`, i don't debug type script

**Comment by Legends** [comment]
I have tracked it down to this npm package:

`npm install @types/html-webpack-plugin --save-dev`

after installing this package, I get the above error, when running `tsc`

**Comment by evilebottnawi** [comment]
@Legends maybe something incompatibility? Can you create issue in `@types`?

**Comment by Legends** [comment]
Regarding my question how to debug it, you can using [node-nightly](https://webpack.js.org/contribute/debugging/#devtools)
