### ISSUE TITLE
Rest parameters not recognized

### ISSUE THREAD

**Issue by flowtsohg** [webpack-contrib/uglifyjs-webpack-plugin#235]
Upon seeing rest parameters, UglifyJs errors with "Name expected".

`function (...args) { }` is enough to test it.

Oddly enough as far as I can see UglifyJs actually did what it needed to do, I got a valid minified file.

I checked on node 8.1.4 and 9.5, webpack 3.11, and uglifyjs-webpack-plugin 1.2.

**Comment by flowtsohg** [comment]
Upon further testing, this only happens when exporting a function with rest parameters via module.exports or the export keyword.

https://github.com/flowtsohg/uglifyjs-webpack-plugin-rest-parameters

**Comment by evilebottnawi** [comment]
@flowtsohg `webpack -p` add build-in `uglify` plugin with old version

**Comment by michael-ciniawsky** [comment]
See @evilebottnawi comment, feel free to reopen if still regressions

**webpack.config.js**
```js
const UglifyJSPlugin = require('uglifyjs-webpack-plugin')

const config = {
   plugins: [
      new UglifyJSPlugin()
   ]
}
```

**Comment by flowtsohg** [comment]
Thanks that works.
