### ISSUE TITLE
Is ES6+ supported or not?

### ISSUE THREAD

**Issue by Offirmo** [webpack-contrib/uglifyjs-webpack-plugin#237]
I'm banging my head on this, as do others all over the internet.

The README doesn't state it clearly, but document some options like `uglifyOptions: { ecma: 6, 7, 8...` which seems to hint that ES6+ is supported.

However, uglifyjs-webpack-plugin complains over a simple arrow function (unexpected token)

So, YES or NO, is ES6+ supported?

Could this be documented clearly in the README?

Thanks a lot for this open source work.

**Comment by michael-ciniawsky** [comment]
Yes and No. `uglifyjs-webpack-plugin >= v1.0.0` supports ES2015+ (ES6+) but the default version of `uglifyjs-webpack-plugin` shipping with `webpack =< v3.0.0 ` is  still on `v0.4.6` which only supports ES5. See this comment (https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/235#issuecomment-366758770) for `webpack =< v3.0.0` ES2015+ (ES6+) usage instructions

**Comment by dbirch-cb** [comment]
If I'm reading the changelog correctly it looks like the answer is back to No. terser-webpack-plugin looks like the option in that case. https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/CHANGELOG.md
