### ISSUE TITLE
TypeError: Cannot read property 'tap' of undefined (Regression in uglifyjs-webpack-plugin@1.2.1)

### ISSUE THREAD

**Issue by gr2m** [webpack-contrib/uglifyjs-webpack-plugin#241]
Hey there 👋 

I see this error showing up since your last release:
https://travis-ci.org/octokit/rest.js/jobs/345401492#L3730

I wish I could help better, I'm still new to webpack and I don’t even know how `uglifyjs-webpack-plugin` get installed, it does not show up when I run `npm ls uglifyjs-webpack-plugin`.

But when I add `uglifyjs-webpack-plugin` as dependency and pin the version to 1.2.0, the error no longer occurs, see: https://travis-ci.org/octokit/rest.js/jobs/345502710#L3766

**Comment by michael-ciniawsky** [comment]
Fix coming in a few minutes thx for the report. `buildMobule`... :D

**Comment by michael-ciniawsky** [comment]
Released in [`v1.2.2`](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/releases/tag/v1.2.2) 🎉

**Comment by gr2m** [comment]
confirmed, thanks a ton 💐
