### ISSUE TITLE
Can't we simply use "uglify-js": "3.3.x" instead of "uglify-es": "^3.3.4" in the dependency

### ISSUE THREAD

**Issue by sahaam** [webpack-contrib/uglifyjs-webpack-plugin#252]
Can't we simply use "uglify-js": "3.3.x" instead of "uglify-es": "^3.3.4" in the dependency as both the packages are same and its creating some confusion. In some repository "uglify-js": "3.3.x" is used.

**Comment by michael-ciniawsky** [comment]
`uglify-js` (ES5) (`master` branch) vs `uglify-es` (ES2015+) (`harmony` branch), the first would require always transpile your code to ES5 before minification

**Comment by evilebottnawi** [comment]
@sahaam this plugin use `uglify-es` in latest version. If other packages use `uglify-js` please create issue about this in their repo. `uglify-es` support all `uglify-js` features and new ECMA features. Downgrade is not needed. Thanks!

**Comment by Slapbox** [comment]
Is there a reason not to hardcode this to `3.3.4` for the time being? In the meantime I've had to fork the package with this change to get a buildable project. Without hardcoding, this plugin uses `3.3.10` which causes the sym.definition bug.

https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/228
