### ISSUE TITLE
uglifyOptions->compress->properties false not work

### ISSUE THREAD

**Issue by mqliutie** [webpack-contrib/uglifyjs-webpack-plugin#260]
webpack version 3.6.0
uglifyjs-webpack-plugin version 1.2.3

```
new UglifyJsPlugin({
    cache: true,
    parallel: true,
    sourceMap: false,
    uglifyOptions: {
        ie8: true,
        compress: {
            warnings: false,
            drop_console: true,
            unused: true,
            properties: false
        },
        mangle: false
    }
})
```
When `webpack -p`  I want `t["default "]` but get `t.default`
When `webapck` It will be `variable["default"]` `variable not compress to t`

**Comment by evilebottnawi** [comment]
@mqliutie using `-p` flag add `uglify-webpack-plugin@0.4.6` which using `uglify-js` and have other options

**Comment by evilebottnawi** [comment]
Please look comment above. Feel free to feedback :+1: 1:
