### ISSUE TITLE
Inline function optimization fails to define some arguments

### ISSUE THREAD

**Issue by jamesopti** [webpack-contrib/uglifyjs-webpack-plugin#265]
This issue appears to be similar/related to #264 but without any variable name clashing, which I think would make it more likely to come across and thus I'm reporting it as a separate issue.
(also filed [issue #3012](https://github.com/mishoo/UglifyJS2/issues/3012) with Uglify-es)

When only a single occurrence of a method happens, Uglify-es is attempting to inline the only usage of the function, but is failing to declare the second variable, causing an uncaught exception.

**Using:**
Webpack @4.1.1
Uglifyjs-webpack-plugin @1.2.4

Minimally reproducible main.js:
```javascript
(function(mod) {
  mod();
})(function() {
  function getMaxSeverity(ax, bx) {
    if (ax === "error") {
      return ax;
    } else {
      return bx;
    }
  }
  function main() {
    var arr = ['test'];
    for (var i = 0; i < arr.length; i++) {
      console.log(getMaxSeverity('one', 'two'));
    }
  }
  main();
});
```

Minifies to:
```javascript
function(o, n) {
    !function() {
        !function() {
            for (var o = ["hey"], n = 0; n < o.length; n++)
                console.log("error" === (e = "one") ? e : bx);
            var e
        }()
    }()
}
```

**Expected**
`two`

**Actual**
Uncaught exception `bx is not defined`

More reproducible test cases here showing working versions of inlining:
https://github.com/jamesopti/uglifyjs-webpack-issue

**Comment by evilebottnawi** [comment]
@jamesopti Duplicate https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/265?

**Comment by sirreal** [comment]
> Duplicate #265?

I think you mean #264 (this is 265)

**Comment by evilebottnawi** [comment]
@sirreal yep, duplicate?

**Comment by sirreal** [comment]
Maybe not 😕 

Here's a chain of references starting with the description of this issue:

* https://github.com/mishoo/UglifyJS2/issues/3012
* https://github.com/mishoo/UglifyJS2/issues/3010#issuecomment-373957512
* https://github.com/mishoo/UglifyJS2/issues/2908

The workaround here seems to be disabling `collapse_vars` (or maybe `conditionals` -- https://github.com/mishoo/UglifyJS2/issues/3010)

---

#264 on the other hand references https://github.com/mishoo/UglifyJS2/issues/2842

This workaround for this seems to be disabling `inline`.

---

They may be different `uglify-es`-side issues and require different workarounds 🙁

I'd say overall this indicates that #262 needs to be discussed.

**Comment by evilebottnawi** [comment]
A lot of problem with `uglify-es` :disappointed: Ways:
1. Found contributor(s) for `uglif-es` and fix some problem asap
2. Release major version where switch to `uglify-js` with note about it is require `babel-loader` for es5+ syntax
3. Migrate `cache` and `parallel` and some other option to `babel-minify` plugin asap and recommandate use their instead `uglify` plugin.

**Comment by kzc** [comment]
`uglifyjs-webpack-plugin` should consider supporting passing in a custom uglify `minify` function similar to how `rollup-plugin-uglify` does it:

https://github.com/TrySound/rollup-plugin-uglify#options

That way users could choose any `uglify-es` or `uglify-js@3.x` API compatible version they like - even a custom version.

**Comment by evilebottnawi** [comment]
@kzc :+1: 
@michael-ciniawsky what about union with `babel-minify` using `custom` function (by default use `uglify`)? It is allow have one plugin for uglifyjs, maybe rename plugin to more common name

**Comment by kzc** [comment]
> what about union with babel-minify using custom function (by default use uglify)? It is allow have one plugin for uglifyjs, maybe rename plugin to more common name

Just from a usability perspective I wouldn't recommend mixing `babel-minify` and `uglify` into a single plugin. Their options are completely different. Use one or the other.

`uglify-es`'s API is a superset of `uglify-js@3`'s API, so you can get away with that.

**Comment by evilebottnawi** [comment]
Close in favor #264, inline doesn't work correctly in many places in `uglify-es`. Solution:
1. Switch on `terser` (PR https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/296) will be merged in new future
2. Allow custom `minify` function, will be done in near future
