### ISSUE TITLE
Firefox error's stack trace is unable to read Source Maps when output code is minified

### ISSUE THREAD

**Issue by kamilogorek** [webpack-contrib/uglifyjs-webpack-plugin#266]
Hey,

I stumbled upon the very strange issue when debugging one of our SDK issues (ref and some more details: https://github.com/getsentry/raven-js/issues/1256).

When this simple code is passed through the Webpack with UglifyJsPlugin, Firefox is unable to correctly read the source map for the bundled code.

![screen shot 2018-03-20 at 16 09 27](https://user-images.githubusercontent.com/1523305/37663675-04b169ac-2c5a-11e8-93ef-b1a758c9ae75.png)

However, when it's not uglified, source maps work just fine

![screen shot 2018-03-20 at 16 15 33](https://user-images.githubusercontent.com/1523305/37663695-0faa2bf0-2c5a-11e8-9613-5873704947a2.png)

I successfully boiled down the issue to this minimal setup:

`// index.js`
```js
var foo = {};
foo.wat();
```

`webpack.config.js`
```js
"use strict";
const webpack = require("webpack");
const path = require("path");

module.exports = {
  devtool: "source-map",
  entry: ["./index.js"],
  output: {
    path: path.join(__dirname, "build"),
    filename: "index.js"
  },
  plugins: [
    new webpack.optimize.UglifyJsPlugin({
      sourceMap: true
    })
  ]
};
```

`index.html`
```
<script src="build/index.js"></script>
```

```
Chrome v64
Firefox v59
Webpack v2.6.1
```

Cheers!

**Comment by evilebottnawi** [comment]
@kamilogorek you use old webpack(2 version) and old version of `uglify` plugin. They very buggy. Only way - update to minimum 3 version and use latest version of `uglify` plugin. Sorry.

**Comment by evilebottnawi** [comment]
@kamilogorek can you create minimum reproducible test repo?

**Comment by kamilogorek** [comment]
@evilebottnawi I posted it at the very top, there's nothing else you need to repro it other than this config and index,js/html files. I can create it tomorrow if you need, as I'm not on my laptop right now.

**Comment by kzc** [comment]
It's behaving as expected - `foo` is optimized away:
```
$ echo '(function(){ var foo = {}; foo.wat(); })();' | bin/uglifyjs -mc | node
[stdin]:1
({}).wat();
     ^
TypeError: (intermediate value).wat is not a function
```
See: [Source Maps and Debugging](https://github.com/mishoo/UglifyJS2/tree/569757d14dbbe04f66af65d7bf0600b3a75efd96#source-maps-and-debugging)

**Comment by evilebottnawi** [comment]
@kzc thanks! @kamilogorek please read comment above :+1:

**Comment by kamilogorek** [comment]
I'm aware of this, tested it myself. It still breaks Firefox source map resolution somehow. I guess I'll just fill an issue there, as it may be FF issue instead.

**Comment by evilebottnawi** [comment]
@kamilogorek feel free to feedback and add link on firefox issue for tracking

**Comment by kamilogorek** [comment]
@evilebottnawi FYI https://bugzilla.mozilla.org/show_bug.cgi?id=1447949

**Comment by evilebottnawi** [comment]
@kamilogorek Thanks!

**Comment by kzc** [comment]
@kamilogorek Regarding https://bugzilla.mozilla.org/show_bug.cgi?id=1447949 consider attaching the minified bundle file and corresponding source map file to that bugzilla ticket to increase the odds of getting it examined.

Here's a possible workaround... Can you patch your local copy of `uglify-es` in `node_modules` used by `uglifyjs-webpack-plugin@1.2.4`, re-run your `webpack@4` config, and report your findings on Firefox?

```patch
--- a/lib/output.js
+++ b/lib/output.js
@@ -1902,6 +1902,9 @@ function OutputStream(options) {
     DEFMAP(AST_Finally, basic_sourcemap_gen);
     DEFMAP(AST_Definitions, basic_sourcemap_gen);
     DEFMAP(AST_Constant, basic_sourcemap_gen);
+    DEFMAP(AST_Class, basic_sourcemap_gen);
+    DEFMAP(AST_Array, basic_sourcemap_gen);
+    DEFMAP(AST_Object, basic_sourcemap_gen);
     DEFMAP(AST_ObjectSetter, function(self, output){
         output.add_mapping(self.start, self.key.name);
     });
```
If it works create a ticket in https://github.com/mishoo/UglifyJS2 with a link to this post.

**Comment by kamilogorek** [comment]
@kzc nice finding. It partially works.

I had to patch `uglify-js` not `uglify-es` that's one thing, and the second one is that Firefox now correctly points to `index.js`, but to the first line, which is `var obj = {}`, not second one `obj.wat()` as it should (it works fine in other browsers after the patch)

It's still a large progress though! :)

<img width="722" alt="screen shot 2018-03-22 at 21 33 46" src="https://user-images.githubusercontent.com/1523305/37796951-c74f3f10-2e18-11e8-8519-db85f60a651e.png">

**Comment by kzc** [comment]
> had to patch uglify-js not uglify-es

That indicates you're using `webpack@3` with `uglifyjs-webpack-plugin@0.4.6`.

Try running `webpack@4` using `uglifyjs-webpack-plugin@1.2.4 `/`uglify-es`.

> Firefox now correctly points to index.js, but to the first line, which is var obj = {}, not second one obj.wat() as it should (it works fine in other browsers after the patch)

The rest is up to Mozilla to deal with then.

**Comment by kamilogorek** [comment]
> That indicates you're using webpack@3 with uglifyjs-webpack-plugin@0.4.6.

I forgot to check which version of `webpack` I used, but I definitely used built-in `uglify-js`, not a separate `uglifyjs-webpack-plugin`.
It's not possible to patch `uglifyjs-webpack-plugin@0.4.6` like this, as it doesn't have `AST_Class` and it'll throw an exception :)

Patching `uglify-es` works just fine as well @kzc 
Issue: https://github.com/mishoo/UglifyJS2/issues/3023
