### ISSUE TITLE
Question - Use different UglifyJs configurations for different files?

### ISSUE THREAD

**Issue by Legends** [webpack-contrib/uglifyjs-webpack-plugin#273]
For example I want the function names to be mangled **only for some files** and **for others not**, and so on.
Is this possible?

**Comment by evilebottnawi** [comment]
@Legends You can setup two instance `uglifyjs-webpack-plugin` with difference options and use `test/include/exclude`. It is rare use case and better to avoid this implementation to support easy maintenance.

**Comment by Legends** [comment]
Didn't know I could use multiple instances.. Thanks!
