### ISSUE TITLE
path info and ModuleConcatenation error comment is not removed

### ISSUE THREAD

**Issue by whtsky** [webpack-contrib/uglifyjs-webpack-plugin#278]
reproduction: https://github.com/whtsky/uglify-comments-example
run
```
yarn
yarn build
```

and take a look at files under `dist/`, there's a lot of non-license comments which should be removed, like
```
/*!*********************************!*\
  !*** ./src/lazy.js + 2 modules ***!
  \*********************************/
/*! exports provided: d, c, x, y */
/*! all exports used */
/*! ModuleConcatenation bailout: Cannot concat with ./src/node_modules/cjs.js (<- Module is not an ECMAScript module) */
/*! ModuleConcatenation bailout: Cannot concat with ./src/node_modules/shared.js */
```

**Comment by whtsky** [comment]
So set `output.pathinfo` to `false` in production mode like the doc suggest ( https://webpack.js.org/configuration/output/#output-pathinfo ) resolves the problem, although I'm not sure if this is a expected behavior.

**Comment by evilebottnawi** [comment]
@whtsky Thanks for issue, looks like `pathinfo` is use legal comment (https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/src/index.js#L46). Solution:
1. Change type of comments in webpack (looks pathinfo use this comment type for avoid remove this information from bundle, sometimes people left this in production code for easy debug). For me bad solution.
2. Add warning about `pathinfo` is enable when you use uglify.
3. Add information about this in README.md
4. Nothing, left as is

For me better is `3` point.

**Comment by whtsky** [comment]
sorry, work is busy, I don't have time for this :(

**Comment by evilebottnawi** [comment]
Looks no one does have problem and docs about `pathinfo`, i close this issue, feel free to feedback
