### ISSUE TITLE
[Feature Request] Add an option in uglifyjs to enable excluding use of some variables when uglifying code

### ISSUE THREAD

**Issue by anubmat** [webpack-contrib/uglifyjs-webpack-plugin#282]
Is it possible to have an option that allows us to specify characters that we want the minifier to exclude from being used during minification. Something like excludeChars: ['$']

In my case, with minification, a function call is sometimes reduced to $(o), which is a macro for output path, and is thus misread by the interpreter.

**Comment by evilebottnawi** [comment]
@anubmat We use `uglify-es` package for uglification https://github.com/mishoo/UglifyJS2#minify-options. 
Use `reserved: ['$']` from https://github.com/mishoo/UglifyJS2/tree/harmony#mangle-options
```js
[
  new UglifyJsPlugin({
    uglifyOptions: {
      mangle: {
       reserved: ['$']
      }
    }
  })
]
```

**Comment by anubmat** [comment]
No, can't do.
reserved (default []) -- Pass an array of identifiers that should be excluded from mangling. Example: ["foo", "bar"].

I don't want to exclude $ from being mangled. I want to prevent it from being used for replacing variables/function names during mangling.  

But sure, I'll open that issue against uglify-es
