### ISSUE TITLE
Consider using shorter file names for caching

### ISSUE THREAD

**Issue by JohnReagan** [webpack-contrib/uglifyjs-webpack-plugin#290]
The caching feature of this plugin creates very long file names. Just the path from node_modules 
`node_modules\.cache\uglifyjs-webpack-plugin\content-v2\sha512\2b\ce\fc932e4e75182464ea021da42584368afdfca38facdf52f2b9bf48e468a80d644f1f62c363fd2f2687c8047061725b4cf511b0ec8c3d05dc047de250bf64` is 192 characters alone.  Windows has a [max file path length of 260 characters](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx), so it's easy to exceed 260 if the solution is nested in the file tree. 

I've turned caching off to get around this, but would be a nice improvement for devs on Windows.

**Comment by evilebottnawi** [comment]
@JohnReagan Thanks for issue, we can't solve this problem here, original issue https://github.com/zkat/cacache/issues/122

**Comment by Team1557** [comment]
Help me to understand why the length of files in .cache associated with your plugin cant be fixed?  I cant even delete the folder or file...

![deleteMe](https://user-images.githubusercontent.com/10479263/65802354-76974c80-e149-11e9-8ec4-d5117c99b24a.png)

**Comment by evilebottnawi** [comment]
Because we don't create filename, it is doing by `cacache`
