### ISSUE TITLE
Ascii_only

### ISSUE THREAD

**Issue by dynalz** [webpack-contrib/uglifyjs-webpack-plugin#291]
`new UglifyJSPlugin({`
  `uglifyOptions:{`
`    compress: {`
`      warnings: true`
`    },`
`    output: {`
`      comments: false,`
`      ascii_only: true,`
`    },`
`  },`
`  sourceMap: false`
`})`

Im using v1.2.5. I seen that this should be the correct settings, however the ascii_only doesnt seem to be working for me.
Use case:
"\x6F\x6E\x65\x5F\x65\x78\x61\x6D\x70\x6C\x65" is converting into "one_example" instead of remaining as it is.

**Comment by evilebottnawi** [comment]
@dynalz we only wrapper around `uglify-es`, please create issue in `uglify-es` repo. Thanks!
