### ISSUE TITLE
No dead code removal with webpack 4.7

### ISSUE THREAD

**Issue by royipressburger** [webpack-contrib/uglifyjs-webpack-plugin#292]
Hi all

I know there was some issues about that before, but I can't make the tree shaking / dead code removal to work with Webpack 4.7 in my project.
I tried to remove the source maps and other things and nothing seems to work.

One more issue that I'm seeing is that this package doesn't ignore unused imports.
so for example:
```js
import { someDevThings } from './dev'

//DEV is defined with define plugin to false in prod builds.
if(DEV) {
    someDevThings();
}
```

in this case in production build I still see the dev file in my bundle.
further more I see files are imported and not in use anywhere in my bundle (regardless if it is under unreachable code).

here is a small repo to reproduce.
https://github.com/royipressburger/uglify-js-treeshake-issue

Thanks ahead.

**Comment by evilebottnawi** [comment]
@royipressburger we only wrapper around `uglify`, you should configure uglify for remove this. Somewhere we had this issue with the resolution...

**Comment by royipressburger** [comment]
@evilebottnawi Hi thanks for the fast response.
I look for every issue that is related to this and could not find any thing that helps.
Maybe i missed something?

Also I tried not to reproduce that with `create react app` I used it to create a new project and it looks like the dead code removal works great.
then I updated it to the latest version of react and uglify Webpack plugin `4.8 and 1.2.5` and it didn't worked anymore.

What do you suggest?

**Comment by evilebottnawi** [comment]
@royipressburger anyway link on reproducible test repo is always good :+1:

**Comment by TheLarkInn** [comment]
Also @royipressburger don't statically import something that will be conditionally loaded. Rather use `import(/*webpackMode: "eager" */"./path/to/module")`

**Comment by evilebottnawi** [comment]
@royipressburger friendly ping

**Comment by royipressburger** [comment]
@evilebottnawi yes? :) then example in the repo is what @TheLarkInn answered

**Comment by evilebottnawi** [comment]
@royipressburger problem will be solved?

**Comment by royipressburger** [comment]
@evilebottnawi there wasn't any release, no?
I meant to say that what @TheLarkInn gave is not the same use case.
His answer is not something that resolve the problem

**Comment by royipressburger** [comment]
@evilebottnawi poke? :)

**Comment by evilebottnawi** [comment]
@royipressburger uglify don't know `DEV` value and can't remove

**Comment by royipressburger** [comment]
@evilebottnawi not sure this is related.
If you can look at link I posted Ill be happy, :) its a repo that reproduce the issue.

You can see that in the index I import a function that I'm not using
```js
import {onePlusOne} from './ttt'
```

**Comment by evilebottnawi** [comment]
@royipressburger out of scope uglify, tree shaking do webpack

**Comment by royipressburger** [comment]
@evilebottnawi Thanks for your time.. it looks better now..
For anyone else who encounter something similar my problem was two things:

1. I was missing `NODE_ENV=production` in the env( don't know why its a must).
2. I was missing `sideEffects: false` in the `package.json`

**Comment by evilebottnawi** [comment]
@royipressburger https://github.com/mishoo/UglifyJS2#conditional-compilation-api

**Comment by royipressburger** [comment]
@evilebottnawi Thank you for your time. ill close this issue.
