### ISSUE TITLE
Issue with AngularJS 1.5 Uglifying

### ISSUE THREAD

**Issue by pratoshpro** [webpack-contrib/uglifyjs-webpack-plugin#295]
Webpack version - 4.6.0
Uglifyjs webpack plugin -  1.2.5
AngularJS - 1.5.0

While bundling angularjs project with webpack uglify we are facing issue with dependency injections ( default module like $location and custom service are unable to register. )

I have created a demo app with all the setup that shown error and can be access from [ng6-starter](https://github.com/pratoshpro/ng6-starter) repo.

I have also attached an screenshot of error msg.

![screen shot 2018-05-17 at 12 45 48 pm](https://user-images.githubusercontent.com/19179660/40162724-70858848-59d2-11e8-9413-3d12df96d390.png)

**Comment by evilebottnawi** [comment]
@pratoshpro looks like bug in unligy, can you try https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/293 branch?

**Comment by pratoshpro** [comment]
@evilebottnawi - Do you have any sample code for integration of @fabiosantoscode/uglify-es with webpack 4.

**Comment by evilebottnawi** [comment]
@pratoshpro what?

**Comment by pratoshpro** [comment]
#293  did not work for me have any other sample code with webpack 4.

**Comment by miluoshi** [comment]
@pratoshpro it looks like your code is missing explicit DI annotations, thus the error `function($stateProvider, $urlRouterProvider) is not using explicit annotation and cannot be invoked in strict mode`
You either need to provide explicit annotations (see [here](https://docs.angularjs.org/error/$injector/strictdi)) or use something like [babel-plugin-angularjs-annotate](https://www.npmjs.com/package/babel-plugin-angularjs-annotate) to auto-annotate your DI.
