### ISSUE TITLE
Building and publishing the lib

### ISSUE THREAD

**Issue by Kitanotori** [webpack-contrib/uglifyjs-webpack-plugin#3]
@bebraw If I understood correctly, `"build"` script should be run automatically when `npm install`ing the lib. So, do we want the build step happening at the user side, or should we instead provide minified bundle, e.g. under `./dist` (I think `lib` is for external dependencies, not builds)?

By the way, when I install the lib locally to another project with `npm install ../uglifyjs-webpack-plugin`, the build script is not being executed, and consequently I am missing `lib` directory, unless I have already executed `npm run build` in `../uglifyjs-webpack-plugin`. Is this expected behavior?

Is it fine if we target ES6, i.e. not transpiling into ES5? So, basically we would be publishing the lib as a minified ES6 bundle.

Noticed also that there is another project with the same goal: https://github.com/Akkuma/webpack-uglify-harmony

**Comment by bebraw** [comment]
@Kitanotori I set up a `postinstall` script so you can consume the package from npm and it will build it. The idea is that a version published to npm will skip that step (that version should include only the built version). I also cleaned up the directory structure a bit.

Going with ES6 alone could be interesting, but I guess having the precompilation step in place doesn't hurt (easier to plug in custom features + ES6 modules work).

About Harmony branch, assuming Uglify retains the same API there, we could solve this by making Uglify a peer dependency of the plugin. This way you can decide which version of Uglify to consume. I added an peer dependency for that, but the version likely needs tweaking.

After basic docs and bits are done, I guess we should publish this to npm.

**Comment by bebraw** [comment]
I published the [initial version](https://www.npmjs.com/package/uglifyjs-webpack-plugin).

Note that uglify is a peer dependency of the project so assuming the API of the Harmony branch is the same, I think it should pick it up. If needed, we can tweak the peer dependency to include it.

**Comment by Kitanotori** [comment]
@bebraw I'm not fully convinced about the peer dependency approach. That means user has to figure out the whole harmony thing again before he can use the plugin for minifying ES6. As you said, this is experimental plugin, so why not make it clear that this plugin supports minifying ES6 (excluding those parts that are not yet supported by the harmony branch) out-of-the-box by having the harmony branch as ordinary dependency? If user doesn't want to use the harmony branch, he can just stick to the plugin currently bundled with Webpack.

**Comment by bebraw** [comment]
I tried to keep this as close to the core as possible since this might become the stable option (webpack 3).

That said, this repository could be forked and we could end up with `uglifyjs-webpack-plugin-harmony` or some such that does exactly what you described. Would that work?

**Comment by Kitanotori** [comment]
@bebraw We might be able to avoid the need for forking by just making the documentation very clear about the status of UglifyJS and its harmony branch. I back down on my previous suggestion of direct dependency/forking and instead suggest that let's clarify the documentation.

Made some clarifications and changes to README.md just now.

**Comment by bebraw** [comment]
Thanks. I published `0.1.1` with the readme tweaks. Let me know if you want publish rights and I'll hook you up.

**Comment by Kitanotori** [comment]
Sure, publish rights would be cool.

**Comment by bebraw** [comment]
@Kitanotori Ok. You need to create an account on npm so I can `npm add` you.

**Comment by Kitanotori** [comment]
@bebraw https://www.npmjs.com/~kitanotori

**Comment by bebraw** [comment]
@Kitanotori Done.
