### ISSUE TITLE
Identifiers in JSX attributes not being uglified

### ISSUE THREAD

**Issue by PhilipDavis** [webpack-contrib/uglifyjs-webpack-plugin#30]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Uglify fails to process some identifiers.

I recently upgraded a React/Redux/TypeScript project from TypeScript 2.2 + Babel + Webpack 2.2 to TypeScript 2.3.2 + Webpack 2.5.1. This project makes heavy use of Immutable and i18next.

After the uglify process, my client.js bundle had exactly one reference to i18next_1.t and immutable_1.fromJS, which is odd because I use both all over the app. Both of these caused errors in the browser because i18next and immutable were undefined (the real ones had been uglified).

**If the current behavior is a bug, please provide the steps to reproduce.**

The two instances shared a few attributes:
- they were both referenced from within a JSX attribute
- they were both from a stateless React component

e.g. UglifyJSPlugin fails on this code (note that TypeScript changes the "t" in placeholder to be i18next_1.t)
```ts
import { t } from 'i18next';

export const TitleField = ({ input }: any) =>
    <input id="title" maxLength={ 32 } type="text" { ...input } placeholder={ t("TITLE_PLACEHOLDER") } autoFocus={ true }/>
;
```

However, it worked when I rewrote the component to have the function call outside of the JSX attribute:
```ts
import { t } from 'i18next';

export const TitleField = ({ input }: any) => {
    const placeholder = t("TITLE_PLACEHOLDER");
    return (
        <input id="title" maxLength={ 32 } type="text" { ...input } placeholder={ placeholder } autoFocus={ true }/>
    );
};
```

**What is the expected behavior?**

Identifier should be uglified

**If this is a feature request, what is motivation or use case for changing the behavior?**

n/a

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

webpack v2.5.1
TypeScript v2.3.2
npm v4.0.5
node v6.9.4
Windows 7

**Comment by bebraw** [comment]
Is it possible to reproduce this issue **without** webpack? If so, the issue should be pushed upstream to Uglify.

**Comment by michael-ciniawsky** [comment]
@PhilipDavis Any updates on this matter ?

**Comment by PhilipDavis** [comment]
@michael-ciniawsky I'm not aware of any updates. This is low priority for me because I've found a workaround (which is shown in the second code snippet in the bug description). @bebraw is likely correct that this is actually an issue with Uglify itself, rather than the webpack plugin. Thanks.
