### ISSUE TITLE
 "uglifyjs-webpack-plugin": "^1.2.5"  cant't Protect the variables not to be compressed

### ISSUE THREAD

**Issue by silence-may** [webpack-contrib/uglifyjs-webpack-plugin#301]
excuse me,
i want to protect some variables not to be compressed,
so ，I did a bit of configuration
![image](https://user-images.githubusercontent.com/20940285/40401303-53c56b60-5e78-11e8-85eb-07f470dfd4a2.png)
but,it seems does't work,  there's the following error
![image](https://user-images.githubusercontent.com/20940285/40401345-8cb92d08-5e78-11e8-9e14-8d16bce3d3dd.png)
can you give me some advice?thanks.

**Comment by evilebottnawi** [comment]
@silence-may it is not QA service, also we just wrapper around uglify-es, please read their documentation or create issue there https://github.com/mishoo/UglifyJS2/tree/harmony. Thanks!
