### ISSUE TITLE
Unnecessary warning on "invalid source map" for JSON files

### ISSUE THREAD

**Issue by creage** [webpack-contrib/uglifyjs-webpack-plugin#313]
I am using a [po-loader](https://github.com/perchlayer/po-loader) to load my PO files, having this loader config
```javascript
{
    test: /\.po$/,
    include: path.resolve(ROOT, 'i18n'),
    type: 'json',
    use: 'po-loader'
}
```

When building **production** build with minification on, I see a warning for final JSON file, which generates following sourcemap
```
{"version":3,"sources":[],"names":[],"mappings":"","file":"chunks/1.df2663.js","sourceRoot":""}
```

which is, according to [this fix](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/284/commits/89aa4ac302c2dea8f2b91376dec3591565996aed) should be treated as an **emptyRawSourceMap**, and should be a valid one

```javascript
expect(utils.isSourceMap(emptyRawSourceMap)).toBe(true);
```

But I still see
`` WARNING in chunks/1.df2663.js contain invalid source map
``

I'm running
webpack 4.12.0
nodejs 10.4.0
Windows 10

**Comment by evilebottnawi** [comment]
@creage hm, we already fix this, need just release patch version :smile:

**Comment by evilebottnawi** [comment]
New version will be release in near future, thanks for issue
