### ISSUE TITLE
[Doc] Add a note about the fact that webpack includes an outdated version

### ISSUE THREAD

**Issue by Nek-** [webpack-contrib/uglifyjs-webpack-plugin#314]
Hello guys,

_First thanks for your work on this plugin._

I just took like 1 hour of research because I didn't install the plugin with yarn and I had issues. I was about to write an issue but your message noticed me about verifying the version before posting... And well, it was not installed at all.

After proper installation, everything was ok. Please guys, add a note in the readme (not about the webpack integration, but about the probably outdated version that comes with webpack).

Thanks :) .

_Here is the error I had (for google 😋)._

```
ERROR in app_bundle.js from UglifyJs
Unexpected token: name (Session) [./node_modules/angular2-template-loader!./src/app/service/session.service.ts:5,13][app_bundle.js:20885,4]
```

**Comment by evilebottnawi** [comment]
@Nek- webpack contain old uglify plugin version, please update your lock file and/or reinstall node_modules, thanks!

**Comment by Nek-** [comment]
I didn't update webpack but simply install uglifyjs alone. Call it how you want. I call it "outdated dependencies". Btw the project is 1 week old.
