### ISSUE TITLE
default disabled inline optimization doesnt work with custom uglifyjs options.

### ISSUE THREAD

**Issue by Mayank1791989** [webpack-contrib/uglifyjs-webpack-plugin#318]
When custom compress option is passed in options then ```compress.inline``` is not set to false.

```js
new WebpackUglifyJSPlugin({
  uglifyOptions: {
    compress: {
      warnings: true
    },
  }
})
```

### Tested with version
```
"uglifyjs-webpack-plugin": "1.2.7",
```

### Expected

```compress.inline``` should be set to false to avoid issue #307

**Comment by evilebottnawi** [comment]
@Mayank1791989 It is expected, you should manually set `inline: false` (or other values), some people use `inline` in some cases

**Comment by Mayank1791989** [comment]
Ok thanks
