### ISSUE TITLE
Bad minification of single expression with const variable

### ISSUE THREAD

**Issue by Cellule** [webpack-contrib/uglifyjs-webpack-plugin#319]
Source code:
```js
function n(e) {
  if (e) {
    const t = setInterval(() => {
      clearInterval(t);
    }, 1000);
  }
}

n(true);
n(false);
```

Minified code:
```js
  function n(e) {
    if (e) const t = setInterval(() => {
      clearInterval(t)
    }, 1e3)
  }
  n(!0), n(!1)
```

Because the brackets have been removed around the `if` statement, it is now a syntax error to use `const` for the variable `t`

**Comment by kzc** [comment]
Run `terser` to see whether a bug exists, and if so file a bug report. No need to /cc me in the future.

**Comment by kzc** [comment]
obligatory link:

https://github.com/fabiosantoscode/terser#replacing-uglify-es-with-terser-in-a-project-using-yarn

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/262
