### ISSUE TITLE
Different uglify results with different version ?

### ISSUE THREAD

**Issue by imwtr** [webpack-contrib/uglifyjs-webpack-plugin#324]
The plugin version in webpack4 is flexible as `"uglifyjs-webpack-plugin": "^1.2.4"` , when I `npm i` again, a new version @1.2.7 is installed (last version is @1.2.5). 
But after rebuilding the project, the uglify file results change.
Is it a bug or inevitable ? And how to avoid these changes.

**Comment by evilebottnawi** [comment]
@imwtr https://github.com/webpack-contrib/uglifyjs-webpack-plugin/releases/tag/v1.2.6, please read changelog before ask questions, it is not QA, you can enable inline, but it is buggy.
