### ISSUE TITLE
Invalid string length

### ISSUE THREAD

**Issue by dds-du** [webpack-contrib/uglifyjs-webpack-plugin#326]
Cause our angular project has a big size module,we can't package it success.
It will throw an error "var string = JSON.stringify(message) + '\n'; " and "Invalid string length".
When I reduce some component of this module,I can package it success.
So, I sure it  because of the body volume.
Version: "1.2.6"

**Comment by evilebottnawi** [comment]
@dds-du need reproducible test repo, without this i can't help, sorry

**Comment by dds-du** [comment]
@evilebottnawi https://github.com/trivago/parallel-webpack/issues/54
You can see this issue.it's a same problem with our project.

**Comment by evilebottnawi** [comment]
Sorry, without minimum reproducible test repo i can't solve your problem, also you can increase nodejs memory usage (it should be help). In some cases 512mb is not enough to uglify bug projects. Feel free create new issue with minimum reproducible test repo.
