### ISSUE TITLE
Runtime error after minification.

### ISSUE THREAD

**Issue by trusktr** [webpack-contrib/uglifyjs-webpack-plugin#327]
Version: `1.2.7`
Node version: `9.11.2`
OS: `macOS 10.13.4 (17E199)`

## problem

When I compile without minification in Webpack's `production` mode,

```js
    optimization: { minimize: false },
```

then I get a runtime error with my code, saying that my object is undefined when I try to call a method on it:

```
Uncaught TypeError: Cannot read property 'construct' of undefined
    at V.constructor (global.js:138)
    at V.WebComponent (global.js:1)
    at V.DeclarativeBase (global.js:1)
    at V.HTMLScene (global.js:1)
    at V.TreeNode (global.js:1)
    at V.Observable (global.js:1)
    at V.Sizeable (global.js:1)
    at V.Transformable (global.js:1)
    at V.ImperativeBase (global.js:1)
    at new Scene (global.js:1)
```

## reproduction

This works (minification is turned off):

```
git clone https://github.com/trusktr/infamous.git
cd infamous
git checkout uglifyjs-webpack-plugin-issue-327
npm install
npm run build
npm install -g http-server
http-server .
```

open `localhost:8080/test.html`, and you should see a cube:

<img width="1386" alt="screen shot 2018-07-07 at 9 47 11 am" src="https://user-images.githubusercontent.com/297678/42412933-c6f7c220-81ca-11e8-82b6-8e68b470d6b7.png">

To enable the error, open `node_modules/builder-js-package/config/webpack.base.config.js`, then change the line

```
    optimization: { minimize: false },
```

to

```
    optimization: { minimize: true },
```

Now refresh the page (make sure you have devtools open with cache disabled so it will load the new file), and you will see errors in the console (with sourcemaps turned off):

<img width="503" alt="screen shot 2018-07-07 at 9 50 27 am" src="https://user-images.githubusercontent.com/297678/42412950-3762dfe0-81cb-11e8-87b4-3e7473a2500e.png">

The file in question is `global.js`, which is outputted at the root of the project.

I'd provide a simpler reproduction, but I don't know what the problem is in order to reproduce a simple version.

**Comment by trusktr** [comment]
You may notice the webpack configuration is located inside the `builder-js-package`.

To run the build directly, you can run the following:

```
node_modules/.bin/webpack --config ./node_modules/builder-js-package/config/webpack.config.js
```

**Comment by evilebottnawi** [comment]
@trusktr looks it is bug in `uglify-es`

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/298
