### ISSUE TITLE
Unable to add a reserved word to mangle

### ISSUE THREAD

**Issue by xavierfoucrier** [webpack-contrib/uglifyjs-webpack-plugin#328]
Hi,

I am experiencing an issue with `webpack 4.14` + `uglifyjs-webpack-plugin 1.2.7` + `uglify-es 3.3.9`: I am unable to add a reserved class name to mangle in webpack production mode to prevent the minifier from renaming it...

When compressing my bundle in **production mode**, uglifyjs-webpack-plugin is renaming the `Smooth` class name of the external package. Setting a reserved word does not seems to fix the problem.

Here is a preview of my `webpack.prod.js` configuration file:

```
const path = require('path');
const uglify = require('uglifyjs-webpack-plugin');

module.exports = {
  mode: 'production',
  entry: './javascript/src/script.js',
  output: {
    filename: 'app.min.js',
    path: path.resolve(__dirname, 'javascript')
  },
  optimization: {
    minimizer: [
      new uglify({
        parallel: true,
        uglifyOptions: {
          output: {
            comments: false
          },
          mangle: {
            reserved: ['Smooth']
          }
        }
      })
    ]
  }
};
```

And here is a link to a **test repository** where the issue happen: https://github.com/xavierfoucrier/webpack-uglify-es-mangle.

The problem is that `new Smooth(...)` is transformed into `new v(...)` in the minified version.

I tried a lot of things in the configuration: compress options, mangle options, etc.. nothing works.

Thanks for your help.
Best regards :wink: 

Node JS 9.5.0 on Windows 7 Pro x64

**Comment by xavierfoucrier** [comment]
But it seems to properly work with a **basic code** like:

```
class Rectangle {
  constructor(width, height) {
    this.width = width;
    this.height = height;
  }
}

const rect = new Rectangle();
rect.width = 10;
rect.height= 10;
```

**Comment by evilebottnawi** [comment]
@xavierfoucrier please use `keep_classnames` option (https://github.com/mishoo/UglifyJS2/tree/harmony#minify-options), feel free to feedback
