### ISSUE TITLE
switch to uglify-es

### ISSUE THREAD

**Issue by graingert** [webpack-contrib/uglifyjs-webpack-plugin#33]
Related somewhat to https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/32

get rid of all the "if using ES2017 install from git" etc, and switch to `uglify-es` only.

**Comment by skorunka** [comment]
How can I use `uglify-es` instead of `uglify-js` in webpack?

**Comment by bebraw** [comment]
@skorunka It's not possible until someone ports the plugin to the new API of Uglify.

**Comment by skorunka** [comment]
@bebraw I see, is there any workaround?

**Comment by bebraw** [comment]
@skorunka No workaround until someone has time to perform the upgrade,

**Comment by skorunka** [comment]
@bebraw Thank you.

**Comment by johnspurlock** [comment]
@skorunka Hmm, I've been using a similar workaround (see below) while waiting for this issue, and it seems to be working for me.  Copying here in case it helps you.

```javascript
/* package.json */
"devDependencies": {
    "uglify-js": "git://github.com/mishoo/UglifyJS2#harmony-v2.8.22",
    "uglifyjs-webpack-plugin": "0.4.3",
```
```javascript
/* webpack.config.js */
const UglifyJSPlugin = require('uglifyjs-webpack-plugin');
new UglifyJSPlugin()
```

**Comment by skorunka** [comment]
That helped! I had to delete `node_modules` folder and `npm i` so I get the rid of all previously installed `uglify-js` mutations.

**Comment by JemarJones** [comment]
Why does the README tell us to use github.com/mishoo/UglifyJS2#harmony and not mention @johnspurlock's fix?

**Comment by bebraw** [comment]
@JemarJones PR welcome. Thanks. 👍

**Comment by zhaiduo** [comment]
Try method from @johnspurlock, still not work.

> ERROR in scripts/p.js from UglifyJs
Unexpected token: punc ()) [scripts/p.js:80,64]

This is my devDependencies:

> "babel-cli": "^6.24.1",
    "babel-core": "^6.25.0",
    "babel-preset-es2015": "^6.24.1",
    "uglify-js": "git://github.com/mishoo/UglifyJS2#harmony-v2.8.22",
    "uglifyjs-webpack-plugin": "^0.4.3",
    "webpack": "^2.6.1",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-dev-middleware": "^1.10.2",
    "webpack-hot-middleware": "^2.18.0",

**Comment by kurtextrem** [comment]
The most recent uglifyjs-webpack-plugin version broke something. If I return back to 0.4.4 everything works again.

**Comment by ricricucit** [comment]
I still get `Unexpected token punc «(»` anyone?

**Comment by graingert** [comment]
@ricricucit could you make a test case for that?

**Comment by michael-ciniawsky** [comment]
Done in #63
