### ISSUE TITLE
The Given Docs doesn't work for webpack stream (gulp)

### ISSUE THREAD

**Issue by IamManchanda** [webpack-contrib/uglifyjs-webpack-plugin#339]
I am trying to use this in Gulp + Webpack [workflow](https://webpack.js.org/guides/integrations/#gulp) but this doesn't seem to work.

I Implemented as per the mentioned docs but doesn't seem to work https://github.com/IamManchanda/gulp-webpack/pull/7/files

Am I missing something?

**Comment by evilebottnawi** [comment]
@IamManchanda sorry it is not QA service - stackoverflow, gitter, etc, please use this resources for question. It is bug tracker.

**Comment by IamManchanda** [comment]
ohk thanks posted it here => https://stackoverflow.com/questions/51821330/uglify-js-webpack-plugin-for-webpack-stream-gulp-webpack
