### ISSUE TITLE
ES6 in my ES5 output

### ISSUE THREAD

**Issue by Artimal** [webpack-contrib/uglifyjs-webpack-plugin#342]
Hi, I have strange issue with exporting my code into ES5. There is only one place in my minified code that contains ES6 features like "const", "let" or arrow functions:

`,,,,,,function(e,t,n){"use strict";Object.defineProperty(t,"__esModule",{value:!0});var r=function(e){return e&&e.__esModule?e:{"default":e}}(n(201));t["default"]=function(e,t){return r["default"].captureException(new Error(e),{extra:t})}},function(e,t,n){"use strict";function r(e,t){return t.encode?t.strict?c(e):encodeURIComponent(e):e}function o(e,t){return t.decode?s(e):e}function i(e){return Array.isArray(e)?e.sort():"object"==typeof e?i(Object.keys(e)).sort((e,t)=>Number(e)-Number(t)).map(t=>e[t]):e}function a(e){const t=e.indexOf("?");return-1===t?"":e.slice(t+1)}function u(e,t){const n=function(e){let t;switch(e.arrayFormat){case"index":return(e,n,r)=>{t=/\[(\d*)\]$/.exec(e),e=e.replace(/\[\d*\]$/,""),t?(r[e]===undefined&&(r[e]={}),r[e][t[1]]=n):r[e]=n};case"bracket":return(e,n,r)=>{t=/(\[\])$/.exec(e),e=e.replace(/\[\]$/,""),t?r[e]!==undefined?r[e]=[].concat(r[e],n):r[e]=[n]:r[e]=n};default:return(e,t,n)=>{n[e]!==undefined?n[e]=[].concat(n[e],t):n[e]=t}}}(t=Object.assign({decode:!0,arrayFormat:"none"},t)),r=Object.create(null);if("string"!=typeof e)return r;if(!(e=e.trim().replace(/^[?#&]/,"")))return r;for(const i of e.split("&")){let[e,a]=i.replace(/\+/g," ").split("=");a=a===undefined?null:o(a,t),n(o(e,t),a,r)}return Object.keys(r).sort().reduce((e,t)=>{const n=r[t];return Boolean(n)&&"object"==typeof n&&!Array.isArray(n)?e[t]=i(n):e[t]=n,e},Object.create(null))}const c=n(347),s=n(348);t.extract=a,t.parse=u,t.stringify=((e,t)=>{!1===(t=Object.assign({encode:!0,strict:!0,arrayFormat:"none"},t)).sort&&(t.sort=(()=>{}));const n=function(e){switch(e.arrayFormat){case"index":return(t,n,o)=>null===n?[r(t,e),"[",o,"]"].join(""):[r(t,e),"[",r(o,e),"]=",r(n,e)].join("");case"bracket":return(t,n)=>null===n?[r(t,e),"[]"].join(""):[r(t,e),"[]=",r(n,e)].join("");default:return(t,n)=>null===n?r(t,e):[r(t,e),"=",r(n,e)].join("")}}(t);return e?Object.keys(e).sort(t.sort).map(o=>{const i=e[o];if(i===undefined)return"";if(null===i)return r(o,t);if(Array.isArray(i)){const e=[];for(const t of i.slice())t!==undefined&&e.push(n(o,t,e.length));return e.join("&")}return r(o,t)+"="+r(i,t)}).filter(e=>e.length>0).join("&"):""}),t.parseUrl=((e,t)=>({url:e.split("?")[0]||"",query:u(a(e),t)}))},,,,,`
It breaks my project on every browser that don't support ES6. My settings are:
`
rules: [
		{
			test: /\.js$/,
			exclude: /node_modules/,
			use: {
				loader: 'babel-loader',
				options: {
					presets: ['env','react','es2015'],
					plugins: ['transform-object-rest-spread']
				}
			}
		},
`
and:
`
new UglifyJSPlugin({
        uglifyOptions: {
			safari10: true,
        	ie8: true,
        	ecma: 5,
        	warnings: false,
        	output: {
				comments: false,
				safari10: true
			},
			parse: {
				ecma: 5
			},
			compress: {
				ecma: 5
			},
			mangle: {
				safari10: true
			}
        }
    }),
`
What is the problem? Please for help! I will be very thankful.

**Comment by evilebottnawi** [comment]
@Artimal you have es6 code in node_modules, you should use `babel-loader` on some node_modules packages or create separate babel-loader configuration (best only for production) to transiple `es6+` to `es5`.

**Comment by Artimal** [comment]
How can I detect which one package is causing this problem?
