### ISSUE TITLE
Code inside ternary operator is not inlined/removed

### ISSUE THREAD

**Issue by adipascu** [webpack-contrib/uglifyjs-webpack-plugin#343]
The following JS:
```js
export const IS_PRODUCTION = process.env.NODE_ENV === 'production';
const TEST_DATA = IS_PRODUCTION ? 'SOME_STRING' : 'SHOULD_NOT_BE_IN_BUNDLE';
```
Is minified into:
```js
const r=!0,o=r?"SOME_STRING":"SHOULD_NOT_BE_IN_BUNDLE"
```

I was expecting that `SHOULD_NOT_BE_IN_BUNDLE` not be in the outputted bundle. This seems to be somehow caused by exporting `IS_PRODUCTION`.

I am currently using this as a workaround:
```js
const isProd = process.env.NODE_ENV === 'production';
export const IS_PRODUCTION = isProd;
const TEST_DATA = isProd ? 'SOME_STRING' : 'SHOULD_NOT_BE_IN_BUNDLE';
```

[Here is a small project to reproduce the issue.](https://github.com/adipascu/webpack-sscce)

I am using node.js v8.11.3 with uglifyjs-webpack-plugin 1.3.0 (loaded by using webpack 4.16.5 in production mode).

**Comment by evilebottnawi** [comment]
@adipascu because uglify doesn't known about your globals, use `DefinePlugin`

**Comment by adipascu** [comment]
Hi @evilebottnawi , thanks for taking a look!

I think that `NODE_ENV` is defined as global by webpack when `mode` is set to `production`.
Also, I noticed that my workaround is working and also relies on uglify knowing about globals.

Am I missing something?

**Comment by evilebottnawi** [comment]
@adipascu webpack doesn't add `NODE_ENV` by default in your code, because it is can break code in some cases. Use `DefinePlugin`
