### ISSUE TITLE
Webpack won't minify js files in sub-folder

### ISSUE THREAD

**Issue by SD-Dude** [webpack-contrib/uglifyjs-webpack-plugin#344]
Webpack runs (to some extent). It finishes the run. There is one error (see below) which many online have explained about.

ERROR in koLabs.js from UglifyJs
SyntaxError: Unexpected token: punc ()) [./~/source-map-loader!./Labs/labsCtrl.js:512,0]

But, it minifies only select js files mainly in the top folder. It leaves out files in the sub-folder without any minification.

/Scripts/Tomat0 - works
/Scripts/Tomat0/(sub-folders) - doesn't minify

Any thoughts on it.

**Comment by evilebottnawi** [comment]
@SD-Dude Your have invalid code in `labsCtrl.js` on `512` line or your use `uglifyOptions.ecma: 5`, but your code in es5+, also maybe bug in uglify-es, better use https://github.com/webpack-contrib/terser-webpack-plugin
