### ISSUE TITLE
Can't install clean-webpack-plugin

### ISSUE THREAD

**Issue by Flashbackvideoman** [webpack-contrib/uglifyjs-webpack-plugin#345]
npm install --save-dev clean-webpack-plugin
produces the following error:

npm ERR! path /home/dovetail/dealware/node_modules/latest/node_modules/npm/node_modules/dezalgo/node_modules/asap
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/home/dovetail/dealware/node_modules/latest/node_modules/npm/node_modules/dezalgo/node_modules/asap' -> '/home/dovetail/dealware/node_modules/latest/node_modules/npm/node_modules/dezalgo/node_modules/.asap.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

Have tried:
Wiping the node_modules directory and npm install
Checking file permissions.

Node version: 8.11.4
NPM version: 5.6.0

**Comment by evilebottnawi** [comment]
@Flashbackvideoman Not related to `uglifyjs-webpack-plugin` , looks you don't have file system permissions

**Comment by Flashbackvideoman** [comment]
Sorry for not noticing I was in the wrong place!
That said, it is not a file permissions problem.  File not there.

**Comment by evilebottnawi** [comment]
@Flashbackvideoman better create this issue in `clean-webpack-plugin`
