### ISSUE TITLE
Different options to different chunks in one pluign instance.

### ISSUE THREAD

**Issue by tsangint** [webpack-contrib/uglifyjs-webpack-plugin#350]
When webpack make two chunks(eg: a.js and b.js) and I need minify them with different options(for example, a.js can be mangled but b.js shouldn't be mangled)
The uglifyjs-webpack-plugin can not make different options to those two chunks in one plugin instance.
Is it best practice to add two uglifyjs-webpack-plugin instance to webpack config.
Like below:
```
const UglifyJSPlugin = require('uglifyjs-webpack-plugin');
module.exports = exports = {
    plugins : [
        new UglifyJSPlugin({ /use for a.js/ }),
        new UglifyJSPlugin({ /use for b.js/ })
    ]
}
```
Is there any way to do this just write one uglifyjs-webpack-plugin in webpack config.Or is there any plan to support the follow way to support multi rule in just one plugin instance.
```
const UglifyJSPlugin = require('uglifyjs-webpack-plugin');
module.exports = exports = {
    plugins : [
        new UglifyJSPlugin([{
            // options for a.js
        },{
            // options for b.js
        }])
    ]
}
```

**Comment by evilebottnawi** [comment]
@tsangint better use two `instance` for this purpose, no plans to support this

**Comment by tsangint** [comment]
@evilebottnawi Thanks for your reply,I'm not sure is it reasonable to use a plugin twice at one webpack config before.I tried and it seems everyting is ok by using two instance.

**Comment by evilebottnawi** [comment]
@tsangint it si normal usage same plugin with difference options twice
