### ISSUE TITLE
uglifyjs locking folders on windows box with too long filename error

### ISSUE THREAD

**Issue by fairbankm24** [webpack-contrib/uglifyjs-webpack-plugin#351]
When deploying our packages, we clean up node_module folders on the server for cleanup, however since installing the latest uglifyjs-webpack-plugin we're hitting an error on the filename being too long in the .cache subfolder of node_modules

`node_modules\.cache\UGLIFY~1\CONTEN~1\sha512\0d\ca\b49ce4203de0c2e8694cfba636580ca2438cb22e42c39605422224d428c4cbc4e16c602b72a7d61a4a14c5dd874841a02f5d793cb349435edff5b5f7d894 - The system cannot find the path specified.`

we've gotten around it by using rimraf but was wondering why the sha is so long?

**Comment by evilebottnawi** [comment]
@fairbankm24 thanks for issue, but related to plugin , please create issue in https://github.com/zkat/cacache repo, we use this package for caching (a lot of other utils/libraries/applications do this package too, example `npm`)
