### ISSUE TITLE
Error after update to 2.0.1

### ISSUE THREAD

**Issue by stefanfrede** [webpack-contrib/uglifyjs-webpack-plugin#359]
* Operating System: macOS 10.13.6
* Node Version: 10.10.0
* NPM Version: 6.4.1
* webpack Version: 4.19.1
* uglifyjs-webpack-plugin Version: 2.0.1

### Expected Behavior

Minification of my code.

### Actual Behavior

```sh
ERROR in vendors~main.dadb.js from UglifyJs
Unexpected token: keyword (const) [./node_modules/lit-html/lib/directive.js:14,0][vendors~main.dadb.js:3555,0]
```

### Code

```js
exports.minifyJavaScript = () => ({
  optimization: {
    minimizer: [new UglifyWebpackPlugin({ sourceMap: true })],
  },
});
```

### How Do We Reproduce?

+ `git clone git@github.com:stefanfrede/knowthen-counter.git`
+ `git checkout update-webpack-config`
+ `npm i`
+ `npm run build`

**Comment by flekschas** [comment]
I ran into the same issue. An interim solution is to downgrade to `v1.3.0`.

**Comment by evilebottnawi** [comment]
Yes, better use terser plugin, 2 version this plugin uses uglify-js, which do not support es6 syntax. In 1 version we use uglify-es, but this package abadoned and contains a lot of bugs.

**Comment by booboo123** [comment]
Same issue here, downgrade from 2.0.1 to v1.3.0 solved the issue. Why release an untested version?
