### ISSUE TITLE
ES6 support broken again

### ISSUE THREAD

**Issue by bskydive** [webpack-contrib/uglifyjs-webpack-plugin#362]
`npm i uglifyjs-webpack-plugin@1`
solve problems in angular es6 : ERROR in main....bundle.js from UglifyJs Unexpected token: keyword (const) ...
In the most popular webpack+angular config used @1 version, not @2: https://github.com/gdi2290/angular-starter/blob/master/package.json

_Originally posted by @bskydive in https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/104#issuecomment-425830023_

**Comment by evilebottnawi** [comment]
@bskydive Please:
1. Use issue template in future
2. Read CHANGELOG before post issue (https://github.com/webpack-contrib/uglifyjs-webpack-plugin/releases/tag/v2.0.0)
> * Switch back to [uglify-js](https://github.com/mishoo/UglifyJS2) (`uglify-es` is abandoned, if you need uglify ES6 code please use [terser-webpack-plugin](https://github.com/webpack-contrib/terser-webpack-plugin)).
3. Use https://github.com/webpack-contrib/terser-webpack-plugin for ES6 (webpack@5 will be use this plugin for uglification)
