### ISSUE TITLE
ERROR in ./assets/js/commons.js from UglifyJs Unexpected token: keyword (const) 

### ISSUE THREAD

**Issue by m-korkut** [webpack-contrib/uglifyjs-webpack-plugin#367]
I use uglifyjs-webpack-plugin.
I get this error :"ERROR in ./assets/js/commons.js from UglifyJs
Unexpected token: keyword (const) [./assets/js/commons.js:13526,0]
"

what's the solution to this ? 

version info : 
nodejs: v8.12.0
npm 6.4.1,
webpack: "^4.21.0",
"uglifyjs-webpack-plugin": "^2.0.1",
"babel-loader": "^8.0.4",   
 babel : 7

**Comment by mhavci** [comment]
+1
same problem

**Comment by evilebottnawi** [comment]
You code contains `ES6`, `uglifyjs-webpack-plugin` use `uglify-js` to compress code and `uglify-js` doesn't support `ES6`, use https://github.com/webpack-contrib/terser-webpack-plugin

**Comment by kk-fan** [comment]
Execution of "yarn add uglifyjs-webpack-plugin" can be temporarily resolved. The specific reasons need to be further searched.
