### ISSUE TITLE
Location of uglify in webpack

### ISSUE THREAD

**Issue by oreporan** [webpack-contrib/uglifyjs-webpack-plugin#370]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [X] Confusing
- [X] Not Sure?

### Please Explain in Detail...
So pretty new to webpack, trying to migrate from 3 -> 4, running in to this confusion:

According to webpack 4 documentation on the [mode option](https://webpack.js.org/plugins/uglifyjs-webpack-plugin/#getting-started)
 
```js
// webpack.production.config.js
module.exports = {
+  mode: 'production',
- performance: {
-   hints: 'warning'  
- },
- output: {
-   pathinfo: false
- },
- optimization: {
-   namedModules: false,
-   namedChunks: false,
-   nodeEnv: 'production',
-   flagIncludedChunks: true,
-   occurrenceOrder: true,
-   sideEffects: true,
-   usedExports: true,
-   concatenateModules: true,
-   splitChunks: {
-     hidePathInfo: true,
-     minSize: 30000,
-     maxAsyncRequests: 5,
-     maxInitialRequests: 3,
-   },
-   noEmitOnErrors: true,
-   checkWasmTypes: true,
-   minimize: true,
- },
- plugins: [
-   new UglifyJsPlugin(/* ... */),
-   new webpack.DefinePlugin({ "process.env.NODE_ENV": JSON.stringify("production") }),
-   new webpack.optimize.ModuleConcatenationPlugin(),
-   new webpack.NoEmitOnErrorsPlugin()
- ]
}
``` 

according to this documentation:

```js
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');

module.exports = {
  //...
  optimization: {
    minimizer: [new UglifyJsPlugin()]
  }
};
```

### Your Proposal for Changes

Am I supposed to understand from this that it should appear in both `plugins: []` and under `optimization.minimizer` ?

**Comment by evilebottnawi** [comment]
Use only in `optimization.minimizer` for `webpack@4`.

**Comment by oreporan** [comment]
Then something doesn't add up

when setting `mode: none` in webpack 4:

in `optimization.minimizer` I'm getting a bundle size of 33Mb
in `plugins` I'm getting a bundle size of 7Mb

**Comment by evilebottnawi** [comment]
@oreporan `minimizer` enabled in `prod` mode only or you can specify `minimize: true` when you need

**Comment by oreporan** [comment]
thanks
