### ISSUE TITLE
Uglify breaks order of indexes

### ISSUE THREAD

**Issue by sherlock1982** [webpack-contrib/uglifyjs-webpack-plugin#373]
* Operating System: Windows 10
* Node Version: 8.11.2
* NPM Version: 6.4.1
* webpack Version: 4.23.1
* uglifyjs-webpack-plugin Version: 2.0.1

### Expected Behavior

Before and after uglification result of a function call should be the same

```
[ 17, 55357, 56832, 32 ]
[ 17, 55357, 56832, 32 ]

```

### Actual Behavior

```
[ 17, 55357, 56832, 32 ]
[ 17, 56832, 55357, 32 ]

```

### How Do We Reproduce?

Checkout repository at https://github.com/sherlock1982/uglify_issue

Run `npm run build`

Can't be reproduced with previous version of uglify-webpack-plugin
Can't be reproduced without webpack.config.js
Can't be reproduced with standalone call to uglifyjs

**Comment by evilebottnawi** [comment]
@sherlock1982 please post this issue in `uglify-js`, we just wrapper or you can use https://github.com/webpack-contrib/terser-webpack-plugin (new generation uglify, support ES6 and a lot of fixes includes)

**Comment by evilebottnawi** [comment]
Use terser plugin, please read changelog
