### ISSUE TITLE
Breaks the new hooks feature in React 16.7

### ISSUE THREAD

**Issue by steadicat** [webpack-contrib/uglifyjs-webpack-plugin#374]
* Operating System: Mac OS 10.14
* Node Version: 8.11.3
* NPM Version: 5.7.1
* webpack Version: 4.23.1
* uglifyjs-webpack-plugin Version: 2.0.1

### Expected Behavior

https://github.com/steadicat/react-useeffect-test compiles and runs without errors.

### Actual Behavior

Error: `Cannot set property 'lastEffect' of null` .

### Code

```js
// webpack.config.js
const UglifyJSPlugin = require("uglifyjs-webpack-plugin");

module.exports = {
  mode: "production",
  entry: "./index.tsx",
  resolve: {
    extensions: [".js", ".tsx"]
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: {
          loader: "ts-loader",
          options: {
            transpileOnly: true
          }
        }
      }
    ]
  },
  optimization: {
    minimizer: [new UglifyJSPlugin()]
  }
};
```

```typescript
import * as React from 'react';
import * as ReactDOM from 'react-dom';

const Component = () => {
  React.useEffect(() => {});
  return null;
};

ReactDOM.render(<Component />, document.getElementById('app'));
```

### How Do We Reproduce?

- Clone https://github.com/steadicat/react-useeffect-test 
- `npm install`
- `NODE_ENV=production ./node_modules/.bin/webpack-cli`
- Open`index.html` and see the error in the console.

See also: https://github.com/facebook/react/issues/14014

**Comment by theskillwithin** [comment]
is this fixed?

**Comment by davidwieler** [comment]
@theskillwithin Thinking no, as I just tried using this plugin and got the error on a production build.

**Comment by davidgolden** [comment]
I migrated from uglify to the webpack terser plugin and it works.
