### ISSUE TITLE
Feature request: add an option persistentCache

### ISSUE THREAD

**Issue by bertho-zero** [webpack-contrib/uglifyjs-webpack-plugin#376]
The uglify cache is very convenient but disappears between each installation, we could have a `persistentCache: boolean` option that corresponds to `cache: path.join (os.homedir (), '.cache', 'uglifyjs-webpack-plugin')`.

Or maybe we can add it to the readme?

**Comment by evilebottnawi** [comment]
@bertho-zero use https://github.com/webpack-contrib/uglifyjs-webpack-plugin#string , you can change `cache` path
