### ISSUE TITLE
When using pako, result is different

### ISSUE THREAD

**Issue by MasatsuguAida** [webpack-contrib/uglifyjs-webpack-plugin#377]
* Operating System: Ubuntu 14.04.5 LTS,
* Node Version: v10.10.0
* NPM Version: yarn version v1.10.1
* webpack Version: 4.25.1
* uglifyjs-webpack-plugin Version: 2.0.1

### Expected Behavior

development / production
Uint8Array(5) [123, 220, 216, 4, 0]

### Actual Behavior

development
Uint8Array(5) [123, 220, 216, 4, 0]

production
Uint8Array(5) [107, 106, 124, 12, 0]

### Code

```js
import pako from 'pako';
const str = 'あ';
const content = pako.deflateRaw(str);
console.log(content);
```

### How Do We Reproduce?

```
import webpack from 'webpack';
import UglifyJsPlugin from 'uglifyjs-webpack-plugin';

export default {
  entry: './src/main.js',
  output: {
    filename: `js/app.js`,
  },
  mode:
  //"production",
  "development",
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              presets: [
                ['@babel/preset-env', {'modules': false}]
              ],
              compact: false
            }
          }
        ]
      },
    ]
  },
  optimization: {
    minimizer: [new UglifyJsPlugin()],
  },
};
```

**Comment by evilebottnawi** [comment]
@MasatsuguAida Better create this problem in `uglify-js` repository, we just wrapper around `uglify-js` and don't change you code. Also i recommend switch to terser plugin https://github.com/webpack-contrib/terser-webpack-plugin
