### ISSUE TITLE
Exported enum with default values should not be tampered with

### ISSUE THREAD

**Issue by dkhalife** [webpack-contrib/uglifyjs-webpack-plugin#379]
* Operating System: Windows (shouldn't matter)
* Node Version: v10.13.0 (shouldn't matter)
* NPM Version: 6.4.1 (shouldn't matter)
* webpack Version: 6.4.1
* uglifyjs-webpack-plugin Version: 1.2.5

### Expected Behavior
An enum type that is exported and does not specify literal values for each of its constants should not be minified.

### Actual Behavior
The unused constants (in the scope of the bundle) get chopped therefore changing their overall values 

### Code
```
export enum MyEnum {
  Value0,
  Value1,
  Value2,
  Value3,
...
}
```

https://gist.github.com/dkhalife/81459a7e708b3d70d0dc20dda7aebcfd

### How Do We Reproduce?

1- Copy the enum code above. 
2- In your bundle, console.log one of the values, say Value1
3- Build and check the output. You would expect it to be 1, however it will be 0

This is a problem in cases where enums are serialized or shared between more than 1 bundle and not each bundle needs to use all of the values but they all should have the same reference.

One workaround is to manually specify values in the enum like so but that you have the guarantee of the values staying in sync but the plugin should still not assume you need the optimization of trimming a few characters at the expense of the risk it creates.

```
export enum MyEnum {
  Value0= 0,
  Value1= 1,
  Value2= 2,
  Value3= 3,
...
}
```

**Comment by evilebottnawi** [comment]
@dkhalife we just wrapper around `uglify-js` (i.e. all bugs with minification should be created in their repo), also `uglify-js` doesn't support `es6+`, use `terser` plugin https://github.com/webpack-contrib/terser-webpack-plugin , thanks for issue
