### ISSUE TITLE
emoji got broken

### ISSUE THREAD

**Issue by crabicode** [webpack-contrib/uglifyjs-webpack-plugin#38]
Please refer this issue [emoji got stripped when building in create-react-app](https://github.com/facebookincubator/create-react-app/issues/2488)

Seems like the uglifying removes some required bits from emoji symbols:

production -> "ðŸ•¹ï¸�": "1f579
development -> "🕹️":"1f579"

Any ideas what can cause the problem?

**Comment by bebraw** [comment]
Can you try it against Uglify itself? There might not be much we can do about the issue in the plugin itself.

**Comment by evilebottnawi** [comment]
@crabicode Your use `emoji` in css, if yes it is do `css-loader`, known issue

**Comment by michael-ciniawsky** [comment]
@crabicode Any updates on this ?

**Comment by crabicode** [comment]
@michael-ciniawsky,

I believe the issue is no longer relevant since it could have been avoided by other means.

anyway, thanks
