### ISSUE TITLE
ERROR in js/background.js from UglifyJs Unexpected token: keyword (const)

### ISSUE THREAD

**Issue by abhijithvijayan** [webpack-contrib/uglifyjs-webpack-plugin#389]
ERROR in js/background.js from UglifyJs
Unexpected token: keyword (const) [js/background.js:421,4]

using "uglifyjs-webpack-plugin": "^2.1.1",

![](https://i.imgur.com/CYOEAQc.png)

**Comment by evilebottnawi** [comment]
Uglify-js doesn't support es6 syntax, use `terser` plugin

**Comment by abhijithvijayan** [comment]
@evilebottnawi Thanks. Switched to `terser`.
