### ISSUE TITLE
Webpack's removes classnames when minifying/uglifying ES6 code with inheritance

### ISSUE THREAD

**Issue by ericmorand** [webpack-contrib/uglifyjs-webpack-plugin#394]
This is a follow-up to #269.

This is still not fixed. Using this perfectly valid ES6 syntax:

````javascript
class Foo {
    getConstructorName() {
        return this.constructor.name;
    }
}

let foo = new Foo();

console.warn(foo.getConstructorName()); // output "Foo" when non-minified; "" when minified
````

webpack will output "" instead of "Foo".

I insist on the fact that this is a perfectly valid syntax that totally respects ES6 specifications. There is not point arguing about that.

**Comment by evilebottnawi** [comment]
Because `uglify-js` doesn't support `es6` syntax, please use `terser` plugin

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/terser-webpack-plugin
