### ISSUE TITLE
Option to keep jsonp names

### ISSUE THREAD

**Issue by muuvmuuv** [webpack-contrib/uglifyjs-webpack-plugin#398]
* Operating System: macOS 10.14.3
* Node Version: 10.15.1
* NPM Version: 6.4.1
* webpack Version: 4.29.5
* uglifyjs-webpack-plugin Version: 2.1.1

### Feature Proposal

An option to keep the names of webpacks jsonp object.

### Feature Use Case

I'm building a theme for a CMS and multiple modules/components/plugins. In many of them and the theme itself I use Webpack. The most of them using shared libraries like jQuery. Now I have figured out that with `splitChunks` I can split them and just load one vendor and with `runtimeChunk.name` I can remove the `webpackJsonpCallback` from the another and just need to load one for all. This heavily reduced my websites size! 

Now and sadly this just works when working in development (uglify off) because with __uglifyjs__ the modules that are imported to `webpackJsonpCallback` are only numbers instead of the vendor name. 

So the problem is here that each project has its own Webpack and therefore produces another `webpackJsonpCallback` array structure. This is no problem without __uglifyjs__ because it would override the vendors with the same name e.g. `jquery`.

I hope it is understandable.

```js
(window["webpackJsonp"]=window["webpackJsonp"]||[]).push([[1] // from a plugin
```

![Bildschirmfoto 2019-03-18 um 13 24 18](https://user-images.githubusercontent.com/11534760/54529811-4a706700-4981-11e9-8e3e-85430538e387.png)

```js
(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["jquery"],{ // from a plugin
```

![Bildschirmfoto 2019-03-18 um 13 26 17](https://user-images.githubusercontent.com/11534760/54529935-928f8980-4981-11e9-9d03-46a108420054.png)

**Comment by evilebottnawi** [comment]
Not related to plugin, use https://github.com/mishoo/UglifyJS2#mangle-options `reserved` option if you want too keep name, we just wrapper around `uglify-js`

**Comment by muuvmuuv** [comment]
Hey @evilebottnawi, thanks! Sorry, you are right I will open it there 'cause the reserved methods does not help.
