### ISSUE TITLE
The library file reported an error when I packaged the project

### ISSUE THREAD

**Issue by HeiShanLaoYao889** [webpack-contrib/uglifyjs-webpack-plugin#399]
![image](https://user-images.githubusercontent.com/24189898/55928230-904fe080-5c4a-11e9-873e-537e1ac9ffb6.png)
```
assets/js/chunk-vendors.e747b9c7.js from UglifyJs
Unexpected token: keyword (const) [assets/js/chunk-vendors.e747b9c7.js:28924,0]
```

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue. You try to minify ES5+ syntax, pleas use `terser webpack plugin`, uglify doesn't support ES5+ syntax

**Comment by HeiShanLaoYao889** [comment]
No, I'm using ES6 syntax, the rest of the libraries are perfect
![image](https://user-images.githubusercontent.com/24189898/56006719-a2905400-5d08-11e9-9cf8-c8e7c1256b54.png)
