### ISSUE TITLE
feat: add options validation

### ISSUE THREAD

**Issue by bebraw** [webpack-contrib/uglifyjs-webpack-plugin#4]
It should be processed through [ajv](https://www.npmjs.com/package/ajv) to give proper errors if the schema validation fails.

**Comment by michael-ciniawsky** [comment]
#64, but it is inconvenient because of `{Function}` && `{Regex}` usage of options 😞. Needs a custom `ajv` 'adapter' in `schema-utils` to support the 2 types first. Does core already handle this somewhere so I can take a look at that maybe 🙃 ?
