### ISSUE TITLE
When using webpack to package the vue project, there is a problem

### ISSUE THREAD

**Issue by taoyuancun123** [webpack-contrib/uglifyjs-webpack-plugin#404]
* Operating System:
* Node Version:
* NPM Version:
* webpack Version:
* uglifyjs-webpack-plugin Version:

### Code

```js
  // webpack.config.js
  // If your code blocks are over 20 lines, please paste a link to a gist
  // (https://gist.github.com).
```

```js
  // additional code, HEY YO remove this block if you don't need it
```

### How Do We Reproduce?

ERROR in main.3853bdb6421aac543ea9.js from UglifyJs
Unterminated string constant [main.3853bdb6421aac543ea9.js:527,17]
Child html-webpack-plugin for "..\index_prod.html":
     1 asset
    Entrypoint undefined = ../index_prod.html

**Comment by Valerika** [comment]
I have the same problem

**Comment by taoyuancun123** [comment]
> rvice-files/bundle.min.js:469,75528]
I reslove this by reinstall all the tools guide by offcial website(vuejs.org).
I think is some tools version wrong.

**Comment by evilebottnawi** [comment]
Based on logs you have 2 minificator (uglify-js and terser) please double check you setup
