### ISSUE TITLE
Better error/suggestion when passing options

### ISSUE THREAD

**Issue by d7my11** [webpack-contrib/uglifyjs-webpack-plugin#405]
* Operating System: macOS 10.14.4
* Node Version: v10.15.3
* NPM Version: 6.4.1
* webpack Version: 4.27.0
* uglifyjs-webpack-plugin Version: 2.1.3

### Feature Proposal
Better error message when passing wrong options.

Example:
```js
{
  sourceMaps: true,
}
```

and I got this error

```
UglifyJs Plugin Invalid Options

options should NOT have additional properties

ValidationError: UglifyJs Plugin Invalid Options
```

we could print out the most similar option, same error message with:

```
Most similar option: `sourceMap`
```

In older versions, I get this error clarify which option is invalid

```
UglifyJs Plugin Invalid Options

options['sourceMaps'] is an invalid additional property

ValidationError: UglifyJs Plugin Invalid Options
```

### Feature Use Case
**Options**
```js
{
  sourceMaps: true,
}
```
**Output**
_if there is a similar option_
```diff
UglifyJs Plugin Invalid Options

+`sourceMaps` is invalid option
+ Most similar option: `sourceMap`
-options should NOT have additional properties

ValidationError: UglifyJs Plugin Invalid Options
```

**Output**
_if there is no similar option_

```diff
UglifyJs Plugin Invalid Options

+`sourceMaps` is invalid option
-options should NOT have additional properties

ValidationError: UglifyJs Plugin Invalid Options
```

I can open a PR for that if the suggestion got accepted.

**Comment by evilebottnawi** [comment]
Not related to this plugin, already WIP (https://github.com/webpack/schema-utils), will be shipped in next week, thanks for issue
