### ISSUE TITLE
There has a problem in version 2.1.3，when I import vconsole!!

### ISSUE THREAD

**Issue by licongwell** [webpack-contrib/uglifyjs-webpack-plugin#406]
* Operating System:MacOs 10.13.4
* Node Version:v11.12.0
* NPM Version:6.7.0
* webpack Version:4.35.0
* uglifyjs-webpack-plugin Version:2.1.3

### Expected Behavior

I used vconsole in my project, hoping to pack it properly.

### Actual Behavior

When I upgraded to version 2.1.3, I found that packaged files deployed in nginx would report errors.

### Code

```js
  // webpack.config.js
 const Uglifyjs = require('uglifyjs-webpack-plugin');
 new Uglifyjs({
     parallel: true,
     sourceMap: true,
     cache: true,
  })
```

```js
  // additional code, HEY YO remove this block if you don't need it
  import Vconsole from 'vconsole';
  new Vconsole();
```

### How Do We Reproduce?
1. npm install vconsole -D;
2. Use this Plugin in version 2.1.3;
3. Deploy packaged files on nginx；
4. Open the file,you will find this error in Browser：**Uncaught TypeError: Super expression must either be null or a function**

**Comment by evilebottnawi** [comment]
Please use terser-webpack-plugin
