### ISSUE TITLE
Please disable mangling by default

### ISSUE THREAD

**Issue by Sheeo** [webpack-contrib/uglifyjs-webpack-plugin#41]
As you note in your [README](https://github.com/webpack-contrib/uglifyjs-webpack-plugin#mangling) property mangling will probably break your code if you don't know how to use it, which is why your upstream UglifyJS disables it by default.

I don't understand what makes you, unlike your upstream, enable it by default, however. This cost me quite a bit of debugging time to figure out why our production build was arbitrarily breaking with a very niche thing in one of our dependencies.

**Comment by mlazowik** [comment]
I'm actually confused by the docs here. When we introduced webpack we've disabled mangling based on them, but they seem to be a bit misleading. Only _property_ mangling is dangerous. It's not clear for me if it's on by default or not.

**Comment by mlazowik** [comment]
By looking at the code looked like it's not. I enabled it manually and it made smaller bundles and actually broke the build, so this confirms it's not on by default.

Another issue is that docs link to uglify master, which is currently v3, but this plugin uses v2 (#32).

**Comment by mlazowik** [comment]
@Sheeo so if you got the error with default settings (you have not set `mangle.props` to `true` or config object) the report with some example code should go upstream to https://github.com/mishoo/UglifyJS2.

**Comment by Sheeo** [comment]
I think upstream's docs are a bit misleading, too -- toplevel variable name mangling can break code as well as property mangling, this was indeed happening in a dependency of mine. Upstream does disable all mangling by default, you have to explicitly enable it.

Thanks for the doc clarification on your end!

**Comment by michael-ciniawsky** [comment]
Fixed by #42, reopen if still regressions :)
