### ISSUE TITLE
Request help, create a vue project, build error

### ISSUE THREAD

**Issue by liuliuboy** [webpack-contrib/uglifyjs-webpack-plugin#411]
Request help, create a vue project, build error；Thank you！

- Operating System: mac
- Node Version: 12.10.0
- NPM Version: 6.10.3
- webpack Version: 4.41.0
- uglifyjs-webpack-plugin Version: ^2.2.0
### Actual Behavior

ERROR in static/js/30.ac7c0ddcd1da1e4a40a1.js from UglifyJs
Unexpected token: punc «(», expected: punc «:» [static/js/30.ac7c0ddcd1da1e4a40a1.js:19142,19]

package.json
 
"scripts": {
    "dev": "webpack-dev-server --inline --progress --config build/webpack.dev.conf.js",
    "build:prod": "cross-env NODE_ENV=production env_config=prod node build/build.js",
    "build:sit": "cross-env NODE_ENV=production env_config=sit node build/build.js",
    "lint": "eslint --ext .js,.vue src",
    "test": "npm run lint",
    "dll": "webpack --config ./build/webpack.dll.config.js"
  },
  "dependencies": {
    "axios": "0.17.1",
    "babel-polyfill": "^6.26.0",
    "clipboard": "1.7.1",
    "crypto-js": "^3.1.9-1",
    "echarts": "3.8.5",
    "element-tree-grid": "^0.1.3",
    "element-ui": "2.0.8",
    "es6-promise": "^4.2.4",
    "file-saver": "1.3.3",
    "font-awesome": "4.7.0",
    "jquery": "^3.3.1",
    "js-base64": "^2.4.5",
    "js-cookie": "2.2.0",
    "jsonlint": "1.6.2",
    "jszip": "3.1.5",
    "mockjs": "1.0.1-beta3",
    "moment": "^2.24.0",
    "normalize.css": "7.0.0",
    "nprogress": "0.2.0",
    "number-precision": "^1.3.1",
    "screenfull": "3.3.2",
    "showdown": "1.8.5",
    "sortablejs": "1.7.0",
    "svg-baker-runtime": "^1.3.3",
    "vue": "2.5.10",
    "vue-calendar-component": "^2.6.0",
    "vue-count-to": "1.0.13",
    "vue-enhanced-check": "^1.5.1",
    "vue-i18n": "7.3.2",
    "vue-loading-template": "^0.1.7",
    "vue-multiselect": "2.0.8",
    "vue-resource": "^1.3.5",
    "vue-router": "^3.0.1",
    "vue-simple-uploader": "^0.4.3",
    "vuex": "3.0.1"
  },
  "devDependencies": {
    "array-includes": "^3.0.3",
    "autoprefixer": "7.2.3",
    "babel": "^6.23.0",
    "babel-core": "6.26.0",
    "babel-helper-vue-jsx-merge-props": "2.0.3",
    "babel-loader": "7.1.2",
    "babel-plugin-syntax-jsx": "6.18.0",
    "babel-plugin-transform-runtime": "6.23.0",
    "babel-plugin-transform-vue-jsx": "3.5.0",
    "babel-preset-env": "1.6.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-2": "6.24.1",
    "babel-runtime": "^6.26.0",
    "chalk": "2.3.0",
    "copy-webpack-plugin": "^5.0.4",
    "cross-env": "5.1.1",
    "css-loader": "^3.2.0",
    "debug": "^3.1.0",
    "file-loader": "^4.2.0",
    "friendly-errors-webpack-plugin": "^1.7.0",
    "happypack": "^5.0.1",
    "html-webpack-plugin": "^3.2.0",
    "mini-css-extract-plugin": "^0.8.0",
    "node-notifier": "5.1.2",
    "node-sass": "^4.9.0",
    "optimize-css-assets-webpack-plugin": "^5.0.3",
    "ora": "1.3.0",
    "portfinder": "1.0.13",
    "postcss-import": "11.0.0",
    "postcss-loader": "^3.0.0",
    "postcss-url": "7.3.0",
    "prettier": "^1.12.1",
    "pushstate-server": "3.0.1",
    "rimraf": "2.6.2",
    "sass-loader": "^6.0.6",
    "sass-resources-loader": "^1.3.3",
    "script-loader": "0.7.2",
    "semver": "5.4.1",
    "shelljs": "0.7.8",
    "style-loader": "^0.21.0",
    "svg-sprite-loader": "^4.1.6",
    "uglifyjs-webpack-plugin": "^2.2.0",
    "url-loader": "^2.1.0",
    "vue-awesome-swiper": "^3.1.3",
    "vue-full-calendar": "^2.6.1",
    "vue-loader": "^15.7.1",
    "vue-style-loader": "3.0.3",
    "vue-template-compiler": "2.5.10",
    "webpack": "^4.41.0",
    "webpack-bundle-analyzer": "^3.5.2",
    "webpack-cli": "^3.3.9",
    "webpack-dev-server": "^3.8.1",
    "webpack-merge": "^4.2.2"
  },
  "engines": {
    "node": ">= 4.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}

webpack.base.conf.js
  'use strict'
const path = require('path')
const webpack = require("webpack")
const utils = require('./utils')
const config = require('../config')
// const vueLoaderConfig = require('./vue-loader.conf')
const manifest = require('../vendor-manifest.json')
const HappyPack = require('happypack');
const os = require('os')
const happyThreadPool = HappyPack.ThreadPool({ size: os.cpus().length })
const VueLoaderPlugin = require('vue-loader/lib/plugin')

function resolve (dir) {
  return path.join(__dirname, '..', dir)
}

// const createLintingRule = () => ({
//   test: /\.(js|vue)$/,
//   loader: 'eslint-loader',
//   enforce: 'pre',
//   include: [resolve('src'), resolve('test')],
//   options: {
//     formatter: require('eslint-friendly-formatter'),
//     emitWarning: !config.dev.showEslintErrorsInOverlay
//   }
// })

module.exports = {
  mode: process.env.NODE_ENV,
  context: path.resolve(__dirname, '../'),
  entry: {
    app: ['babel-polyfill','./src/main.js']
  },
  output: {
    path: config.build.assetsRoot,
    filename: '[name].js',
    publicPath: process.env.NODE_ENV === 'production'
      ? config.build.assetsPublicPath
      : config.dev.assetsPublicPath
  },
  resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      'vue$': 'vue/dist/vue.esm.js',
      '@': resolve('src'),
      'jquery': path.resolve(__dirname, '../node_modules/jquery/src/jquery')
    }
  },
  module: {
    rules: [
      // ...(config.dev.useEslint ? createLintingRule : []),
      // {
      //   test: /\.(js|vue)$/,
      //   loader: 'eslint-loader',
      //   enforce: 'pre',
      //   include: [resolve('src'), resolve('test')],
      //   options: {
      //       formatter: require('eslint-friendly-formatter'),
      //       emitWarning: !config.dev.showEslintErrorsInOverlay
      //   }
      // },
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        // options: vueLoaderConfig
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test')]
      },
      {
        test: /\.svg$/,
        loader: 'svg-sprite-loader',
        include: [resolve('src/icons')],
        options: {
          symbolId: 'icon-[name]'
        }
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url-loader',
        exclude: [resolve('src/icons')],
        options: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(mp4|webm|ogg|mp3|wav|flac|aac)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('media/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 80000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      },
      {
        test: /.sass$/,
        loaders: ['style', 'css', 'sass']
      },
      {
        test: /\.js$/,
        // loader: 'babel-loader',
        loader: 'happypack/loader?id=happy-babel-js', // 增加新的HappyPack构建loader
        include: [resolve('src'), resolve('test')]
      }
    ],
  },
  node: {
    // prevent webpack from injecting useless setImmediate polyfill because Vue
    // source contains it (although only uses it if it's native).
    setImmediate: false,
    // prevent webpack from injecting mocks to Node native modules
    // that does not make sense for the client
    dgram: 'empty',
    fs: 'empty',
    net: 'empty',
    tls: 'empty',
    child_process: 'empty'
  },

  performance: {
    hints: "warning", // 枚举
    maxAssetSize: 30000000, // 整数类型（以字节为单位）
    maxEntrypointSize: 50000000, // 整数类型（以字节为单位）
    assetFilter: function(assetFilename) {
      // 提供资源文件名的断言函数
      return assetFilename.endsWith('.css') || assetFilename.endsWith('.js');
    }
  },

  plugins: [
    new webpack.DllReferencePlugin({
      context: __dirname,
      manifest: manifest
    }),
    new VueLoaderPlugin(),
    new HappyPack({
      id: 'happy-babel-js',
      loaders: ['babel-loader?cacheDirectory=true'],
      threadPool: happyThreadPool,
    })
  ]
}

.babelrc
 {
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
      "browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
      }
    }],
    ["es2015"],
    "stage-2"
  ],
  "plugins": []
}

**Comment by evilebottnawi** [comment]
Please migrate on https://github.com/webpack-contrib/terser-webpack-plugin, uglifyjs doesn't support ES6 syntax

**Comment by left-handed** [comment]
Thanks answer
