### ISSUE TITLE
npm (Node.js <7.1) bug prevents from developing using 'npm link'

### ISSUE THREAD

**Issue by Kitanotori** [webpack-contrib/uglifyjs-webpack-plugin#5]
Although not a bug of this project, I thought I would share my findings here. I've been mostly developing with the latest LTS version of Node.js (currently 6.9.4), but it seems there is a bug in versions prior to 7.1 that prevents resolving peer dependencies when using `npm link` due to issues with symlinks. 

The solution is to run the linked project with Node.js >= 7.1 and either `--preserve-symlinks` flag or `NODE_PRESERVE_SYMLINKS=1` environment variable.

https://github.com/npm/npm/issues/5875
https://github.com/npm/npm/issues/5080
https://nodejs.org/api/cli.html#cli_preserve_symlinks

**Comment by Kitanotori** [comment]
@bebraw How are you usually developing npm projects, by the way? Particularly interested in how to smoothly test an npm project via other project.

**Comment by bebraw** [comment]
I tend to avoid `npm link` as it has been too glitchy with webpack in the past. That said, if you can set up something to study, I don't mind having a look.

**Comment by michael-ciniawsky** [comment]
Reopen if still relevant, but emms to be unrelated to `uglifyjs-webpack-plugin` in particular, so cclosing for now 😛
