### ISSUE TITLE
v0.4.6 set uglify-js@^2.8.29 Invalidate uglify-js#harmony-v2.8.22

### ISSUE THREAD

**Issue by aegisho** [webpack-contrib/uglifyjs-webpack-plugin#68]
my package.json
```
"uglify-js": "git://github.com/mishoo/UglifyJS2#harmony-v2.8.22",
"uglifyjs-webpack-plugin": "v0.4.6",
```

it's fine with  uglifyjs-webpack-plugin@0.4.4

i use yarn v0.21.3，node@v6.9.2
npm@3.10.9 has same problem

please recovery uglify-js version

**Comment by michael-ciniawsky** [comment]
Try `v1.0.0-beta.1` `npm i -D uglifyjs-webpack-plugin@beta` which contains an upgrade to `uglify-es` (UglifyJS v3.0.0) instead please. There won't be any changes to `< v1.0.0`
