### ISSUE TITLE
all folders missing from package on npm install

### ISSUE THREAD

**Issue by torvitas** [webpack-contrib/uglifyjs-webpack-plugin#70]
Version: master

Hi,

since you added ./dist/ to gitignore its not anymore included when installed via npm. The other folders aren't included either since you specified files: ["dist"] in package.json.

Greetings, Sascha

**Comment by michael-ciniawsky** [comment]
This only happens, when `npm i` via `git` ?

**Comment by torvitas** [comment]
Of course, how else would you be able to install master?

**Comment by michael-ciniawsky** [comment]
`npm i -D uglifyjs-webpack-plugin@beta`

**Comment by torvitas** [comment]
ah, didn't know that, thank you!
