### ISSUE TITLE
feature: Add logic to ensure only 1 UglifyJsPlugin's instance per compiler

### ISSUE THREAD

**Issue by hulkish** [webpack-contrib/uglifyjs-webpack-plugin#72]
## Problem:
Currently, I think it's too easy to accidentally apply 2 instances of UglifyJsPlugin to the same compiler/compilation.

### Scenario:
- You are a webpack newb
- You need to make a production build
- You learn UglifyJsPlugin is the recommended way to minify your bundle, so you make a `webpack.config.prod.js` and include UglifyJsPlugin.
- You learn that it's recommended to use the `--optimize-minimize/-p` argument with webpack cli, so u make a production build script:
```
"scripts": {
  "build:prod": "webpack -p"
}
```

Since this webpack cli option auto-adds the UglifyJsPlugin: 
- You now have attached 2 separate instances of the same plugin.
- Your production build is 'gon be sloowwwwww

## Solution
Add a guard to the top of `UglifyJsPlugin` class method `apply` which restricts multiple instances of the plugin from being applied to the same compiler, like so:

```js
class UglifyJsPlugin {
  static appliedCompilers = new WeakSet();

  // then use it as a guard:
  apply(compiler) {
    if (UglifyJsPlugin.appliedCompilers.has(compiler)) return;
    appliedCompilers.add(compiler);
    [...]
  }
}
```

### "But... that's user error"
Yes, it absolutely is. However, I have personally come across the mistake several times. My thinking is... the negative impact this potentially introduces is worth safeguarding against.

**Comment by michael-ciniawsky** [comment]
Does `UglifyJSPlugin.name` work (`Function.prototype.name`) ? Would it be worthwhile to consider filtering plugin duplicates generally in webpack? Is it needed to `add` the whole compiler, why not `static isApplied = false // {Boolean} && if (isApplied) return\n isApplied = true`?

**Comment by hulkish** [comment]
@michael-ciniawsky I think so... but if I recall correctly there is differences in this behavior between `node@4.3` - `node@8` etc. I'd have to look.

**Comment by hulkish** [comment]
@michael-ciniawsky Also, keep in mind that its adding the compiler to a `WeakSet`, therefore memory issues relating to "storing" the compiler can be absolved.

**Comment by bebraw** [comment]
I would go with a property that webpack core interprets. That pushes the problem to the right place.

**Comment by hulkish** [comment]
@bebraw So, problem with that... It only works if its always the compiler.apply that is called. However, when you call `MyPlugin.apply` - that doesn't prevent it from being applied twice or more.

**Comment by bebraw** [comment]
@hulkish I'm not sure. It's better to get Tobias' input on that.

**Comment by indutny** [comment]
What if I want to use the plugin anyway? Like I have different passes of optimizations and want to apply it after each pass?

**Comment by hulkish** [comment]
@indutny can you give an example?

**Comment by indutny** [comment]
Several passes of tree shaking? (I don't use it currently, but it may have uses in the future).

1. Remove unused `exports.a = ...`
2. Remove dead code with uglify
3. Remove more unused `exports.a = ...` that appeared because the dead code is gone
4. Apply uglify again?

Anyway, I think it should be better to just print warning rather than skipping the step altogether.

**Comment by hulkish** [comment]
@indutny Wouldn't uglify running once *after` tree shaking? I would hope that nothing would ever "need" to be uglified more than once. Since, it's such a heavy task.

**Comment by indutny** [comment]
Uh, right... bad example. I'll have to think if I can come up with anything else.

All in all, it still feels "unsafe" to disable the plugin if it is used twice. In my opinion, warning is better.

**Comment by hulkish** [comment]
@indutny True, and I totally agree this should not be applied to all plugins. I think it should be instantiated from the plugin itself. As explained in option #2 here: https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/72#issuecomment-313854965

**Comment by sokra** [comment]
I guess we could a a unique check to the `apply` method of `Tapable`. If the plugin has a `unique` property:

* `unique === true`: We add `plugin.constructor` to a Set.
* `unique` is truthy: We add `plugin.unique` to a Set.

This way babli-plugin and uglifyjs-plugin could set `unique = "asset-minimize"`.

---

Anyway there is a case where you want to apply the uglifyjs plugin multiple times:

``` js
new UglifyJsPlugin({
  include: /file\.js$/,
  compress: true
})
new UglifyJsPlugin({
  include: /other-file\.js$/,
  compress: { /* some special options */ }
})
```

**Comment by mikesherov** [comment]
I don't think this can be solved generically. As Tobias has shown above, there is no generic case where, even for Uglify, where we know uniqueness should happen. 

There are two things we can do: 
1. If user has supplied the `p` flag, ensure that the plugins that are added by that flag aren't also added manually.
2. Make sure the optimize plugins all use cache so that even if they are applied twice, the second run is essentially a no-op.

**Comment by hulkish** [comment]
Per that use case @sokra mentioned for using UglifyJsPlugin multiple - I feel like it would be better if we even still forced the unique behavior. And, instead provided a way for them to accomplish the same using during a single pass of the plugin''s event handlers.

Maybe something like:

```js
new UglifyJsPlugin({
  optionsPerAsset: [
    {
      include: /file\.js$/,
      compress: true
    },
    {
      include: /other-file\.js$/,
      compress: { /* some special options */ }
    },
  ]
})
```

**Comment by mikesherov** [comment]
Point is, there is a lot we can do for *individual plugins*, and with that in mind, having a generic "unique plugin" system seems overkill for handling just the specific cases, but that's just my opinion, and I'm not stuck on it :-)

**Comment by hulkish** [comment]
@mikesherov I agree, this could just as easily be totally the responsibility of the plugin. That was my original idea but wondered what u folks think.

**Comment by mikesherov** [comment]
Exactly. I'm just saying what I think ;-)

**Comment by hulkish** [comment]
Closing this in light of https://github.com/webpack/webpack/pull/5248#issuecomment-316705008

**Comment by tstackhouse** [comment]
@hulkish I think I have an example use-case to @indutny's point of multiple uglify instances: Say I have all my application logic in `main.bundle.js` and I have my vendor libraries in `vendor.bundle.js`.  I can uglify my app code, including mangling and everything still works, but if I apply mangling to my vendor code, things break horribly (and are very difficult to trace).  Therefore I want to set up 2 copies of the plugin, one to uglify my application logic with mangling enabled, and another for my vendor libraries, without mangling.
