### ISSUE TITLE
bug: uglifyjs-weback-plugin@1.0.0-beta.1 breaks with MultiCompiler

### ISSUE THREAD

**Issue by hulkish** [webpack-contrib/uglifyjs-webpack-plugin#73]
[This line](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/src/index.js#L152) breaks support for `webpack/lib/MultiCompiler` because a `MultiCompiler` instance child compiler does not have a `context`.

**Comment by nkovacs** [comment]
I have the same problem with worker-loader: https://github.com/webpack-contrib/worker-loader/issues/92
