### ISSUE TITLE
Update plugin

### ISSUE THREAD

**Issue by SebastianS90** [webpack-contrib/uglifyjs-webpack-plugin#8]
[Several commits](https://github.com/webpack/webpack/commits/master/lib/optimize/UglifyJsPlugin.js) have been applied to the plugin in webpack/webpack, so we should update it here as well.

Simply copying the new version will lead to a bunch of linting errors, because the projects use different eslint configurations.

**Comment by bebraw** [comment]
Yeah, keeping these in sync is going to be tough...

**Comment by SebastianS90** [comment]
I created #9, but there is the linting problem I mentioned above.

Probably it would be best to automate the sync somehow or at least to have a script that does the sync on a manual trigger.

**Comment by bebraw** [comment]
Fully automatic sync is not possible as the linting rules require some code to be rewritten in a slightly different way.

The problem would go away if both the core and the plugin adhered to the same style. `webpack-defaults` might solve this given some time.
