### ISSUE TITLE
an error got when building

### ISSUE THREAD

**Issue by zzzgit** [webpack-contrib/uglifyjs-webpack-plugin#82]
![image](https://user-images.githubusercontent.com/1060733/28237918-a09ec9ce-697b-11e7-98d3-66349c82282e.png)

![image](https://user-images.githubusercontent.com/1060733/28237923-b8d667a4-697b-11e7-8264-62ef60799173.png)

I got an error when using this plugin

**Comment by zzzgit** [comment]
node v6.10.1
webpack 2.6.1

**Comment by evilebottnawi** [comment]
@zzzgit seems your use `babel-loader` and something don't compile to ES5, can your give more information about version plugin and example code from `5.js`?

**Comment by hulkish** [comment]
@zzzgit can u try using the `ecma` option? ex:
```
new UglifyJsPlugin ({ uglifyjsOptions: { ecma: 8 } })
```

Also, make sure you're not using a module transforn babel plugin... For ex... set  `modules: false` if you're using babel-preset-es2015 or babel-preset-env.

**Comment by michael-ciniawsky** [comment]
@zzzgit Ensure to either transpile your JS to ES5 when using `<= v0.4.6` or if you use `>= v1.0.0-beta.0` see @hulkish's comment and feel free to reopen if still regressions :)

**Comment by zzzgit** [comment]
update to `v1.0.0-beta.0`, and then` { uglifyjsOptions: { ecma: 8 } }`, now it works
