### ISSUE TITLE
Missing documentation & changelog on `uglifyOptions`

### ISSUE THREAD

**Issue by Akkuma** [webpack-contrib/uglifyjs-webpack-plugin#85]
There doesn't seem to be any mention of `uglifyOptions` anywhere in the 1.0.0-beta.1, which I didn't know about until I dug into the source code to resolve a problem that cropped up due to it.

**Comment by michael-ciniawsky** [comment]
Currently in => `beta` <= PR is here (#61), `develop`, `next`, `beta` branch would be better agreed, but we don't have one atm 😛
