### ISSUE TITLE
options structure convention

### ISSUE THREAD

**Issue by osadan** [webpack-contrib/uglifyjs-webpack-plugin#88]
I tried to use uglify-es with angular-cli (v "1.3.0-beta.1") 
and switch to uglify-webpack-plugin version 1.0.0 -beta.1
I tried to play around with the options (modify mangle,sourcemap,comments)
and I saw that inside UglifyJsPlugin that there is no uglifyOptions property inside options just options
which lead to that the plugin will not recognized the options coming from webpack/angular-cli
```
 this.uglifyOptions = this.options.uglifyOptions || {};
```

**Comment by michael-ciniawsky** [comment]
The need to be updated in `angular-cli` as soon as UglifyJSPlugin `v1.0.0` is out of `beta`. Please open an tracking issue in Angular CLI aswell :)

**Comment by osadan** [comment]
reference to angular cli issue https://github.com/angular/angular-cli/issues/7063
