### ISSUE TITLE
docs(README): `UglifyJS v3` should be `uglify-es`

### ISSUE THREAD

**Issue by kzc** [webpack-contrib/uglifyjs-webpack-plugin#89]
The current [README](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/8459b4678d08af43d487a1d491778611fe5af7ec/README.md#uglifyjs-webpack-plugin) states:

> This plugin uses UglifyJS v3 to minify your JavaScript

That is incorrect. 

`uglify-js@3` only handles ES5, whereas `uglify-es` handles ES6+.

The README should state:

> This plugin uses `uglify-es` to minify your JavaScript

**Comment by michael-ciniawsky** [comment]
I thought `UglifyJS v3` is `uglify-es` on npm, where the `-es` is the 'harmony'  branch/version of `uglify` (ES2015+), your release/package management is very confusing :). Is it absolutely incorrect to refer to a Uglify**JS** version? If so, please let me know and I will fix it later then 😛 . Anything else which isn't correct ?

**Comment by kzc** [comment]
I appreciate that the nomenclature is confusing.

[`uglify-es`](https://github.com/mishoo/UglifyJS2/tree/harmony) is the [npm package name](https://www.npmjs.com/package/uglify-es) based off of the `harmony` branch of uglify supporting ES6+. The `master` branch of the [`UglifyJS2` repository](https://github.com/mishoo/UglifyJS2) presently only supports ES5 and has the npm package name "uglify-js".

I suppose that `uglify-es` could loosely be called "Uglify" or "UglifyJS" but when v3 is used there is ambiguity between it and `uglify-js`. `uglify-js@3` only handles ES5, whereas `uglify-es@3` handles ES6+. It is fair to say that both share the UglifyJS v3 *API*, although the `uglify-es` API is a superset of the `uglify-js@3` API. 

Perhaps one day `uglify-es` could be merged into the mainline `uglify-js` but that's a call for the maintainer of uglify.
