### ISSUE TITLE
uglifyOptions aren't working – passing option without works

### ISSUE THREAD

**Issue by julmot** [webpack-contrib/uglifyjs-webpack-plugin#90]
When I pass `compress` as a child of `uglifyOptions` the console statements will not be removed.

```javascript
  config.plugins.push(new webpack.optimize.UglifyJsPlugin({
    uglifyOptions: {
      compress: {
        drop_console: true
      }
    }
  }));
```

But this works:

```javascript
  config.plugins.push(new webpack.optimize.UglifyJsPlugin({
    compress: {
      drop_console: true
    }
  }));
```

I'm using Webpack v3.4.1.

**Comment by michael-ciniawsky** [comment]
`uglifyOptions` is the new `options` interface for `uglifyjs-webpack-plugin >= v1.0.0-beta` currently usable via `npm i -D uglifyjs-webpack-plugin@beta`, webpack by default ships with `uglifyjs-webpack-plugin v0.4.6` which uses the 'old' interface without `uglifyOptions`. This will change in the near future when `uglifyjs-webpack-plugin v1.0.0` is out of `beta`

**Comment by kmvan** [comment]
In version 1.0.0-beta.2
drop_console not works
config is:
    uglifyOptions: {
      compress: {
        drop_console: true
      }
    }

**Comment by PixnBits** [comment]
@kmvan using 1.0.1 allowed me to use 
```
new UglifyJSPlugin({
  uglifyOptions: {
    compress: {
      drop_console: true,
    },
  }
})
```

**Comment by kmvan** [comment]
@PixnBits Thank you, works.
