### ISSUE TITLE
[v1.0.0] Release Date (?)

### ISSUE THREAD

**Issue by samouri** [webpack-contrib/uglifyjs-webpack-plugin#95]
First off I wanted to say thank you for all of the excellent work!
I've been playing with the `v1.0.0-beta.2` release for the past week and its incredibly fast + pleasant to use.  

I was wondering if there was any rough timeline for when 1.0 would get out of beta? Would you guess on the order of days/weeks or months?

Thanks!

**Comment by d3viant0ne** [comment]
Realistically, weeks. Prior to release ( latest tag ) on the big ticket items & once everything is solid enough code wise, the change also needs to be communicated & tested for the major integrations that everyone else in turn uses. e.g Create-React-App, Angular/cli and so on.
